(()=>{
'use strict';
const MAX_COINS=40, EXCLUDE=new Set(['USDC','BUSD','TUSD','FDUSD','USDP','DAI','EUR','GBP','EURI','USTC','PAX','UST','WBTC','WBETH']);
const coins={}, order=[]; let ws=null, filter=null, search='', sort='intel', cgBySymbol={}, validation=null, botBrain=null, currentRegime=null;
const watch=new Set(JSON.parse(localStorage.getItem('wavelength_watchlist')||'[]'));
const alerts=JSON.parse(localStorage.getItem('wavelength_alert_log')||'[]');
const opportunities=JSON.parse(localStorage.getItem('wavelength_opportunities')||'[]');
const priorState=JSON.parse(localStorage.getItem('wavelength_prior_state')||'{}');
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const n=(v,d=2)=>v==null||!Number.isFinite(+v)?'—':(+v).toLocaleString('en-US',{maximumFractionDigits:d,minimumFractionDigits:d});
const money=v=>v==null||!Number.isFinite(+v)?'—':(+v>=1?'$'+(+v).toLocaleString('en-US',{maximumFractionDigits:2,minimumFractionDigits:2}):'$'+(+v).toLocaleString('en-US',{maximumFractionDigits:8}));
const compact=v=>v==null||!Number.isFinite(+v)?'—':new Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:2}).format(+v);
const pct=v=>v==null||!Number.isFinite(+v)?'—':`${+v>=0?'+':''}${n(+v,2)}%`;
const cls=v=>+v>0?'up':+v<0?'down':'neutral';
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
function getJSON(url){return fetch(url).then(r=>{if(!r.ok)throw new Error(`${r.status} ${url}`);return r.json()})}
function save(){localStorage.setItem('wavelength_watchlist',JSON.stringify([...watch]));localStorage.setItem('wavelength_alert_log',JSON.stringify(alerts.slice(0,50)));localStorage.setItem('wavelength_opportunities',JSON.stringify(opportunities.slice(-80)));localStorage.setItem('wavelength_prior_state',JSON.stringify(priorState))}
function setFeed(state){const el=$('#feedStatus');if(!el)return;el.className='status-pill '+(state==='live'?'':state==='bad'?'bad':'warn');el.innerHTML=`<span class="dot"></span>${state==='live'?'LIVE':state==='bad'?'OFFLINE':'CONNECTING'}`}
function ema(vals,p){if(vals.length<p)return null;const k=2/(p+1);let e=vals.slice(0,p).reduce((a,b)=>a+b,0)/p;for(let i=p;i<vals.length;i++)e=vals[i]*k+e*(1-k);return e}
function rsi(vals,p=14){if(vals.length<=p)return null;let gain=0,loss=0;for(let i=1;i<=p;i++){const d=vals[i]-vals[i-1];gain+=Math.max(d,0);loss+=Math.max(-d,0)}gain/=p;loss/=p;for(let i=p+1;i<vals.length;i++){const d=vals[i]-vals[i-1];gain=(gain*(p-1)+Math.max(d,0))/p;loss=(loss*(p-1)+Math.max(-d,0))/p}if(loss===0)return 100;const rs=gain/loss;return 100-100/(1+rs)}
function atrAndAdx(ks,p=14){if(ks.length<p*2+2)return{atr:null,adx:null};const tr=[],plus=[],minus=[];for(let i=1;i<ks.length;i++){const h=+ks[i][2],l=+ks[i][3],pc=+ks[i-1][4],ph=+ks[i-1][2],pl=+ks[i-1][3];tr.push(Math.max(h-l,Math.abs(h-pc),Math.abs(l-pc)));const up=h-ph,down=pl-l;plus.push(up>down&&up>0?up:0);minus.push(down>up&&down>0?down:0)}let atr=tr.slice(0,p).reduce((a,b)=>a+b,0)/p,ps=plus.slice(0,p).reduce((a,b)=>a+b,0)/p,ms=minus.slice(0,p).reduce((a,b)=>a+b,0)/p;const dx=[];for(let i=p;i<tr.length;i++){atr=(atr*(p-1)+tr[i])/p;ps=(ps*(p-1)+plus[i])/p;ms=(ms*(p-1)+minus[i])/p;const pdi=atr?100*ps/atr:0,mdi=atr?100*ms/atr:0;dx.push((pdi+mdi)?100*Math.abs(pdi-mdi)/(pdi+mdi):0)}if(dx.length<p)return{atr,adx:null};let adx=dx.slice(0,p).reduce((a,b)=>a+b,0)/p;for(let i=p;i<dx.length;i++)adx=(adx*(p-1)+dx[i])/p;return{atr,adx}}
function technicals(ks){const closes=ks.map(k=>+k[4]),vols=ks.map(k=>+k[5]),close=closes.at(-1),e20=ema(closes,20),e80=ema(closes,80),e200=ema(closes,200),R=rsi(closes),aa=atrAndAdx(ks),atrPct=aa.atr&&close?aa.atr/close*100:null;const recent=vols.slice(-4).reduce((a,b)=>a+b,0)/4,prior=vols.slice(-24,-4),avg=prior.length?prior.reduce((a,b)=>a+b,0)/prior.length:null,volRatio=avg?recent/avg:null;const bull=e20>e80&&close>e200,bear=e20<e80&&close<e200,setup=bull&&R>=50&&R<=75&&aa.adx>=35;let score=0;if(e20>e80)score+=20;if(close>e200)score+=20;if(R>=50&&R<=75)score+=20;if(aa.adx>=35)score+=20;if(volRatio>=1)score+=10;return{close,ema20:e20,ema80:e80,ema200:e200,rsi:R,adx:aa.adx,atrPct,volRatio,bull,bear,setup,score}}
function perfFromDaily(ks,days){if(!ks?.length)return null;const closes=ks.map(k=>+k[4]);if(closes.length<=days)return null;const a=closes.at(-1),b=closes[closes.length-1-days];return b?100*(a/b-1):null}
function dailyReturns(ks,limit=60){const c=(ks||[]).map(k=>+k[4]).slice(-(limit+1)),r=[];for(let i=1;i<c.length;i++)if(c[i-1])r.push(c[i]/c[i-1]-1);return r}
function corr(a,b){const m=Math.min(a.length,b.length);if(m<10)return null;a=a.slice(-m);b=b.slice(-m);const ma=a.reduce((x,y)=>x+y,0)/m,mb=b.reduce((x,y)=>x+y,0)/m;let num=0,da=0,db=0;for(let i=0;i<m;i++){const x=a[i]-ma,y=b[i]-mb;num+=x*y;da+=x*x;db+=y*y}return da&&db?num/Math.sqrt(da*db):null}
function derivativeRead(c){const d=c.deriv;if(!d)return'No perp data';const f=d.funding||0,oi=d.oiChange24h,px=c.chg_24h||0;if(f>.0005&&px>2)return'Crowded longs';if(f<-.0005&&px<-2)return'Crowded shorts';if(oi>5&&px>2)return'Fresh long build';if(oi>5&&px<-2)return'Fresh short build';if(oi<-5&&Math.abs(px)>2)return'Deleveraging';return'Balanced'}
function intelligenceScore(c){const t=c.tech;if(!t||t.error)return 0;let s=t.score||0;const rs=c.relative||{};if((rs.vsBtc30||0)>5)s+=8;else if((rs.vsBtc30||0)>0)s+=4;if((rs.d90||0)>20)s+=5;if(t.volRatio>=1.25)s+=5;if(t.atrPct>7)s-=8;if(t.rsi>75)s-=8;if(c.deriv){const f=Math.abs(c.deriv.funding||0);if(f>.001)s-=8;if(c.deriv.oiChange24h>8&&c.chg_24h>2)s+=4}return clamp(Math.round(s),0,100)}
function intelExplanation(c){const t=c.tech,parts=[];if(!t)return'Waiting for technical scan.';parts.push(t.bull?'Bullish trend structure':t.bear?'Bearish trend structure':'Mixed trend structure');if(t.adx>=35)parts.push(`strong ADX ${n(t.adx,1)}`);else if(t.adx>=25)parts.push(`developing ADX ${n(t.adx,1)}`);else parts.push(`weak ADX ${n(t.adx,1)}`);if(c.relative?.vsBtc30>5)parts.push(`outperforming BTC by ${n(c.relative.vsBtc30,1)}% over 30d`);else if(c.relative?.vsBtc30<-5)parts.push(`lagging BTC by ${n(Math.abs(c.relative.vsBtc30),1)}% over 30d`);if(t.volRatio>=1.25)parts.push('volume expanding');if(t.rsi>75)parts.push('momentum stretched');if(c.deriv?.funding>.0005)parts.push('positive funding is crowded');if(c.deriv?.oiChange24h>8)parts.push('open interest is building quickly');return parts.join(' · ')+'.'}
function pushAlert(type,message,symbol=null){const key=`${type}|${symbol||''}|${message}`;if(alerts[0]?.key===key)return;const item={key,type,message,symbol,time:new Date().toISOString()};alerts.unshift(item);if(alerts.length>50)alerts.length=50;save();renderAlerts();if(Notification.permission==='granted')try{new Notification('Wavelength',{body:message,tag:key})}catch{}}
function evaluateCoinAlerts(c){if(!c.tech)return;const p=priorState[c.symbol]||{};if(c.tech.setup&&!p.setup)pushAlert('SETUP',`${c.symbol} has entered V3-like technical conditions.`,c.symbol);if(c.tech.adx>=35&&(p.adx==null||p.adx<35))pushAlert('ADX',`${c.symbol} ADX crossed 35 (${n(c.tech.adx,1)}).`,c.symbol);if(p.bull===true&&!c.tech.bull)pushAlert('TREND',`${c.symbol} lost its bullish Wavelength trend structure.`,c.symbol);priorState[c.symbol]={setup:c.tech.setup,adx:c.tech.adx,bull:c.tech.bull,intel:c.intelScore};save()}
function trackOpportunity(c){if(!c.tech||!c.price)return;const active=opportunities.find(o=>o.symbol===c.symbol&&!o.done);if(c.tech.setup&&!active){opportunities.push({symbol:c.symbol,start:Date.now(),entry:c.price,score:c.intelScore||0,h:{},done:false});pushAlert('OPPORTUNITY',`${c.symbol} opportunity tracking started at ${money(c.price)}.`,c.symbol)}const rec=opportunities.find(o=>o.symbol===c.symbol&&!o.done);if(!rec)return;const age=Date.now()-rec.start;[['4h',4],['24h',24],['3d',72],['7d',168]].forEach(([k,h])=>{if(!rec.h[k]&&age>=h*3600000)rec.h[k]=100*(c.price/rec.entry-1)});if(rec.h['7d']!=null)rec.done=true;save()}
function updateOpportunities(){order.forEach(s=>{const c=coins[s];if(c)trackOpportunity(c)});renderOpportunities()}
function renderOpportunities(){const el=$('#opportunityHistory');if(!el)return;const rows=opportunities.slice(-8).reverse();if(!rows.length){el.innerHTML='<div class="empty">No tracked opportunities yet. Wavelength will start a record when a market enters V3-like conditions.</div>';return}el.innerHTML=`<div class="table-wrap"><table class="market-table"><thead><tr><th class="left">Coin</th><th>Entry</th><th>4h</th><th>24h</th><th>3d</th><th>7d</th></tr></thead><tbody>${rows.map(o=>`<tr data-open="${o.symbol}"><td class="left">${o.symbol}</td><td>${money(o.entry)}</td>${['4h','24h','3d','7d'].map(k=>`<td class="${cls(o.h[k])}">${o.h[k]==null?'…':pct(o.h[k])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
async function loadValidation(){try{validation=await getJSON(`validation.json?t=${Date.now()}`);const g=$('#validationGrid');$('#validationMeta').textContent=`Fresh evidence only · updated ${validation.generated_at?new Date(validation.generated_at).toLocaleString():'—'} · orders disabled`;g.innerHTML=Object.values(validation.strategies||{}).map(validationCard).join('');for(const [k,s] of Object.entries(validation.strategies||{})){const pk=`validation_${k}`,old=priorState[pk];if(old&&old.position!==s.position)pushAlert('VALIDATION',`${s.name} shadow position changed ${old.position} → ${s.position}.`);if(old&&old.status!==s.status)pushAlert('VALIDATION',`${s.name} status changed ${old.status} → ${s.status}.`);priorState[pk]={position:s.position,status:s.status}}save()}catch{$('#validationGrid').innerHTML='<div class="empty">Validation feed unavailable.</div>'}}
function validationCard(s){const min=s.minimums||{},tradeP=min.completed_trades?Math.min(100,(s.completed_trades||0)/min.completed_trades*100):0,dayP=min.calendar_days?Math.min(100,(s.observation_days||0)/min.calendar_days*100):0,progress=Math.min(tradeP,dayP),stat=s.status||'UNKNOWN',bc=stat.includes('FAIL')?'bad':stat.includes('ELIGIBLE')?'good':'warn';return `<article class="validation-card metric"><div class="validation-top"><div><div class="strategy-name">${esc(s.name)}</div><div class="card-meta">Shadow ${esc(s.position)} · ${n(s.observation_days||0,1)} / ${min.calendar_days||'—'} days</div></div><span class="badge ${bc}">${esc(stat.replaceAll('_',' '))}</span></div><div class="grid4"><div><div class="metric-label">Fresh trades</div><div class="metric-value">${s.completed_trades||0}/${min.completed_trades||'—'}</div></div><div><div class="metric-label">Return</div><div class="metric-value ${cls(s.return_pct)}">${pct(s.return_pct)}</div></div><div><div class="metric-label">Drawdown</div><div class="metric-value ${cls(s.max_drawdown_pct)}">${pct(s.max_drawdown_pct)}</div></div><div><div class="metric-label">Profit factor</div><div class="metric-value">${s.profit_factor==null?'—':n(s.profit_factor,2)}</div></div></div><div class="progress"><span style="width:${progress}%"></span></div><div class="gate-list">Waiting on: ${(s.unmet_gates||[]).map(esc).join(' · ')||'No unmet gates'}</div></article>`}
async function loadBot(){try{botBrain=await getJSON(`bot-brain.json?t=${Date.now()}`);const b=botBrain,action=(b.action||'UNKNOWN').replaceAll('_',' ');$('#botBadge').textContent=action;$('#botBadge').className='badge '+(b.action==='WOULD_ENTER'||b.action==='HOLD'?'good':'');$('#botMeta').textContent=`${b.symbol||'ETH/USD'} · ${b.timeframe||'4Hour'} · ${b.validation_status||'forward test'} · orders disabled`;$('#botGrid').innerHTML=[['Decision',action,''],['Trend',b.trend_ok?'BULLISH':'NOT QUALIFIED',b.trend_ok?'up':'neutral'],['ADX',b.adx==null?'—':n(b.adx,1),b.trend_strength_ok?'up':'neutral'],['RSI',b.rsi==null?'—':n(b.rsi,1),b.momentum_ok?'up':'neutral'],['ATR',b.atr_pct==null?'—':n(b.atr_pct,2)+'%',''],['Candle close',money(b.close),''],['EMA 20 / 80',b.fast_above_slow?'BULLISH':'BEARISH',b.fast_above_slow?'up':'down'],['Shadow position',b.has_position?'LONG':'FLAT',b.has_position?'up':'neutral']].map(x=>`<div class="metric"><div class="metric-label">${x[0]}</div><div class="metric-value ${x[2]}">${x[1]}</div></div>`).join('')}catch{$('#botGrid').innerHTML='<div class="empty">Bot brain unavailable.</div>'}}
async function fundamentals(){try{const list=await getJSON('https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=200&page=1&sparkline=false&price_change_percentage=7d,30d');list.forEach(c=>{const s=(c.symbol||'').toUpperCase();if(!cgBySymbol[s]||c.market_cap_rank<(cgBySymbol[s].market_cap_rank||99999))cgBySymbol[s]=c;if(coins[s])Object.assign(coins[s],{name:c.name,image:c.image,rank:c.market_cap_rank,market_cap:c.market_cap,circulating_supply:c.circulating_supply,ath_change_pct:c.ath_change_percentage,fdv:c.fully_diluted_valuation})});render()}catch(e){console.warn('CoinGecko unavailable',e)}}
async function initUniverse(){try{const all=await getJSON('https://api.binance.com/api/v3/ticker/24hr'),usdt=all.filter(t=>t.symbol.endsWith('USDT')).sort((a,b)=>+b.quoteVolume-+a.quoteVolume);for(const t of usdt){const s=t.symbol.slice(0,-4);if(EXCLUDE.has(s)||coins[s])continue;coins[s]={symbol:s,name:s,price:+t.lastPrice,chg_24h:+t.priceChangePercent,high_24h:+t.highPrice,low_24h:+t.lowPrice,volume_24h:+t.quoteVolume,tech:null,relative:null,deriv:null,intelScore:0};order.push(s);if(order.length>=MAX_COINS)break}render();renderMovers();connectStream();fundamentals();scanAll();setFeed('live')}catch(e){setFeed('bad');$('#marketBody').innerHTML='<tr><td colspan="11" class="empty">Could not reach Binance market data.</td></tr>'}}
function connectStream(){if(ws)try{ws.close()}catch{};const streams=order.map(s=>`${s.toLowerCase()}usdt@ticker`).join('/');ws=new WebSocket('wss://stream.binance.com:9443/stream?streams='+streams);ws.onopen=()=>setFeed('live');ws.onmessage=e=>{try{const d=JSON.parse(e.data).data,s=d.s.slice(0,-4),c=coins[s];if(!c)return;c.price=+d.c;c.chg_24h=+d.P;c.high_24h=+d.h;c.low_24h=+d.l;c.volume_24h=+d.q;updateOpportunities()}catch{}};ws.onclose=()=>{setFeed('warn');setTimeout(connectStream,4000)};ws.onerror=()=>{try{ws.close()}catch{}}}
async function fetchDerivatives(s){try{const sym=encodeURIComponent(s+'USDT');const [p,oi]=await Promise.all([getJSON(`https://fapi.binance.com/fapi/v1/premiumIndex?symbol=${sym}`),getJSON(`https://fapi.binance.com/futures/data/openInterestHist?symbol=${sym}&period=4h&limit=7`)]);let oiChange24h=null;if(Array.isArray(oi)&&oi.length>1){const a=+oi.at(-1).sumOpenInterestValue,b=+oi[0].sumOpenInterestValue;if(b)oiChange24h=100*(a/b-1)}return{funding:+p.lastFundingRate,mark:+p.markPrice,oiChange24h}}catch{return null}}
async function scanOne(s){try{const sym=encodeURIComponent(s+'USDT');const [k4,kd]=await Promise.all([getJSON(`https://api.binance.com/api/v3/klines?symbol=${sym}&interval=4h&limit=240`),getJSON(`https://api.binance.com/api/v3/klines?symbol=${sym}&interval=1d&limit=120`)]);const c=coins[s];c.tech=technicals(k4);c.daily=kd;c.relative={d7:perfFromDaily(kd,7),d30:perfFromDaily(kd,30),d90:perfFromDaily(kd,90),returns:dailyReturns(kd)};c.deriv=await fetchDerivatives(s);return true}catch(e){coins[s].tech={error:true};return false}}
async function scanAll(){const queue=[...order],workers=Array.from({length:5},async()=>{while(queue.length){const s=queue.shift();await scanOne(s);computeRelative();coins[s].intelScore=intelligenceScore(coins[s]);evaluateCoinAlerts(coins[s]);render();renderIntelligence();renderDerivatives();renderRelative();updateRegime();updateBriefing();updatePortfolio();updateOpportunities()}});await Promise.all(workers);computeRelative();order.forEach(s=>{coins[s].intelScore=intelligenceScore(coins[s]);evaluateCoinAlerts(coins[s])});$('#marketsMeta').textContent=`${order.length} liquid markets · live prices · technical, relative-strength and derivatives scan complete`;render();renderIntelligence();renderDerivatives();renderRelative();updateRegime();updateBriefing();updatePortfolio();updateOpportunities()}
function computeRelative(){const btc=coins.BTC?.relative;if(!btc)return;order.forEach(s=>{const r=coins[s].relative;if(!r)return;r.vsBtc7=r.d7==null||btc.d7==null?null:r.d7-btc.d7;r.vsBtc30=r.d30==null||btc.d30==null?null:r.d30-btc.d30;r.vsBtc90=r.d90==null||btc.d90==null?null:r.d90-btc.d90});const ranked=order.map(s=>coins[s]).filter(c=>c.relative?.vsBtc30!=null).sort((a,b)=>b.relative.vsBtc30-a.relative.vsBtc30);ranked.forEach((c,i)=>c.relative.rank=i+1)}
function filtered(){let arr=order.map(s=>coins[s]).filter(Boolean);if(search){const q=search.toLowerCase();arr=arr.filter(c=>(c.name||'').toLowerCase().includes(q)||c.symbol.toLowerCase().includes(q))}if(filter==='bull')arr=arr.filter(c=>c.tech?.bull);if(filter==='strong')arr=arr.filter(c=>c.tech?.adx>=30);if(filter==='setup')arr=arr.filter(c=>c.tech?.setup);if(filter==='crowded')arr=arr.filter(c=>derivativeRead(c).includes('Crowded'));if(filter==='watch')arr=arr.filter(c=>watch.has(c.symbol));arr.sort((a,b)=>{const value=c=>sort==='intel'?(c.intelScore??-1):sort==='score'?(c.tech?.score??-1):sort==='relative'?(c.relative?.vsBtc30??-999):sort==='adx'?(c.tech?.adx??-1):sort==='rsi'?(c.tech?.rsi??-1):(c[sort]??-Infinity);return value(b)-value(a)});return arr}
function render(){const body=$('#marketBody');if(!body)return;const arr=filtered();body.innerHTML=arr.length?arr.map(c=>{const t=c.tech,trend=!t?'Scanning…':t.bull?'BULL':t.bear?'BEAR':'MIXED',fund=c.deriv?.funding;return `<tr class="market-row" data-sym="${c.symbol}"><td class="left"><button class="watch ${watch.has(c.symbol)?'on':''}" data-watch="${c.symbol}" title="Watchlist">★</button></td><td class="left"><div class="coin-cell">${c.image?`<img class="coin-icon" src="${esc(c.image)}" alt="">`:''}<span class="coin-name">${esc(c.name)}</span><span class="coin-symbol">${c.symbol}</span></div></td><td>${money(c.price)}</td><td class="${cls(c.chg_24h)}">${pct(c.chg_24h)}</td><td>$${compact(c.volume_24h)}</td><td class="${trend==='BULL'?'up':trend==='BEAR'?'down':'neutral'}">${trend}</td><td>${t?.rsi==null?'—':n(t.rsi,1)}</td><td>${t?.adx==null?'—':n(t.adx,1)}</td><td class="${cls(c.relative?.vsBtc30)}">${c.relative?.vsBtc30==null?'—':pct(c.relative.vsBtc30)}</td><td class="${fund!=null&&Math.abs(fund)>.0005?'accent':''}">${fund==null?'—':n(fund*100,4)+'%'}</td><td><span class="score ${c.intelScore>=75?'up':''}">${c.intelScore||'—'}</span></td></tr>`}).join(''):'<tr><td colspan="11" class="empty">No markets match these filters.</td></tr>';renderWatchlist()}
function renderMovers(){const el=$('#movers');if(!el)return;const arr=order.slice(0,10).map(s=>coins[s]);el.innerHTML=arr.map(c=>`<div class="mover" data-open="${c.symbol}"><div class="mover-sym">${c.symbol}</div><div class="mover-price">${money(c.price)}</div><div class="mover-change ${cls(c.chg_24h)}">${pct(c.chg_24h)}</div></div>`).join('')}
function renderWatchlist(){const card=$('#watchlistCard'),el=$('#watchlist'),arr=[...watch].map(s=>coins[s]).filter(Boolean);if(!arr.length){card.hidden=true;return}card.hidden=false;el.innerHTML=arr.map(c=>`<div class="mover" data-open="${c.symbol}"><div class="mover-sym">★ ${c.symbol}</div><div class="mover-price">${money(c.price)}</div><div class="mover-change ${cls(c.chg_24h)}">${pct(c.chg_24h)} · intel ${c.intelScore||'—'}</div></div>`).join('')}
function renderIntelligence(){const el=$('#intelligenceList');if(!el)return;const arr=order.map(s=>coins[s]).filter(c=>c.tech&&!c.tech.error).sort((a,b)=>b.intelScore-a.intelScore).slice(0,6);if(!arr.length)return;el.innerHTML=arr.map((c,i)=>`<div class="intel-row" data-open="${c.symbol}"><div class="intel-rank">#${i+1}</div><div class="intel-main"><div class="intel-title">${c.symbol} <span class="badge ${c.tech.setup?'good':''}">${c.intelScore}/100</span></div><div class="intel-copy">${esc(intelExplanation(c))}</div></div></div>`).join('')}
function renderRelative(){const body=$('#relativeBody');if(!body)return;const arr=order.map(s=>coins[s]).filter(c=>c.relative?.rank).sort((a,b)=>a.relative.rank-b.relative.rank).slice(0,12);if(!arr.length)return;body.innerHTML=arr.map(c=>`<tr data-open="${c.symbol}"><td class="left">${c.symbol}</td><td class="${cls(c.relative.d7)}">${pct(c.relative.d7)}</td><td class="${cls(c.relative.d30)}">${pct(c.relative.d30)}</td><td class="${cls(c.relative.d90)}">${pct(c.relative.d90)}</td><td class="${cls(c.relative.vsBtc30)}">${pct(c.relative.vsBtc30)}</td><td>#${c.relative.rank}</td></tr>`).join('')}
function renderDerivatives(){const body=$('#derivativesBody');if(!body)return;const arr=order.map(s=>coins[s]).filter(c=>c.deriv).sort((a,b)=>Math.abs(b.deriv.oiChange24h||0)-Math.abs(a.deriv.oiChange24h||0)).slice(0,12);if(!arr.length)return;body.innerHTML=arr.map(c=>`<tr data-open="${c.symbol}"><td class="left">${c.symbol}</td><td class="${Math.abs(c.deriv.funding)>.0005?'accent':''}">${n(c.deriv.funding*100,4)}%</td><td class="${cls(c.deriv.oiChange24h)}">${pct(c.deriv.oiChange24h)}</td><td class="${cls(c.chg_24h)}">${pct(c.chg_24h)}</td><td class="left">${derivativeRead(c)}</td></tr>`).join('')}
function updateRegime(){const scanned=order.map(s=>coins[s]).filter(c=>c.tech&&!c.tech.error);if(scanned.length<3)return;const bull=scanned.filter(c=>c.tech.bull).length,bear=scanned.filter(c=>c.tech.bear).length,strong=scanned.filter(c=>c.tech.adx>=30).length,avg=scanned.reduce((a,c)=>a+(c.tech.adx||0),0)/scanned.length,highVol=scanned.filter(c=>c.tech.atrPct>=5).length;let label='RANGE / LOW CONVICTION',klass='neutral';if(bull/scanned.length>.58&&strong/scanned.length>.35){label='RISK-ON / TRENDING';klass='up'}else if(bear/scanned.length>.55){label='RISK-OFF / DEFENSIVE';klass='down'}else if(highVol/scanned.length>.4){label='VOLATILE / MIXED';klass='accent'}const el=$('#regimeCard');el.querySelector('.regime-value').textContent=label;el.querySelector('.regime-value').className=`regime-value ${klass}`;el.querySelector('.regime-row').textContent=`${bull}/${scanned.length} bullish · ${strong} strong trends · avg ADX ${n(avg,1)} · ${highVol} high-volatility`;if(currentRegime&&currentRegime!==label)pushAlert('REGIME',`Market regime changed ${currentRegime} → ${label}.`);currentRegime=label;priorState.regime=label;save()}
function updateBriefing(){const el=$('#briefingBody');if(!el)return;const scanned=order.map(s=>coins[s]).filter(c=>c.tech&&!c.tech.error);if(scanned.length<8)return;const ranked=[...scanned].sort((a,b)=>b.intelScore-a.intelScore),bull=scanned.filter(c=>c.tech.bull).length,setups=scanned.filter(c=>c.tech.setup).length,strong=scanned.filter(c=>c.tech.adx>=30).length,top=ranked.slice(0,3).map(c=>c.symbol).join(', '),weak=[...scanned].sort((a,b)=>a.intelScore-b.intelScore).slice(0,3).map(c=>c.symbol).join(', '),crowded=scanned.filter(c=>derivativeRead(c).includes('Crowded')).slice(0,3).map(c=>c.symbol).join(', ');$('#briefingBadge').textContent=currentRegime||'MARKET SCAN';$('#briefingBadge').className=`badge ${currentRegime?.includes('RISK-ON')?'good':currentRegime?.includes('RISK-OFF')?'bad':'warn'}`;$('#briefingMeta').textContent=`${scanned.length}/${order.length} markets analysed · refreshed ${new Date().toLocaleTimeString()}`;el.innerHTML=`<div class="brief-grid"><div class="brief-stat"><span>Breadth</span><strong>${bull}/${scanned.length} bullish</strong></div><div class="brief-stat"><span>Strong trends</span><strong>${strong}</strong></div><div class="brief-stat"><span>V3-like setups</span><strong>${setups}</strong></div><div class="brief-stat"><span>Top attention</span><strong>${top||'—'}</strong></div></div><div class="brief-sentence"><strong>What matters:</strong> ${top||'No clear leaders'} currently rank highest on combined trend, momentum, volume and relative-strength evidence. ${crowded?`Crowding risk is elevated in ${crowded}. `:''}Lowest-priority names right now: ${weak}. ${botBrain?`ETH bot decision is ${(botBrain.action||'unknown').replaceAll('_',' ').toLowerCase()}.`:''}</div>`}
function renderAlerts(){const el=$('#alertLog');if(!el)return;const btn=$('#enableAlerts');if(btn)btn.textContent=Notification.permission==='granted'?'Browser alerts enabled':'Enable browser alerts';if(!alerts.length){el.innerHTML='<div class="empty">No alerts recorded in this browser yet.</div>';return}el.innerHTML=alerts.slice(0,8).map(a=>`<div class="alert-row" ${a.symbol?`data-open="${a.symbol}"`:''}><span class="badge">${esc(a.type)}</span><div><div>${esc(a.message)}</div><small>${new Date(a.time).toLocaleString()}</small></div></div>`).join('')}
function updatePortfolio(){const el=$('#portfolioIntel');if(!el)return;const arr=[...watch].map(s=>coins[s]).filter(c=>c.relative?.returns?.length);if(arr.length<2){el.innerHTML='<div class="empty">Star at least two scanned coins to build correlation intelligence.</div>';return}const btc=coins.BTC?.relative?.returns||[],rows=arr.map(c=>({symbol:c.symbol,btc:corr(c.relative.returns,btc),intel:c.intelScore})).sort((a,b)=>(b.btc||0)-(a.btc||0));let pair=null;for(let i=0;i<arr.length;i++)for(let j=i+1;j<arr.length;j++){const r=corr(arr[i].relative.returns,arr[j].relative.returns);if(r!=null&&(!pair||r>pair.r))pair={a:arr[i].symbol,b:arr[j].symbol,r}}const high=rows.filter(x=>x.btc!=null&&x.btc>.75).length;el.innerHTML=`<div class="portfolio-summary">${high>=2?`<span class="badge warn">CONCENTRATED</span> ${high} watchlist coins have >0.75 daily-return correlation with BTC.`:`<span class="badge good">DIVERSIFIED</span> Watchlist BTC overlap is moderate.`}${pair?` Highest pair overlap: <strong>${pair.a}/${pair.b} ${n(pair.r,2)}</strong>.`:''}</div><div class="table-wrap"><table class="market-table"><thead><tr><th class="left">Coin</th><th>Corr BTC</th><th>Intel</th><th>Role</th></tr></thead><tbody>${rows.map(r=>`<tr data-open="${r.symbol}"><td class="left">${r.symbol}</td><td>${r.btc==null?'—':n(r.btc,2)}</td><td>${r.intel}</td><td class="left">${r.btc>.8?'BTC-like exposure':r.btc<.4?'Diversifier':'Moderate overlap'}</td></tr>`).join('')}</tbody></table></div>`}
$$('.chip').forEach(b=>b.addEventListener('click',()=>{filter=filter===b.dataset.filter?null:b.dataset.filter;$$('.chip').forEach(x=>x.classList.toggle('active',x.dataset.filter===filter));render()}));$('#search')?.addEventListener('input',e=>{search=e.target.value.trim();render()});$('#sort')?.addEventListener('change',e=>{sort=e.target.value;render()});$('#enableAlerts')?.addEventListener('click',async()=>{if(!('Notification'in window)){pushAlert('SYSTEM','This browser does not support desktop notifications.');return}const p=await Notification.requestPermission();renderAlerts();if(p==='granted')pushAlert('SYSTEM','Wavelength browser alerts enabled.')});document.addEventListener('click',e=>{const w=e.target.closest('[data-watch]');if(w){e.stopPropagation();const s=w.dataset.watch;watch.has(s)?watch.delete(s):watch.add(s);save();render();updatePortfolio();return}const o=e.target.closest('[data-open],tr[data-sym]');const s=o?.dataset.open||o?.dataset.sym;if(s)location.href=`coin.html?symbol=${encodeURIComponent(s)}`});
renderAlerts();loadValidation();loadBot().then(()=>updateBriefing());initUniverse();setInterval(()=>{loadValidation();loadBot()},60000);setInterval(updateOpportunities,60000);
})();