(()=>{
'use strict';
const MAX_COINS=40, EXCLUDE=new Set(['USDC','BUSD','TUSD','FDUSD','USDP','DAI','EUR','GBP','EURI','USTC','PAX','UST','WBTC','WBETH']);
const coins={}, order=[]; let ws=null, filter=null, search='', sort='score', cgBySymbol={};
const watch=new Set(JSON.parse(localStorage.getItem('wavelength_watchlist')||'[]'));
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const n=(v,d=2)=>v==null||!Number.isFinite(+v)?'—':(+v).toLocaleString('en-US',{maximumFractionDigits:d,minimumFractionDigits:d});
const money=v=>v==null||!Number.isFinite(+v)?'—':(+v>=1?'$'+(+v).toLocaleString('en-US',{maximumFractionDigits:2,minimumFractionDigits:2}):'$'+(+v).toLocaleString('en-US',{maximumFractionDigits:8}));
const compact=v=>v==null||!Number.isFinite(+v)?'—':new Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:2}).format(+v);
const pct=v=>v==null||!Number.isFinite(+v)?'—':`${+v>=0?'+':''}${n(+v,2)}%`;
const cls=v=>+v>0?'up':+v<0?'down':'neutral';
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function setFeed(state){const el=$('#feedStatus'); if(!el)return; el.className='status-pill '+(state==='live'?'':state==='bad'?'bad':'warn'); el.innerHTML=`<span class="dot"></span>${state==='live'?'LIVE':state==='bad'?'OFFLINE':'CONNECTING'}`}
function ema(vals,p){if(vals.length<p)return null; const k=2/(p+1); let e=vals.slice(0,p).reduce((a,b)=>a+b,0)/p; for(let i=p;i<vals.length;i++)e=vals[i]*k+e*(1-k); return e}
function rsi(vals,p=14){if(vals.length<=p)return null; let gain=0,loss=0; for(let i=1;i<=p;i++){const d=vals[i]-vals[i-1];gain+=Math.max(d,0);loss+=Math.max(-d,0)} gain/=p;loss/=p; for(let i=p+1;i<vals.length;i++){const d=vals[i]-vals[i-1];gain=(gain*(p-1)+Math.max(d,0))/p;loss=(loss*(p-1)+Math.max(-d,0))/p} if(loss===0)return 100; const rs=gain/loss; return 100-100/(1+rs)}
function atrAndAdx(ks,p=14){if(ks.length<p*2+2)return {atr:null,adx:null}; const tr=[],plus=[],minus=[]; for(let i=1;i<ks.length;i++){const h=+ks[i][2],l=+ks[i][3],pc=+ks[i-1][4],ph=+ks[i-1][2],pl=+ks[i-1][3];tr.push(Math.max(h-l,Math.abs(h-pc),Math.abs(l-pc))); const up=h-ph,down=pl-l;plus.push(up>down&&up>0?up:0);minus.push(down>up&&down>0?down:0)} let atr=tr.slice(0,p).reduce((a,b)=>a+b,0)/p,ps=plus.slice(0,p).reduce((a,b)=>a+b,0)/p,ms=minus.slice(0,p).reduce((a,b)=>a+b,0)/p; const dx=[]; for(let i=p;i<tr.length;i++){atr=(atr*(p-1)+tr[i])/p;ps=(ps*(p-1)+plus[i])/p;ms=(ms*(p-1)+minus[i])/p; const pdi=atr?100*ps/atr:0,mdi=atr?100*ms/atr:0;dx.push((pdi+mdi)?100*Math.abs(pdi-mdi)/(pdi+mdi):0)} if(dx.length<p)return {atr,adx:null}; let adx=dx.slice(0,p).reduce((a,b)=>a+b,0)/p; for(let i=p;i<dx.length;i++)adx=(adx*(p-1)+dx[i])/p; return {atr,adx}}
function technicals(ks){const closes=ks.map(k=>+k[4]), vols=ks.map(k=>+k[5]), close=closes.at(-1),e20=ema(closes,20),e80=ema(closes,80),e200=ema(closes,200),R=rsi(closes),aa=atrAndAdx(ks),atrPct=aa.atr&&close?aa.atr/close*100:null; const recent=vols.slice(-4).reduce((a,b)=>a+b,0)/4,prior=vols.slice(-24,-4),avg=prior.length?prior.reduce((a,b)=>a+b,0)/prior.length:null,volRatio=avg?recent/avg:null; const bull=e20>e80&&close>e200,bear=e20<e80&&close<e200,setup=bull&&R>=50&&R<=75&&aa.adx>=35; let score=0; if(e20>e80)score+=20;if(close>e200)score+=20;if(R>=50&&R<=75)score+=20;if(aa.adx>=35)score+=20;if(volRatio>=1)score+=10;return {close,ema20:e20,ema80:e80,ema200:e200,rsi:R,adx:aa.adx,atrPct,volRatio,bull,bear,setup,score}}
async function getJSON(url){const r=await fetch(url);if(!r.ok)throw new Error(`${r.status} ${url}`);return r.json()}
async function loadValidation(){try{const d=await getJSON(`validation.json?t=${Date.now()}`),g=$('#validationGrid'); $('#validationMeta').textContent=`Fresh evidence only · updated ${d.generated_at?new Date(d.generated_at).toLocaleString():'—'} · orders disabled`;g.innerHTML=Object.values(d.strategies||{}).map(s=>validationCard(s)).join('')}catch(e){$('#validationGrid').innerHTML='<div class="empty">Validation feed unavailable.</div>'}}
function validationCard(s){const min=s.minimums||{}, tradeP=min.completed_trades?Math.min(100,(s.completed_trades||0)/min.completed_trades*100):0,dayP=min.calendar_days?Math.min(100,(s.observation_days||0)/min.calendar_days*100):0,progress=Math.min(tradeP,dayP); const stat=s.status||'UNKNOWN',bc=stat.includes('FAIL')?'bad':stat.includes('ELIGIBLE')?'good':'warn'; return `<article class="validation-card metric"><div class="validation-top"><div><div class="strategy-name">${esc(s.name)}</div><div class="card-meta">Shadow ${esc(s.position)} · ${n(s.observation_days||0,1)} / ${min.calendar_days||'—'} days</div></div><span class="badge ${bc}">${esc(stat.replaceAll('_',' '))}</span></div><div class="grid4"><div><div class="metric-label">Fresh trades</div><div class="metric-value">${s.completed_trades||0}/${min.completed_trades||'—'}</div></div><div><div class="metric-label">Return</div><div class="metric-value ${cls(s.return_pct)}">${pct(s.return_pct)}</div></div><div><div class="metric-label">Drawdown</div><div class="metric-value ${cls(s.max_drawdown_pct)}">${pct(s.max_drawdown_pct)}</div></div><div><div class="metric-label">Profit factor</div><div class="metric-value">${s.profit_factor==null?'—':n(s.profit_factor,2)}</div></div></div><div class="progress"><span style="width:${progress}%"></span></div><div class="gate-list">Waiting on: ${(s.unmet_gates||[]).map(esc).join(' · ')||'No unmet gates'}</div></article>`}
async function loadBot(){try{const b=await getJSON(`bot-brain.json?t=${Date.now()}`);const action=(b.action||'UNKNOWN').replaceAll('_',' ');$('#botBadge').textContent=action;$('#botBadge').className='badge '+(b.action==='WOULD_ENTER'||b.action==='HOLD'?'good':'');$('#botMeta').textContent=`${b.symbol||'ETH/USD'} · ${b.timeframe||'4Hour'} · ${b.validation_status||'forward test'} · orders disabled`;$('#botGrid').innerHTML=[['Decision',action,''],['Trend',b.trend_ok?'BULLISH':'NOT QUALIFIED',b.trend_ok?'up':'neutral'],['ADX',b.adx==null?'—':n(b.adx,1),b.trend_strength_ok?'up':'neutral'],['RSI',b.rsi==null?'—':n(b.rsi,1),b.momentum_ok?'up':'neutral'],['ATR',b.atr_pct==null?'—':n(b.atr_pct,2)+'%',''],['Candle close',money(b.close),''],['EMA 20 / 80',b.fast_above_slow?'BULLISH':'BEARISH',b.fast_above_slow?'up':'down'],['Shadow position',b.has_position?'LONG':'FLAT',b.has_position?'up':'neutral']].map(x=>`<div class="metric"><div class="metric-label">${x[0]}</div><div class="metric-value ${x[2]}">${x[1]}</div></div>`).join('')}catch(e){$('#botGrid').innerHTML='<div class="empty">Bot brain unavailable.</div>'}}
async function fundamentals(){try{const list=await getJSON('https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=200&page=1&sparkline=false&price_change_percentage=7d,30d');list.forEach(c=>{const s=(c.symbol||'').toUpperCase();if(!cgBySymbol[s]||c.market_cap_rank<(cgBySymbol[s].market_cap_rank||99999))cgBySymbol[s]=c;if(coins[s])Object.assign(coins[s],{name:c.name,image:c.image,rank:c.market_cap_rank,market_cap:c.market_cap,circulating_supply:c.circulating_supply,ath_change_pct:c.ath_change_percentage,fdv:c.fully_diluted_valuation})});render()}catch(e){console.warn('CoinGecko unavailable',e)}}
async function initUniverse(){try{const all=await getJSON('https://api.binance.com/api/v3/ticker/24hr'), usdt=all.filter(t=>t.symbol.endsWith('USDT')).sort((a,b)=>+b.quoteVolume-+a.quoteVolume);for(const t of usdt){const s=t.symbol.slice(0,-4);if(EXCLUDE.has(s)||coins[s])continue;coins[s]={symbol:s,name:s,price:+t.lastPrice,chg_24h:+t.priceChangePercent,high_24h:+t.highPrice,low_24h:+t.lowPrice,volume_24h:+t.quoteVolume,tech:null};order.push(s);if(order.length>=MAX_COINS)break}render();renderMovers();connectStream();fundamentals();scanTechnicals();setFeed('live')}catch(e){setFeed('bad');$('#marketBody').innerHTML='<tr><td colspan="11" class="empty">Could not reach Binance market data.</td></tr>'}}
function connectStream(){if(ws)try{ws.close()}catch{};const streams=order.map(s=>`${s.toLowerCase()}usdt@ticker`).join('/');ws=new WebSocket('wss://stream.binance.com:9443/stream?streams='+streams);ws.onopen=()=>setFeed('live');ws.onmessage=e=>{try{const d=JSON.parse(e.data).data,s=d.s.slice(0,-4),c=coins[s];if(!c)return;c.price=+d.c;c.chg_24h=+d.P;c.high_24h=+d.h;c.low_24h=+d.l;c.volume_24h=+d.q}catch{}};ws.onclose=()=>{setFeed('warn');setTimeout(connectStream,4000)};ws.onerror=()=>{try{ws.close()}catch{}}}
async function scanOne(s){try{const ks=await getJSON(`https://api.binance.com/api/v3/klines?symbol=${encodeURIComponent(s+'USDT')}&interval=4h&limit=240`);coins[s].tech=technicals(ks)}catch(e){coins[s].tech={error:true}}}
async function scanTechnicals(){const queue=[...order],workers=Array.from({length:6},async()=>{while(queue.length){const s=queue.shift();await scanOne(s);render();updateRegime()}});await Promise.all(workers);$('#marketsMeta').textContent=`${order.length} liquid markets · live prices · 4h technical scan complete`;updateRegime();render()}
function filtered(){let arr=order.map(s=>coins[s]).filter(Boolean);if(search){const q=search.toLowerCase();arr=arr.filter(c=>(c.name||'').toLowerCase().includes(q)||c.symbol.toLowerCase().includes(q))}if(filter==='bull')arr=arr.filter(c=>c.tech?.bull);if(filter==='strong')arr=arr.filter(c=>c.tech?.adx>=30);if(filter==='setup')arr=arr.filter(c=>c.tech?.setup);if(filter==='watch')arr=arr.filter(c=>watch.has(c.symbol));arr.sort((a,b)=>{const av=sort==='score'?(a.tech?.score??-1):sort==='adx'?(a.tech?.adx??-1):sort==='rsi'?(a.tech?.rsi??-1):(a[sort]??-Infinity),bv=sort==='score'?(b.tech?.score??-1):sort==='adx'?(b.tech?.adx??-1):sort==='rsi'?(b.tech?.rsi??-1):(b[sort]??-Infinity);return bv-av});return arr}
function render(){const body=$('#marketBody');if(!body)return;const arr=filtered();body.innerHTML=arr.length?arr.map(c=>{const t=c.tech,trend=!t?'Scanning…':t.bull?'BULL':t.bear?'BEAR':'MIXED';return `<tr class="market-row" data-sym="${c.symbol}"><td class="left"><button class="watch ${watch.has(c.symbol)?'on':''}" data-watch="${c.symbol}" title="Watchlist">★</button></td><td class="left"><div class="coin-cell">${c.image?`<img class="coin-icon" src="${esc(c.image)}" alt="">`:''}<span class="coin-name">${esc(c.name)}</span><span class="coin-symbol">${c.symbol}</span></div></td><td>${money(c.price)}</td><td class="${cls(c.chg_24h)}">${pct(c.chg_24h)}</td><td>$${compact(c.volume_24h)}</td><td>${c.market_cap?'$'+compact(c.market_cap):'—'}</td><td class="${trend==='BULL'?'up':trend==='BEAR'?'down':'neutral'}">${trend}</td><td>${t?.rsi==null?'—':n(t.rsi,1)}</td><td>${t?.adx==null?'—':n(t.adx,1)}</td><td>${t?.atrPct==null?'—':n(t.atrPct,2)+'%'}</td><td><span class="score ${t?.setup?'up':''}">${t?.score??'—'}</span></td></tr>`}).join(''):'<tr><td colspan="11" class="empty">No markets match these filters.</td></tr>';renderWatchlist()}
function renderMovers(){const el=$('#movers');if(!el)return;const arr=order.slice(0,10).map(s=>coins[s]);el.innerHTML=arr.map(c=>`<div class="mover" data-open="${c.symbol}"><div class="mover-sym">${c.symbol}</div><div class="mover-price">${money(c.price)}</div><div class="mover-change ${cls(c.chg_24h)}">${pct(c.chg_24h)}</div></div>`).join('')}
function renderWatchlist(){const card=$('#watchlistCard'),el=$('#watchlist');const arr=[...watch].map(s=>coins[s]).filter(Boolean);if(!arr.length){card.hidden=true;return}card.hidden=false;el.innerHTML=arr.map(c=>`<div class="mover" data-open="${c.symbol}"><div class="mover-sym">★ ${c.symbol}</div><div class="mover-price">${money(c.price)}</div><div class="mover-change ${cls(c.chg_24h)}">${pct(c.chg_24h)} · score ${c.tech?.score??'—'}</div></div>`).join('')}
function updateRegime(){const scanned=order.map(s=>coins[s]).filter(c=>c.tech&&!c.tech.error);if(scanned.length<3)return;const bull=scanned.filter(c=>c.tech.bull).length,bear=scanned.filter(c=>c.tech.bear).length,strong=scanned.filter(c=>c.tech.adx>=30).length,avg=scanned.reduce((a,c)=>a+(c.tech.adx||0),0)/scanned.length,breadth=bull/scanned.length*100;let label='MIXED / TRANSITIONAL',klass='accent';if(breadth>=65&&avg>=25){label='RISK-ON / TRENDING';klass='up'}else if(bear/scanned.length>=.55){label='RISK-OFF / DEFENSIVE';klass='down'}else if(avg<20){label='RANGE / LOW CONVICTION';klass='neutral'}const card=$('#regimeCard');card.innerHTML=`<div class="regime-label">MARKET REGIME · 4H</div><div class="regime-value ${klass}">${label}</div><div class="regime-row">${bull}/${scanned.length} bullish · ${bear}/${scanned.length} bearish · ${strong} strong-trend · avg ADX ${n(avg,1)}</div>`}
function saveWatch(){localStorage.setItem('wavelength_watchlist',JSON.stringify([...watch]));render()}
document.addEventListener('click',e=>{const w=e.target.closest('[data-watch]');if(w){e.stopPropagation();const s=w.dataset.watch;watch.has(s)?watch.delete(s):watch.add(s);saveWatch();return}const o=e.target.closest('[data-open],tr[data-sym]');if(o){const s=o.dataset.open||o.dataset.sym;location.href=`coin.html?symbol=${encodeURIComponent(s)}`}});
$('#search')?.addEventListener('input',e=>{search=e.target.value.trim();render()});$('#sort')?.addEventListener('change',e=>{sort=e.target.value;render()});$$('[data-filter]').forEach(b=>b.addEventListener('click',()=>{const f=b.dataset.filter;filter=filter===f?null:f;$$('[data-filter]').forEach(x=>x.classList.toggle('active',x.dataset.filter===filter));render()}));
setInterval(()=>{renderMovers();render()},2500);loadValidation();loadBot();initUniverse();setInterval(loadValidation,60000);setInterval(loadBot,60000);setInterval(fundamentals,120000);
})();
