(()=>{
'use strict';
const $=s=>document.querySelector(s);const qp=new URLSearchParams(location.search);const base=(qp.get('symbol')||'BTC').toUpperCase().replace(/[^A-Z0-9]/g,'');const pair=`${base}USDT`;
const n=(v,d=2)=>v==null||!Number.isFinite(+v)?'—':(+v).toLocaleString('en-GB',{maximumFractionDigits:d,minimumFractionDigits:d});
const compact=v=>v==null||!Number.isFinite(+v)?'—':new Intl.NumberFormat('en-GB',{notation:'compact',maximumFractionDigits:2}).format(+v);
const money=v=>v==null||!Number.isFinite(+v)?'—':(+v>=1?'$'+(+v).toLocaleString('en-GB',{maximumFractionDigits:2,minimumFractionDigits:2}):'$'+(+v).toLocaleString('en-GB',{maximumFractionDigits:8}));
const pct=v=>v==null||!Number.isFinite(+v)?'—':`${+v>=0?'+':''}${n(v,2)}%`;
const get=async u=>{const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw new Error(`${r.status} ${u}`);return r.json()};
let candles=[],hover=-1,currentRange='4h';
function ema(vals,p){if(vals.length<p)return null;const k=2/(p+1);let e=vals.slice(0,p).reduce((a,b)=>a+b,0)/p;for(let i=p;i<vals.length;i++)e=vals[i]*k+e*(1-k);return e}
function rsi(vals,p=14){if(vals.length<=p)return null;let g=0,l=0;for(let i=1;i<=p;i++){const d=vals[i]-vals[i-1];g+=Math.max(d,0);l+=Math.max(-d,0)}g/=p;l/=p;for(let i=p+1;i<vals.length;i++){const d=vals[i]-vals[i-1];g=(g*(p-1)+Math.max(d,0))/p;l=(l*(p-1)+Math.max(-d,0))/p}return l===0?100:100-100/(1+g/l)}
function atrAdx(ks,p=14){if(ks.length<p*2+2)return{atr:null,adx:null};const tr=[],plus=[],minus=[];for(let i=1;i<ks.length;i++){const h=+ks[i][2],lo=+ks[i][3],pc=+ks[i-1][4],ph=+ks[i-1][2],pl=+ks[i-1][3];tr.push(Math.max(h-lo,Math.abs(h-pc),Math.abs(lo-pc)));const up=h-ph,down=pl-lo;plus.push(up>down&&up>0?up:0);minus.push(down>up&&down>0?down:0)}let atr=tr.slice(0,p).reduce((a,b)=>a+b,0)/p,ps=plus.slice(0,p).reduce((a,b)=>a+b,0)/p,ms=minus.slice(0,p).reduce((a,b)=>a+b,0)/p;const dx=[];for(let i=p;i<tr.length;i++){atr=(atr*(p-1)+tr[i])/p;ps=(ps*(p-1)+plus[i])/p;ms=(ms*(p-1)+minus[i])/p;const pdi=atr?100*ps/atr:0,mdi=atr?100*ms/atr:0;dx.push((pdi+mdi)?100*Math.abs(pdi-mdi)/(pdi+mdi):0)}if(dx.length<p)return{atr,adx:null};let adx=dx.slice(0,p).reduce((a,b)=>a+b,0)/p;for(let i=p;i<dx.length;i++)adx=(adx*(p-1)+dx[i])/p;return{atr,adx}}
function computeTech(ks){const closes=ks.map(k=>+k[4]),vols=ks.map(k=>+k[5]),close=closes.at(-1),e20=ema(closes,20),e80=ema(closes,80),e200=ema(closes,200),R=rsi(closes),aa=atrAdx(ks),atrPct=aa.atr&&close?100*aa.atr/close:null;const vr=vols.length>=24?(vols.slice(-4).reduce((a,b)=>a+b,0)/4)/(vols.slice(-24,-4).reduce((a,b)=>a+b,0)/20):null;const bull=e20>e80&&close>e200,bear=e20<e80&&close<e200;let score=0;if(e20>e80)score+=20;if(close>e200)score+=20;if(R>=50&&R<=75)score+=20;if(aa.adx>=30)score+=20;if(vr>=1)score+=10;if(atrPct!=null&&atrPct<8)score+=10;return{close,e20,e80,e200,rsi:R,adx:aa.adx,atrPct,volRatio:vr,bull,bear,score}}
function setFeed(ok){const e=$('#assetFeed');e.className='status-pill '+(ok?'':'bad');e.innerHTML=`<span class="dot"></span>${ok?'LIVE':'PARTIAL'}`}
async function loadMarket(){try{const t=await get(`https://api.binance.com/api/v3/ticker/24hr?symbol=${pair}`);$('#assetSymbol').textContent=base;$('#assetName').textContent=`${base} / USDT`;$('#assetPrice').textContent=money(t.lastPrice);$('#assetChange').textContent=`${pct(t.priceChangePercent)} · 24h`;$('#marketStats').innerHTML=[[`24h high`,money(t.highPrice)],[`24h low`,money(t.lowPrice)],[`24h volume`,compact(t.quoteVolume)],[`Trades`,compact(t.count)]].map(x=>`<div class="asset-stat"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');setFeed(true)}catch(e){setFeed(false);$('#assetName').textContent=`${base} / USDT`;$('#assetSymbol').textContent=base;}}
async function loadCandles(range=currentRange){currentRange=range;document.querySelectorAll('.range-btn').forEach(b=>b.classList.toggle('active',b.dataset.range===range));try{candles=await get(`https://api.binance.com/api/v3/klines?symbol=${pair}&interval=${range}&limit=300`);const tech=computeTech(candles);renderTech(tech);drawChart();$('#chartMeta').textContent=`${base}/USDT · ${range.toUpperCase()} · ${candles.length} candles`;await loadDerivatives(tech)}catch(e){$('#chartMeta').textContent='Chart unavailable for this market';}}
function renderTech(t){const trend=t.bull?'Bullish':t.bear?'Bearish':'Mixed';$('#technicalMetrics').innerHTML=[[`Trend`,trend],[`RSI`,n(t.rsi,1)],[`ADX`,n(t.adx,1)],[`ATR`,t.atrPct==null?'—':n(t.atrPct,2)+'%'],[`EMA 20`,money(t.e20)],[`EMA 80`,money(t.e80)],[`EMA 200`,money(t.e200)],[`Volume ratio`,t.volRatio==null?'—':n(t.volRatio,2)+'×']].map(x=>`<div class="metric-row"><small>${x[0]}</small><b>${x[1]}</b></div>`).join('');const state=t.score>=80?'NEAR SIGNAL':t.score>=60?'DEVELOPING':t.score>=40?'WATCH':'LOW PRIORITY';$('#signalScore').textContent=`${Math.round(t.score)}/100`;$('#signalState').textContent=state;$('#signalBadge').textContent=state;$('#signalBadge').className='badge '+(t.score>=70?'good':t.score<40?'':'warn');const why=[];why.push(`${trend.toLowerCase()} trend structure`);if(t.adx>=30)why.push(`strong trend strength (ADX ${n(t.adx,1)})`);else why.push(`trend strength still limited (ADX ${n(t.adx,1)})`);if(t.rsi>=50&&t.rsi<=75)why.push(`momentum in Wavelength's preferred trend zone`);if(t.volRatio>=1)why.push('volume is confirming rather than fading');if(t.atrPct>8)why.push('volatility is elevated');$('#signalExplain').textContent=why.join(' · ')+'.';$('#whyCare').innerHTML=`Wavelength currently reads <b>${base}</b> as <b>${state.toLowerCase()}</b>. The strongest supportive evidence is ${why.slice(0,3).join(', ')}.<br><br><b>Invalidation cues:</b> loss of trend structure, ADX deterioration, momentum leaving the preferred zone, abnormal volatility expansion, or derivatives positioning becoming excessively crowded. This page does not mean any validated strategy is approved on ${base}.`}
async function loadDerivatives(t){let funding=null,oi=null;try{const f=await get(`https://fapi.binance.com/fapi/v1/premiumIndex?symbol=${pair}`);funding=+f.lastFundingRate*100}catch{}try{const h=await get(`https://fapi.binance.com/futures/data/openInterestHist?symbol=${pair}&period=1h&limit=25`);if(h.length>1){const a=+h[0].sumOpenInterestValue,b=+h.at(-1).sumOpenInterestValue;oi=a?100*(b/a-1):null}}catch{}let read='Balanced';if(funding!=null&&funding>.05)read='Crowded longs';else if(funding!=null&&funding<-.05)read='Crowded shorts';else if(oi!=null&&oi>5)read='Open interest building';else if(oi!=null&&oi<-5)read='Deleveraging';$('#derivativeMetrics').innerHTML=[[`Funding`,funding==null?'—':pct(funding)],[`OI change ~24h`,oi==null?'—':pct(oi)],[`Crowding read`,read],[`Spot trend`,t.bull?'Bullish':t.bear?'Bearish':'Mixed']].map(x=>`<div class="metric-row"><small>${x[0]}</small><b>${x[1]}</b></div>`).join('')}
async function loadFundamentals(){try{const s=await get(`https://api.coingecko.com/api/v3/search?query=${encodeURIComponent(base)}`);const coin=(s.coins||[]).find(c=>String(c.symbol).toUpperCase()===base)||s.coins?.[0];if(!coin)throw new Error('not found');const d=await get(`https://api.coingecko.com/api/v3/coins/${coin.id}?localization=false&tickers=false&community_data=false&developer_data=false&sparkline=false`);$('#assetName').textContent=`${d.name} · ${base}/USDT`;const m=d.market_data||{};$('#fundamentalMetrics').innerHTML=[[`Market cap`,m.market_cap?.usd==null?'—':'$'+compact(m.market_cap.usd)],[`FDV`,m.fully_diluted_valuation?.usd==null?'—':'$'+compact(m.fully_diluted_valuation.usd)],[`Circulating supply`,compact(m.circulating_supply)],[`Max supply`,compact(m.max_supply)],[`Market-cap rank`,d.market_cap_rank==null?'—':'#'+d.market_cap_rank],[`ATH`,money(m.ath?.usd)]].map(x=>`<div class="metric-row"><small>${x[0]}</small><b>${x[1]}</b></div>`).join('');const desc=(d.description?.en||'').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();$('#fundamentalDescription').textContent=desc?desc.slice(0,420)+(desc.length>420?'…':''):'Public fundamentals description unavailable.'}catch(e){$('#fundamentalMetrics').innerHTML='<div class="empty">Fundamentals feed unavailable or rate-limited.</div>';$('#fundamentalDescription').textContent='Technical and derivatives intelligence remains available.'}}
function drawChart(){const canvas=$('#priceChart');if(!canvas||!candles.length)return;const rect=canvas.getBoundingClientRect(),dpr=window.devicePixelRatio||1;canvas.width=Math.max(1,Math.floor(rect.width*dpr));canvas.height=Math.max(1,Math.floor(rect.height*dpr));const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);const w=rect.width,h=rect.height,pad={l:12,r:62,t:16,b:26};const vals=candles.map(k=>+k[4]),lo=Math.min(...vals),hi=Math.max(...vals),span=hi-lo||1;const x=i=>pad.l+i*(w-pad.l-pad.r)/(vals.length-1),y=v=>pad.t+(hi-v)*(h-pad.t-pad.b)/span;ctx.clearRect(0,0,w,h);ctx.globalAlpha=.18;ctx.strokeStyle='#94a3b8';ctx.lineWidth=1;for(let i=0;i<5;i++){const yy=pad.t+i*(h-pad.t-pad.b)/4;ctx.beginPath();ctx.moveTo(pad.l,yy);ctx.lineTo(w-pad.r,yy);ctx.stroke();ctx.globalAlpha=.75;ctx.fillStyle='#94a3b8';ctx.font='10px IBM Plex Mono';ctx.fillText(money(hi-i*span/4),w-pad.r+7,yy+3);ctx.globalAlpha=.18}ctx.globalAlpha=1;ctx.strokeStyle='#9db5d8';ctx.lineWidth=2;ctx.beginPath();vals.forEach((v,i)=>i?ctx.lineTo(x(i),y(v)):ctx.moveTo(x(i),y(v)));ctx.stroke();if(hover>=0&&hover<vals.length){const xx=x(hover),yy=y(vals[hover]);ctx.strokeStyle='#64748b';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(xx,pad.t);ctx.lineTo(xx,h-pad.b);ctx.stroke();ctx.fillStyle='#e2e8f0';ctx.beginPath();ctx.arc(xx,yy,3,0,Math.PI*2);ctx.fill()}}
function initChartHover(){const c=$('#priceChart'),tip=$('#chartTip');c.addEventListener('mousemove',e=>{if(!candles.length)return;const r=c.getBoundingClientRect(),ratio=(e.clientX-r.left)/r.width;hover=Math.max(0,Math.min(candles.length-1,Math.round(ratio*(candles.length-1))));const k=candles[hover];tip.style.display='block';tip.style.left=Math.min(r.width-150,e.clientX-r.left+12)+'px';tip.style.top=Math.max(6,e.clientY-r.top-38)+'px';tip.textContent=`${new Date(+k[0]).toLocaleString()} · ${money(+k[4])}`;drawChart()});c.addEventListener('mouseleave',()=>{hover=-1;tip.style.display='none';drawChart()})}
document.addEventListener('DOMContentLoaded',()=>{document.title=`${base} — Wavelength Live`;document.querySelectorAll('.range-btn').forEach(b=>b.addEventListener('click',()=>loadCandles(b.dataset.range)));window.addEventListener('resize',drawChart);initChartHover();loadMarket();loadCandles('4h');loadFundamentals()});
})();