(()=>{'use strict';
const $=s=>document.querySelector(s);const esc=s=>String(s??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const age=ts=>{if(!ts)return '—';const m=(Date.now()-new Date(ts).getTime())/60000;if(!Number.isFinite(m))return '—';return m<90?`${Math.max(0,Math.round(m))}m ago`:`${(m/60).toFixed(1)}h ago`};
const cls=v=>/CLEAR|OK|100|CANARY|FORWARD_SHADOW/.test(String(v))?'up':/BLOCK|CRITICAL|ERROR|DEGRADED/.test(String(v))?'down':'neutral';
async function get(){const r=await fetch(`bot-operations-status.json?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}
function metric(label,value,explain){return `<div class="metric"${explain?` data-explain="${esc(label)}" data-explain-text="${esc(explain)}"`:''}><div class="metric-label">${esc(label)}</div><div class="metric-value ${cls(value)}">${esc(value)}</div></div>`}
function ensure(){if($('#botOpsMaturity'))return;const hero=document.querySelector('.hero');if(!hero)return;const wrap=document.createElement('div');wrap.innerHTML=`
<section class="card" id="botOpsMaturity"><div class="card-head"><div><div class="card-title">Bot operations observability</div><div class="card-meta" id="botOpsMeta">Loading sanitised operational maturity feed…</div></div><span class="badge warn" id="botOpsCircuit">LOADING</span></div><div class="grid4" id="botOpsGrid"><div class="empty">Loading…</div></div><div class="card-meta" style="margin-top:12px">Read-only status only. Broker credentials, account balances, order IDs, quantities, stops and submit/cancel controls are deliberately not published.</div></section>
<section class="grid2" id="botOpsDetail"><div class="card"><div class="card-head"><div><div class="card-title">First paper-trade launch gate</div><div class="card-meta">Manual review boundary · never automatic promotion</div></div></div><div id="botLaunchGate"><div class="empty">Loading…</div></div></div><div class="card"><div class="card-head"><div><div class="card-title">Strategy registry</div><div class="card-meta">Versioned research → shadow → future paper-review path</div></div></div><div id="botStrategyRegistry"><div class="empty">Loading…</div></div></div></section>
<section class="grid2"><div class="card"><div class="card-head"><div><div class="card-title">Manual paper review packet</div><div class="card-meta">Private packet status only</div></div><span class="badge">NO SUBMIT CONTROL</span></div><div class="analysis-list"><div class="analysis-row"><span class="analysis-label">Public order button</span><strong class="up">NONE ✓</strong></div><div class="analysis-row"><span class="analysis-label">Private exact order packet</span><strong class="neutral">REVIEW OFF-SITE / PRIVATE</strong></div><div class="analysis-row"><span class="analysis-label">Automatic paper submit</span><strong class="up">DISABLED ✓</strong></div><div class="analysis-row"><span class="analysis-label">Live-money submit</span><strong class="up">UNSUPPORTED ✓</strong></div></div><p class="card-meta" style="margin-top:12px">When the private launch gate eventually becomes reviewable, Wavelength may prepare a private proposed-order packet. This public cockpit intentionally does not expose quantity, stop, account equity or executable instructions.</p></div><div class="card"><div class="card-head"><div><div class="card-title">Operational boundaries</div><div class="card-meta">What this feed can and cannot mean</div></div></div><div class="analysis-list"><div class="analysis-row"><span class="analysis-label">Reconciliation confidence</span><strong id="reconExplain">—</strong></div><div class="analysis-row"><span class="analysis-label">Twin-engine comparison</span><strong id="twinExplain">—</strong></div><div class="analysis-row"><span class="analysis-label">Incident queue</span><strong id="incidentExplain">—</strong></div><div class="analysis-row"><span class="analysis-label">Data health</span><strong id="dataExplain">—</strong></div></div></div></section>`;
const frag=document.createDocumentFragment();while(wrap.firstChild)frag.appendChild(wrap.firstChild);hero.parentNode.insertBefore(frag,hero.nextSibling)}
function render(x){ensure();$('#botOpsMeta').textContent=`${x.mode||'BOT OPERATIONS'} · generated ${age(x.generated_at)} · observability only`;$('#botOpsCircuit').textContent=x.circuit_breaker||'UNKNOWN';$('#botOpsCircuit').className='badge '+(x.circuit_breaker==='CLEAR'?'good':x.circuit_breaker==='HARD_BLOCK'?'bad':'warn');
$('#botOpsGrid').innerHTML=[['Launch state',x.first_paper_launch_state,'Only a manual-review readiness state; never submission permission.'],['Reconciliation',x.reconciliation_confidence==null?'—':`${x.reconciliation_confidence}%`,'Descriptive agreement across expected broker/persisted/protection state.'],['Guardian',x.guardian_status||'UNKNOWN','Public guardian summary only.'],['Data health',x.data_health||'UNKNOWN','Freshness/time-sync quality for the operational feed.'],['Hard blockers',x.hard_blocker_count??'—','Count only; private blocker detail is not exposed.'],['Soft blockers',x.soft_blocker_count??'—','Review items that do not grant execution permission.'],['Incidents',x.unacknowledged_incidents??'—','Unacknowledged operational incident count.'],['Paper trades',x.closed_paper_trades??0,'Closed controlled broker-paper trades observed by this maturity feed.'],['Canary stage',x.canary_review_stage||'—','Maximum stage eligible for manual review; risk never auto-escalates.'],['Twin engine',x.twin_engine_status||'—','Shadow-vs-paper comparison becomes meaningful only after paper fills accumulate.'],['Scheduled execution',x.scheduled_execution?'ENABLED':'DISABLED','Scheduled order submission remains off.'],['Auto promotion',x.automatic_promotion?'ENABLED':'DISABLED','Strategies cannot promote themselves.']].map(a=>metric(...a)).join('');
const state=x.first_paper_launch_state||'UNKNOWN';$('#botLaunchGate').innerHTML=`<div class="metric"><div class="metric-label">Current state</div><div class="metric-value ${cls(state)}">${esc(state.replaceAll('_',' '))}</div></div><div class="analysis-list" style="margin-top:12px"><div class="analysis-row"><span class="analysis-label">Hard blockers</span><strong>${esc(x.hard_blocker_count??'—')}</strong></div><div class="analysis-row"><span class="analysis-label">Soft review items</span><strong>${esc(x.soft_blocker_count??'—')}</strong></div><div class="analysis-row"><span class="analysis-label">Eligible review stage</span><strong>${esc(x.canary_review_stage||'—')}</strong></div><div class="analysis-row"><span class="analysis-label">Order permission</span><strong class="up">NO</strong></div></div><p class="card-meta" style="margin-top:10px">“Reviewable” means the private safety checklist is close enough for a human review. It does not mean an order will be sent.</p>`;
const strategies=x.strategies||[];$('#botStrategyRegistry').innerHTML=strategies.length?`<div class="analysis-list">${strategies.map(s=>`<div class="analysis-row"><span class="analysis-label">${esc(s.id)}</span><strong>${esc(s.version)} · ${esc((s.status||'—').replaceAll('_',' '))}</strong></div>`).join('')}</div>`:'<div class="empty">No strategy registry feed yet.</div>';
$('#reconExplain').textContent=x.reconciliation_confidence==null?'—':`${x.reconciliation_confidence}%`;$('#twinExplain').textContent=x.twin_engine_status||'—';$('#incidentExplain').textContent=`${x.unacknowledged_incidents??0} unacknowledged`;$('#dataExplain').textContent=x.data_health||'—';
if(x.orders_enabled||x.live_money_enabled){$('#botOpsMaturity').classList.add('bad');$('#botOpsMeta').textContent='SAFETY FEED VIOLATION — public status unexpectedly reports execution enabled';}}
async function load(){ensure();try{const x=await get();render(x)}catch(e){console.error(e);$('#botOpsMeta').textContent='Operational maturity feed unavailable';$('#botOpsCircuit').textContent='FEED ERROR';$('#botOpsCircuit').className='badge bad';$('#botOpsGrid').innerHTML='<div class="empty">Sanitised bot operations feed unavailable. This is not the same as “no signal”.</div>'}}
load();setInterval(load,60000);
})();
