(()=>{
'use strict';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=(v,d=2)=>v==null||!Number.isFinite(+v)?'—':(+v).toLocaleString('en-GB',{maximumFractionDigits:d,minimumFractionDigits:d});
const pct=v=>v==null||!Number.isFinite(+v)?'—':`${+v>=0?'+':''}${n(+v,2)}%`;
function cls(v){return v==='HELPFUL'?'trust-good':v==='HARMFUL'?'trust-bad':'trust-warn'}
function badge(v){return v==='HELPFUL'?'good':v==='HARMFUL'?'bad':'warn'}
function latest(rows,h='24h'){return rows.filter(x=>x.horizon===h)}
function card(r,isReject=false){const title=(r.feature||r.reason||'').replaceAll('_',' '),delta=isReject?r.protective_delta_pct:r.delta_vs_absent_pct,nobs=isReject?r.tagged_n:r.present_n;return `<article class="trust-card ${cls(r.verdict)}"><div class="card-head"><div><h3>${esc(title)}</h3><div class="card-meta">${esc(r.horizon)} horizon</div></div><span class="badge ${badge(r.verdict)}">${esc((r.verdict||'UNKNOWN').replaceAll('_',' '))}</span></div><div class="trust-score">${pct(delta)}</div><div class="trust-meta">${isReject?'Protective delta':'Delta vs condition absent'} · n=${nobs||0}<br>Evidence: ${esc((r.evidence_strength||'UNKNOWN').replaceAll('_',' '))}</div></article>`}
async function init(){try{const r=await fetch(`signal-calibration.json?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(r.status);const d=await r.json();$('#calStatus').className='status-pill';$('#calStatus').innerHTML='<span class="dot"></span>LIVE';$('#evidenceCount').textContent=d.record_count??'—';$('#evidenceMeta').textContent=`Resolved: ${d.resolved?.['4h']||0} 4h · ${d.resolved?.['24h']||0} 24h · ${d.resolved?.['7d']||0} 7d`;const sig=latest(d.signal_calibration||[],'24h');$('#signalGrid').innerHTML=sig.length?sig.map(x=>card(x,false)).join(''):'<div class="empty">Calibration sample not available yet.</div>';const rej=latest(d.rejection_calibration||[],'24h');$('#rejectGrid').innerHTML=rej.length?rej.map(x=>card(x,true)).join(''):'<div class="empty">Rejection calibration not available yet.</div>';const buckets=d.score_calibration||[];$('#scoreBuckets').innerHTML=buckets.map(b=>{const h=b.horizons?.['24h']||{};return `<div class="bucket-row"><b>${esc(b.bucket)}</b><span>n ${h.resolved_n||0}</span><span>avg ${pct(h.avg_pct)}</span><span>win ${h.win_rate_pct==null?'—':n(h.win_rate_pct,1)+'%'}</span></div>`}).join('')||'<div class="empty">No score evidence yet.</div>';$('#methodBody').innerHTML=`Source: durable server decision journal. Association, not causation. Directional labels require at least ${d.methodology?.minimum_n_for_directional_label||20} resolved observations. Multiple-testing caution remains in force. <b>No automatic parameter changes, no V3/Crowding mutation, no automatic promotion, no order authority.</b>`}catch(e){$('#calStatus').className='status-pill bad';$('#calStatus').innerHTML='<span class="dot"></span>UNAVAILABLE';$('#signalGrid').innerHTML='<div class="empty">Signal calibration feed is not published yet. The server workflow may be awaiting its first run.</div>'}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();