(()=>{
'use strict';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])), num=(v,d=2)=>Number.isFinite(+v)?(+v).toFixed(d):'—', pct=v=>Number.isFinite(+v)?`${+v>=0?'+':''}${(+v).toFixed(2)}%`:'—', money=v=>Number.isFinite(+v)?`${+v>=0?'+':''}$${Math.abs(+v).toFixed(2)}`:'—', cls=v=>+v>0?'up':+v<0?'down':'neutral';
const API='https://data-api.binance.vision';
const state={paper:null,radar:null,validation:null,learning:null};
const style=document.createElement('style');style.textContent=`
.pro-shell{display:grid;gap:16px;margin:18px 0}.pro-grid2{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.pro-grid3{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.pro-card{border:1px solid var(--border,#24303a);border-radius:16px;padding:18px;background:rgba(255,255,255,.012)}.pro-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;margin-bottom:14px}.pro-title{font:700 18px 'Bricolage Grotesque',sans-serif}.pro-meta{font:500 12px 'IBM Plex Mono',monospace;opacity:.62;margin-top:3px}.pro-kpis{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.pro-kpi{padding:12px;border-radius:12px;background:rgba(255,255,255,.025)}.pro-kpi b{display:block;font:700 18px 'IBM Plex Mono',monospace;margin-top:6px}.funnel{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:8px}.funnel-step{padding:12px;border:1px solid var(--border,#24303a);border-radius:12px;text-align:center}.funnel-step b{display:block;font:700 22px 'IBM Plex Mono',monospace}.bar{height:9px;border-radius:99px;background:rgba(255,255,255,.07);overflow:hidden}.bar>i{display:block;height:100%;background:currentColor}.exposure-row,.health-row,.journal-row,.perf-row{display:grid;grid-template-columns:120px 1fr auto;gap:10px;align-items:center;padding:9px 0;border-bottom:1px solid rgba(255,255,255,.06)}.health-dot{width:9px;height:9px;border-radius:50%;display:inline-block;margin-right:8px;background:currentColor}.health-good{color:#27d69b}.health-warn{color:#f3c969}.health-bad{color:#ff5d62}.validation-row{margin:12px 0}.validation-top{display:flex;justify-content:space-between;gap:10px;font:600 12px 'IBM Plex Mono',monospace;margin-bottom:6px}.spark{height:34px;margin-top:8px}.spark svg{width:100%;height:100%}.drawer{position:fixed;inset:0;display:none;z-index:9998;background:rgba(0,0,0,.55)}.drawer.open{display:block}.drawer-panel{position:absolute;right:0;top:0;height:100%;width:min(520px,94vw);overflow:auto;background:#0f141c;border-left:1px solid var(--border,#24303a);padding:24px}.drawer-close{float:right;border:1px solid var(--border,#24303a);background:transparent;color:inherit;border-radius:10px;padding:7px 10px;cursor:pointer}.quality{display:inline-block;padding:5px 9px;border-radius:999px;border:1px solid currentColor;font:700 12px 'IBM Plex Mono',monospace}.progress-axis{position:relative;height:14px;border-radius:99px;background:rgba(255,255,255,.07);margin:14px 0}.progress-axis .stopzone{position:absolute;left:0;top:0;bottom:0;width:50%;opacity:.18;background:#ff5d62;border-radius:99px 0 0 99px}.progress-axis .marker{position:absolute;top:-4px;width:3px;height:22px;background:currentColor}.changed-item{padding:10px 0;border-bottom:1px solid rgba(255,255,255,.06)}.mobile-nav-btn{display:none}.nav.mobile-open{display:flex!important}.empty-pro{opacity:.58;padding:12px 0}.clickable-heat{cursor:pointer}.clickable-heat:hover{transform:translateY(-1px)}
@media(max-width:900px){.pro-grid2,.pro-grid3,.pro-kpis,.funnel{grid-template-columns:1fr}.exposure-row,.health-row,.journal-row,.perf-row{grid-template-columns:92px 1fr}.exposure-row>:last-child,.health-row>:last-child,.journal-row>:last-child,.perf-row>:last-child{grid-column:2}.topbar{flex-wrap:wrap}.nav{display:none;width:100%;overflow-x:auto;padding-top:8px}.mobile-nav-btn{display:inline-flex;border:1px solid var(--border,#24303a);background:transparent;color:inherit;border-radius:10px;padding:8px 11px;cursor:pointer;margin-left:auto}}
`;document.head.appendChild(style);
async function j(url){const r=await fetch(`${url}?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(url);return r.json()}
function inject(){const anchor=document.querySelector('.hero');if(!anchor||$('#proCockpit'))return;const wrap=document.createElement('section');wrap.id='proCockpit';wrap.className='pro-shell';wrap.innerHTML=`
<div class="pro-grid2"><div class="pro-card"><div class="pro-head"><div><div class="pro-title">Opportunity funnel</div><div class="pro-meta">Watch → developing → near confirmation → qualified → paper</div></div><span class="badge warn">LIVE PIPELINE</span></div><div class="funnel" id="opportunityFunnel"></div></div><div class="pro-card"><div class="pro-head"><div><div class="pro-title">What changed?</div><div class="pro-meta">Since your previous visit on this browser</div></div></div><div id="whatChanged" class="empty-pro">Building comparison…</div></div></div>
<div class="pro-grid2"><div class="pro-card"><div class="pro-head"><div><div class="pro-title">Portfolio risk dashboard</div><div class="pro-meta">Open risk, stop-loss exposure, cash and concentration</div></div></div><div class="pro-kpis" id="riskKpis"></div><div id="exposureBreakdown" style="margin-top:14px"></div></div><div class="pro-card"><div class="pro-head"><div><div class="pro-title">Drawdown monitor</div><div class="pro-meta">Distance from equity high and recovery requirement</div></div></div><div id="drawdownMonitor"></div></div></div>
<div class="pro-grid3"><div class="pro-card"><div class="pro-head"><div><div class="pro-title">Performance by coin</div><div class="pro-meta">Realised trades only</div></div></div><div id="perfCoin"></div></div><div class="pro-card"><div class="pro-head"><div><div class="pro-title">Performance by regime</div><div class="pro-meta">RISK_ON / MIXED / RISK_OFF</div></div></div><div id="perfRegime"></div></div><div class="pro-card"><div class="pro-head"><div><div class="pro-title">Performance by setup quality</div><div class="pro-meta">Entry Intelligence bands</div></div></div><div id="perfSetup"></div></div></div>
<div class="pro-grid2"><div class="pro-card"><div class="pro-head"><div><div class="pro-title">Trade journal timeline</div><div class="pro-meta">Radar, entries, exits and regime context</div></div></div><div id="tradeJournal"></div></div><div class="pro-card"><div class="pro-head"><div><div class="pro-title">Forward-validation progress</div><div class="pro-meta">Visual gate progress — no promotion implied</div></div></div><div id="validationProgress"></div></div></div>
<div class="pro-card"><div class="pro-head"><div><div class="pro-title">System health</div><div class="pro-meta">Feed freshness and safety state</div></div><span class="badge good">ORDERS OFF</span></div><div id="systemHealth"></div></div>
<div class="drawer" id="tradeDrawer"><div class="drawer-panel"><button class="drawer-close" id="drawerClose">Close</button><div id="drawerBody"></div></div></div>`;anchor.insertAdjacentElement('afterend',wrap);
const nav=document.querySelector('.nav'),top=document.querySelector('.topbar');if(nav&&top&&!$('.mobile-nav-btn')){const b=document.createElement('button');b.className='mobile-nav-btn';b.textContent='Menu';b.onclick=()=>nav.classList.toggle('mobile-open');top.insertBefore(b,nav)}
$('#drawerClose').onclick=()=>$('#tradeDrawer').classList.remove('open');$('#tradeDrawer').onclick=e=>{if(e.target.id==='tradeDrawer')e.currentTarget.classList.remove('open')};
}
function age(ts){if(!ts)return Infinity;return (Date.now()-new Date(ts).getTime())/36e5}
function health(label,ts,goodHours,warnHours,detail=''){const a=age(ts),c=a<=goodHours?'health-good':a<=warnHours?'health-warn':'health-bad',status=a<=goodHours?'HEALTHY':a<=warnHours?'STALE':'STALE / CHECK';return `<div class="health-row"><span class="${c}"><i class="health-dot"></i>${esc(label)}</span><span>${detail|| (ts?new Date(ts).toLocaleString():'No timestamp')}</span><strong class="${c}">${status}</strong></div>`}
function renderFunnel(){const r=state.radar||{},p=state.paper||{},xs=r.opportunities||[];const counts={WATCH:0,DEVELOPING:0,NEAR_CONFIRMATION:0};xs.forEach(x=>counts[x.stage]=(counts[x.stage]||0)+1);const q=p.last_scan?.qualified||0,open=(p.open_positions||[]).length;$('#opportunityFunnel').innerHTML=[['WATCH',counts.WATCH],['DEVELOPING',counts.DEVELOPING],['NEAR CONF.',counts.NEAR_CONFIRMATION],['QUALIFIED',q],['PAPER',open]].map(([a,b])=>`<div class="funnel-step"><b>${b||0}</b><span>${a}</span></div>`).join('')}
function renderRisk(){const p=state.paper;if(!p)return;const open=p.open_positions||[],eq=+p.paper_equity||+p.paper_starting_equity||1;let stopLoss=0,notional=0;open.forEach(x=>{notional+=+x.current_value||0;stopLoss+=Math.max(0,(+x.current||0-(+x.stop||0))*(+x.quantity||0))});const planned=open.reduce((a,x)=>a+Math.max(0,(+x.entry-(+x.stop||0))*(+x.quantity||0)),0);const worst=eq-planned;const cashPct=(+p.cash||0)/eq*100;$('#riskKpis').innerHTML=[['Open positions',open.length],['Open notional',`$${notional.toFixed(2)}`],['Cash',`${cashPct.toFixed(1)}%`],['Planned stop risk',`$${planned.toFixed(2)}`],['Current stop buffer',`$${stopLoss.toFixed(2)}`],['Equity if all entry-risk hit',`$${worst.toFixed(2)}`]].map(([l,v])=>`<div class="pro-kpi"><span class="pro-meta">${l}</span><b>${v}</b></div>`).join('');const rows=[['Cash',+p.cash||0],...open.map(x=>[x.symbol,+x.current_value||0])];$('#exposureBreakdown').innerHTML=rows.map(([s,v])=>`<div class="exposure-row"><strong>${esc(s)}</strong><div class="bar"><i style="width:${Math.min(100,v/eq*100)}%"></i></div><span>${(v/eq*100).toFixed(1)}%</span></div>`).join('')}
function renderDrawdown(){const p=state.paper;if(!p)return;const eq=+p.paper_equity||0,start=+p.paper_starting_equity||0;let high=Math.max(eq,start);try{const old=JSON.parse(localStorage.getItem('wavelength_equity_high')||'null');if(Number.isFinite(+old))high=Math.max(high,+old)}catch{}localStorage.setItem('wavelength_equity_high',String(high));const dd=high?100*(eq/high-1):0,recover=eq>0?100*(high/eq-1):0;$('#drawdownMonitor').innerHTML=`<div class="pro-kpis"><div class="pro-kpi"><span class="pro-meta">Equity high</span><b>$${high.toFixed(2)}</b></div><div class="pro-kpi"><span class="pro-meta">Current drawdown</span><b class="${cls(dd)}">${pct(dd)}</b></div><div class="pro-kpi"><span class="pro-meta">Recovery needed</span><b>${recover.toFixed(2)}%</b></div></div><div class="bar" style="margin-top:14px"><i style="width:${Math.max(0,Math.min(100,100+dd))}%"></i></div>`}
function aggregate(keyFn){const ts=state.paper?.recent_closed_trades||[];const m={};ts.forEach(t=>{const k=keyFn(t);(m[k]??=[]).push(t)});return m}
function perfHtml(groups){const entries=Object.entries(groups);if(!entries.length)return '<div class="empty-pro">Waiting for closed trades. No performance conclusion is shown from open positions.</div>';return entries.map(([k,ts])=>{const pnl=ts.reduce((a,t)=>a+(+t.pnl||0),0),wins=ts.filter(t=>+t.pnl>0).length;return `<div class="perf-row"><strong>${esc(k)}</strong><span>${ts.length} trades · ${(100*wins/ts.length).toFixed(0)}% wins</span><b class="${cls(pnl)}">${money(pnl)}</b></div>`}).join('')}
function renderPerformance(){const ts=state.paper?.recent_closed_trades||[];$('#perfCoin').innerHTML=perfHtml(aggregate(t=>t.symbol||'Other'));$('#perfRegime').innerHTML=perfHtml(aggregate(t=>t.regime||'UNKNOWN'));$('#perfSetup').innerHTML=perfHtml(aggregate(t=>{const i=+t.intel||0;return i>=95?'Intel 95+':i>=85?'Intel 85–94':'Intel 75–84'}))}
function renderJournal(){const p=state.paper||{},r=state.radar||{};const rows=[];(p.open_positions||[]).forEach(x=>rows.push({t:p.generated_at,type:'PAPER ENTRY/OPEN',text:`${x.symbol} · Intel ${x.intel??'—'} · ${money(x.unrealized_pnl)} net`}));(p.recent_closed_trades||[]).slice(-8).forEach(x=>rows.push({t:x.exit_time||x.closed_at||p.generated_at,type:'PAPER EXIT',text:`${x.symbol} · ${(x.reason||'exit').replaceAll('_',' ')} · ${money(x.pnl)}`}));(r.opportunities||[]).filter(x=>x.stage==='NEAR_CONFIRMATION').slice(0,5).forEach(x=>rows.push({t:r.generated_at,type:'RADAR',text:`${x.symbol} near confirmation · score ${x.score}`}));rows.sort((a,b)=>new Date(b.t)-new Date(a.t));$('#tradeJournal').innerHTML=rows.length?rows.slice(0,12).map(x=>`<div class="journal-row"><strong>${esc(x.type)}</strong><span>${esc(x.text)}</span><span class="pro-meta">${x.t?new Date(x.t).toLocaleString():'—'}</span></div>`).join(''):'<div class="empty-pro">No journal events yet.</div>'}
function renderValidation(){const v=state.validation;if(!v)return;const out=[];Object.values(v.strategies||{}).forEach(s=>{const mt=+s.minimums?.completed_trades||1,md=+s.minimums?.calendar_days||1;const tradeP=Math.min(100,100*(+s.completed_trades||0)/mt),dayP=Math.min(100,100*(+s.observation_days||0)/md);out.push(`<div class="validation-row"><div class="validation-top"><span>${esc(s.name)}</span><span>${esc(s.status||'—')}</span></div><div class="pro-meta">Trades ${s.completed_trades||0}/${mt}</div><div class="bar"><i style="width:${tradeP}%"></i></div><div class="pro-meta" style="margin-top:7px">Days ${num(s.observation_days,0)}/${md}</div><div class="bar"><i style="width:${dayP}%"></i></div><div class="pro-meta" style="margin-top:7px">Unmet: ${esc((s.unmet_gates||[]).join(', ')||'none')}</div></div>`)});$('#validationProgress').innerHTML=out.join('')||'<div class="empty-pro">Validation feed unavailable.</div>'}
function renderHealth(){const p=state.paper||{},r=state.radar||{},v=state.validation||{},l=state.learning||{};$('#systemHealth').innerHTML=health('Hourly Radar',r.generated_at,2,4,`${r.scanned_markets||0} markets · orders ${r.orders_enabled?'ON':'OFF'}`)+health('4h Paper Engine',p.generated_at,5,9,`${p.open_positions?.length||0} open · simulation only`)+health('Learning',l.generated_at,6,12,`${l.stage||'—'} · auto weights ${l.automatic_weight_changes?'ON':'OFF'}`)+health('Validation',v.generated_at,6,12,`${v.live_ready?'LIVE READY':'NOT LIVE READY'} · orders ${v.orders_enabled?'ON':'OFF'}`)}
function quality(p){const i=+p.intel||0,rs=+p.vs_btc30||0,a=+p.adx||0;const score=i+(rs>5?4:0)+(a>=35?3:0);return score>=100?'A+':score>=94?'A':score>=86?'B':'C'}
async function spark(symbol){try{const r=await fetch(`${API}/api/v3/klines?symbol=${encodeURIComponent(symbol+'USDT')}&interval=1h&limit=24`,{cache:'no-store'});const d=await r.json();const vals=d.map(x=>+x[4]).filter(Number.isFinite);if(vals.length<2)return '';const mn=Math.min(...vals),mx=Math.max(...vals),range=mx-mn||1,W=320,H=34;const pts=vals.map((v,i)=>`${(i*(W/(vals.length-1))).toFixed(1)},${(H-(v-mn)/range*H).toFixed(1)}`).join(' ');return `<svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none"><polyline points="${pts}" fill="none" stroke="currentColor" stroke-width="2"/></svg>`}catch{return ''}}
async function openDrawer(symbol){const p=state.paper?.open_positions?.find(x=>x.symbol===symbol);if(!p)return;const r=state.radar?.opportunities?.find(x=>x.symbol===symbol),den=(+p.entry-(+p.stop||0)),riskUsed=den>0?Math.max(0,Math.min(100,100*((+p.entry-(+p.current||0))/den))):0;$('#drawerBody').innerHTML=`<div class="pro-meta">OPEN PAPER POSITION</div><h2>${esc(symbol)} <span class="quality">${quality(p)}</span></h2><p class="pro-meta">Why Wavelength selected it</p><div class="pro-kpis"><div class="pro-kpi"><span class="pro-meta">Intel</span><b>${p.intel??'—'}</b></div><div class="pro-kpi"><span class="pro-meta">ADX</span><b>${num(p.adx,1)}</b></div><div class="pro-kpi"><span class="pro-meta">RS vs BTC</span><b>${pct(p.vs_btc30)}</b></div><div class="pro-kpi"><span class="pro-meta">Net P&L</span><b class="${cls(p.unrealized_pnl)}">${money(p.unrealized_pnl)}</b></div><div class="pro-kpi"><span class="pro-meta">Entry</span><b>$${num(p.entry,6)}</b></div><div class="pro-kpi"><span class="pro-meta">Stop</span><b>$${num(p.stop,6)}</b></div></div><h3>Position progress</h3><div class="progress-axis"><div class="stopzone"></div><div class="marker" style="left:${50+Math.max(-45,Math.min(45,(+p.current/+p.entry-1)*500))}%"></div></div><div class="pro-meta">${riskUsed.toFixed(0)}% of planned downside risk used · ${r?`Radar: ${esc(r.stage)} · RSI ${num(r.rsi,1)} · Vol ${num(r.volume_ratio,2)}×`:'No current hourly-radar match'}</div><h3>Last 24h</h3><div class="spark" id="drawerSpark">Loading…</div><h3>Trade basis</h3><p>Entry remains governed by the 4h paper engine. Live dashboard pricing does not change the stop, entry rules or exit schedule.</p>`;$('#tradeDrawer').classList.add('open');$('#drawerSpark').innerHTML=await spark(symbol)}
function hookHeat(){document.querySelectorAll('#portfolioHeatmap .heat-tile').forEach(el=>{const a=el.querySelector('.heat-symbol a');if(!a)return;el.classList.add('clickable-heat');el.onclick=e=>{if(e.target.closest('a'))e.preventDefault();openDrawer(a.textContent.trim())}})}
function changedSnapshot(){const p=state.paper||{},r=state.radar||{};const now={regime:p.market_regime,open:(p.open_positions||[]).map(x=>x.symbol).sort(),near:(r.opportunities||[]).filter(x=>x.stage==='NEAR_CONFIRMATION').map(x=>x.symbol).sort(),equity:+p.paper_equity||null};let prev=null;try{prev=JSON.parse(localStorage.getItem('wavelength_pro_snapshot')||'null')}catch{}const items=[];if(prev){if(prev.regime!==now.regime)items.push(`Regime changed ${prev.regime||'—'} → ${now.regime||'—'}`);now.open.filter(x=>!prev.open?.includes(x)).forEach(x=>items.push(`${x} entered the paper portfolio`));prev.open?.filter(x=>!now.open.includes(x)).forEach(x=>items.push(`${x} left the paper portfolio`));now.near.filter(x=>!prev.near?.includes(x)).forEach(x=>items.push(`${x} moved to Near Confirmation`));if(Number.isFinite(prev.equity)&&Number.isFinite(now.equity)){const d=now.equity-prev.equity;if(Math.abs(d)>=.01)items.push(`Paper equity changed ${money(d)} since last visit`)}}$('#whatChanged').innerHTML=prev?(items.length?items.map(x=>`<div class="changed-item">${esc(x)}</div>`).join(''):'<div class="empty-pro">No material state changes since your previous visit.</div>'):'<div class="empty-pro">Baseline saved. Changes will appear on your next visit.</div>';localStorage.setItem('wavelength_pro_snapshot',JSON.stringify(now))}
async function load(){inject();const [p,r,v,l]=await Promise.allSettled([j('paper-portfolio.json'),j('opportunity-radar.json'),j('validation.json'),j('learning-status.json')]);if(p.status==='fulfilled')state.paper=p.value;if(r.status==='fulfilled')state.radar=r.value;if(v.status==='fulfilled')state.validation=v.value;if(l.status==='fulfilled')state.learning=l.value;renderFunnel();renderRisk();renderDrawdown();renderPerformance();renderJournal();renderValidation();renderHealth();changedSnapshot();setTimeout(hookHeat,500)}
load();setInterval(load,60000);new MutationObserver(()=>hookHeat()).observe(document.body,{subtree:true,childList:true});
})();
