(()=>{
'use strict';
const $=s=>document.querySelector(s), money=v=>Number.isFinite(+v)?`${+v>=0?'+':''}$${(+v).toFixed(2)}`:'—', pct=v=>Number.isFinite(+v)?`${+v>=0?'+':''}${(+v).toFixed(2)}%`:'—', cls=v=>+v>0?'up':+v<0?'down':'neutral', esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const PRICE_API='https://data-api.binance.vision/api/v3/ticker/price';let paperSnapshot=null,historySnapshot=null,liveBusy=false;
const style=document.createElement('style');style.textContent=`
.cockpit-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.radar-row{display:grid;grid-template-columns:70px 1fr 78px 78px 78px;gap:10px;align-items:center;padding:11px 0;border-bottom:1px solid var(--border,#24303a)}.radar-row:last-child{border-bottom:0}.radar-score{font:700 18px 'IBM Plex Mono',monospace}.heat-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.heat-tile{padding:16px;border:1px solid var(--border,#24303a);border-radius:14px;background:rgba(255,255,255,.018)}.heat-head{display:flex;justify-content:space-between;gap:12px;align-items:center}.heat-symbol{font:700 20px 'Bricolage Grotesque',sans-serif}.heat-pnl{font:700 18px 'IBM Plex Mono',monospace}.risk-track{height:8px;background:rgba(255,255,255,.07);border-radius:999px;overflow:hidden;margin:10px 0 6px}.risk-fill{height:100%;background:currentColor;border-radius:999px}.heat-meta{display:flex;justify-content:space-between;gap:8px;font-size:12px;opacity:.75}.chartbox{width:100%;height:250px}.chartbox svg{width:100%;height:100%;overflow:visible}.cal-grid{display:grid;grid-template-columns:repeat(7,minmax(36px,1fr));gap:6px}.cal-day{min-height:50px;border:1px solid var(--border,#24303a);border-radius:9px;padding:6px;font:600 11px 'IBM Plex Mono',monospace;background:rgba(255,255,255,.018)}.cal-day.pos{background:rgba(32,201,151,.12)}.cal-day.neg{background:rgba(255,99,132,.12)}.cal-date{opacity:.6;display:block;margin-bottom:6px}.subtle{font-size:12px;opacity:.7}@media(max-width:900px){.cockpit-grid,.heat-grid{grid-template-columns:1fr}.radar-row{grid-template-columns:60px 1fr 70px}.radar-row .optional{display:none}}
`;document.head.appendChild(style);
async function j(url){const r=await fetch(`${url}?t=${Date.now()}`);if(!r.ok)throw new Error(`${url} ${r.status}`);return r.json()}
async function livePrice(symbol){const r=await fetch(`${PRICE_API}?symbol=${encodeURIComponent(symbol+'USDT')}`,{cache:'no-store'});if(!r.ok)throw new Error(`${symbol} ${r.status}`);const d=await r.json(),px=+d.price;if(!Number.isFinite(px))throw new Error(`bad price ${symbol}`);return px}
function markPaper(d,prices){const fee=(+d.rules?.fee_per_side_pct||0)/100,slip=(+d.rules?.slippage_per_side_pct||0)/100,x=structuredClone(d);x.open_positions=(x.open_positions||[]).map(p=>{const market=prices[p.symbol];if(!Number.isFinite(market))return p;const qty=+p.quantity||0,entryValue=Number.isFinite(+p.entry_value)?+p.entry_value:qty*(+p.entry||0),entryFee=Number.isFinite(+p.entry_fee)?+p.entry_fee:entryValue*fee,currentValue=qty*market,exitGross=qty*market*(1-slip),exitFee=exitGross*fee,pnl=exitGross-exitFee-entryValue-entryFee;return {...p,current:market,current_value:currentValue,estimated_exit_fee:exitFee,estimated_round_trip_fees:entryFee+exitFee,unrealized_pnl:pnl,unrealized_net_pct:(entryValue+entryFee)>0?pnl/(entryValue+entryFee)*100:null}});x.paper_equity=(+x.cash||0)+x.open_positions.reduce((a,p)=>a+(+p.current_value||0),0);return x}
function renderRadar(d){const body=$('#hourlyRadar');if(!body)return;const xs=d.opportunities||[];$('#radarMeta').textContent=d.generated_at?`Last hourly scan ${new Date(d.generated_at).toLocaleString()} · ${d.scanned_markets||0} liquid markets · research only`:'Waiting for first hourly server scan…';body.innerHTML=xs.length?xs.slice(0,10).map(x=>`<div class="radar-row"><div class="radar-score">${x.score}</div><div><strong><a href="coin.html?symbol=${encodeURIComponent(x.symbol)}">${esc(x.symbol)}</a></strong><div class="subtle">${esc((x.stage||'WATCH').replaceAll('_',' '))}${x.breakout_20h?' · 20h breakout':''}</div></div><div class="${cls(x.change_24h)}">${pct(x.change_24h)}</div><div class="optional">ADX ${Number.isFinite(+x.adx)?(+x.adx).toFixed(1):'—'}</div><div class="optional">Vol ${Number.isFinite(+x.volume_ratio)?(+x.volume_ratio).toFixed(2)+'×':'—'}</div></div>`).join(''):'<div class="empty">No developing hourly opportunities currently meet the radar threshold.</div>'}
function renderHeat(d,isLive=false){const root=$('#portfolioHeatmap');if(!root)return;const xs=d.open_positions||[];root.innerHTML=xs.length?xs.map(p=>{const denom=p.entry-p.stop;const used=denom>0?Math.max(0,Math.min(100,100*(p.entry-p.current)/denom)):0;const buffer=Number.isFinite(+p.current)&&Number.isFinite(+p.stop)?100*(p.current-p.stop)/p.current:null;return `<div class="heat-tile"><div class="heat-head"><div class="heat-symbol"><a href="coin.html?symbol=${encodeURIComponent(p.symbol)}">${esc(p.symbol)}</a></div><div class="heat-pnl ${cls(p.unrealized_pnl)}">${money(p.unrealized_pnl)}</div></div><div class="heat-meta"><span>${pct(p.unrealized_net_pct)} net${isLive?' · LIVE':''}</span><span>Intel ${p.intel??'—'}</span></div><div class="risk-track ${used>70?'down':used>35?'neutral':'up'}"><div class="risk-fill" style="width:${used}%"></div></div><div class="heat-meta"><span>${used.toFixed(0)}% planned risk used</span><span>${buffer==null?'—':buffer.toFixed(2)+'%'} above stop</span></div><div class="heat-meta" style="margin-top:8px"><span>Value $${Number.isFinite(+p.current_value)?(+p.current_value).toFixed(2):'—'}</span><span>Stop $${Number.isFinite(+p.stop)?(+p.stop).toLocaleString('en-US',{maximumFractionDigits:6}):'—'}</span></div></div>`}).join(''):'<div class="empty">No open paper positions.</div>'}
function lineSvg(points){if(points.length<2)return '<div class="empty">The equity curve will appear after more scheduled paper snapshots.</div>';const W=900,H=240,p=18,vals=points.map(x=>+x.equity),mn=Math.min(...vals),mx=Math.max(...vals),range=mx-mn||1;const xy=points.map((x,i)=>[p+i*(W-2*p)/(points.length-1),H-p-(+x.equity-mn)*(H-2*p)/range]);const path=xy.map((q,i)=>(i?'L':'M')+q[0].toFixed(1)+','+q[1].toFixed(1)).join(' ');return `<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Paper equity curve"><line x1="${p}" y1="${H-p}" x2="${W-p}" y2="${H-p}" stroke="currentColor" opacity=".15"/><path d="${path}" fill="none" stroke="currentColor" stroke-width="3"/><text x="${p}" y="14" fill="currentColor" opacity=".7" font-size="12">High $${mx.toFixed(2)}</text><text x="${W-p}" y="14" text-anchor="end" fill="currentColor" opacity=".7" font-size="12">Now $${vals.at(-1).toFixed(2)}</text><text x="${p}" y="${H-3}" fill="currentColor" opacity=".55" font-size="11">Low $${mn.toFixed(2)}</text></svg>`}
function renderHistory(d,liveEquity=null){const curve=$('#equityCurve'),cal=$('#pnlCalendar');if(curve){const pts=(d.equity_curve||[]).slice();if(Number.isFinite(+liveEquity))pts.push({time_ms:Date.now(),equity:+liveEquity});curve.innerHTML=lineSvg(pts)}if(!cal)return;const xs=d.calendar||[];cal.innerHTML=xs.length?xs.slice(-35).map(x=>`<div class="cal-day ${+x.pnl>0?'pos':+x.pnl<0?'neg':''}"><span class="cal-date">${esc(x.date.slice(5))}</span><span class="${cls(x.pnl)}">${money(x.pnl)}</span><div class="subtle">${pct(x.return_pct)}</div></div>`).join(''):'<div class="empty">Daily P&L squares will build as scheduled paper snapshots accumulate.</div>'}
async function liveMark(){if(liveBusy||!paperSnapshot||(paperSnapshot.open_positions||[]).length===0)return;liveBusy=true;try{const pairs=await Promise.all((paperSnapshot.open_positions||[]).map(async p=>[p.symbol,await livePrice(p.symbol)])),live=markPaper(paperSnapshot,Object.fromEntries(pairs));renderHeat(live,true);if(historySnapshot)renderHistory(historySnapshot,live.paper_equity)}catch(e){console.warn('Overview live P&L fallback',e)}finally{liveBusy=false}}
async function load(){const [r,p,h]=await Promise.allSettled([j('opportunity-radar.json'),j('paper-portfolio.json'),j('paper-history.json')]);if(r.status==='fulfilled')renderRadar(r.value);if(p.status==='fulfilled'){paperSnapshot=p.value;renderHeat(p.value)}if(h.status==='fulfilled'){historySnapshot=h.value;renderHistory(h.value)}liveMark()}
load();setInterval(load,60000);setInterval(liveMark,10000);
})();
