(()=>{'use strict';
const qs=new URLSearchParams(location.search),symbol=(qs.get('symbol')||'ETH').toUpperCase().replace(/[^A-Z0-9]/g,''),$=s=>document.querySelector(s);
const esc=s=>String(s??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=(v,d=1)=>v==null||!Number.isFinite(+v)?'—':(+v).toLocaleString('en-GB',{minimumFractionDigits:d,maximumFractionDigits:d});
const pct=v=>v==null||!Number.isFinite(+v)?'—':`${+v>=0?'+':''}${n(v,1)}%`;
function ensure(){if($('#coinHistory'))return;const anchor=$('#wavelengthRead');if(!anchor)return;const s=document.createElement('section');s.className='card';s.id='coinHistory';s.innerHTML=`<div class="card-head"><div><div class="card-title">Intelligence history</div><div class="card-meta" id="historyMeta">Loading durable Wavelength snapshots…</div></div><span class="badge" id="historyBadge">COLLECTING</span></div><div class="grid4" id="historyMetrics"><div class="empty">Loading…</div></div><div class="grid2" style="margin-top:14px"><div><div class="card-title" style="font-size:14px">Score trajectory</div><div id="historyChart" style="min-height:180px;margin-top:8px"></div></div><div><div class="card-title" style="font-size:14px">What changed</div><div class="context-list" id="historyChanges"><div class="empty">Waiting for snapshots…</div></div></div></div><div class="grid2" style="margin-top:14px"><div><div class="card-title" style="font-size:14px">Recent snapshots</div><div id="historyTable" class="table-wrap"></div></div><div><div class="card-title" style="font-size:14px">Prior opportunities & alerts</div><div id="historyEvents" class="context-list"></div></div></div><p class="card-meta" style="margin-top:12px">Durable server snapshots are sampled every four hours and retained for roughly 90 days. Browser-local opportunity outcomes are shown separately and are not treated as server-side validation evidence.</p>`;anchor.insertAdjacentElement('afterend',s)}
function nearestBefore(arr,ms){const cutoff=Date.now()-ms;let best=null;for(const x of arr){const t=Date.parse(x.ts);if(t<=cutoff&&(!best||t>Date.parse(best.ts)))best=x}return best}
function spark(arr){if(arr.length<2)return '<div class="empty">History has started; a trajectory appears after the next snapshot.</div>';const w=640,h=170,p=18,vals=arr.map(x=>+x.score),lo=Math.min(...vals,0),hi=Math.max(...vals,100),range=hi-lo||1,pts=arr.map((x,i)=>`${p+i*(w-2*p)/(arr.length-1)},${h-p-(x.score-lo)*(h-2*p)/range}`).join(' ');const last=arr.at(-1),first=arr[0];return `<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Wavelength intelligence score history" style="width:100%;height:180px"><line x1="${p}" y1="${h-p}" x2="${w-p}" y2="${h-p}" stroke="#242B39"/><line x1="${p}" y1="${p}" x2="${p}" y2="${h-p}" stroke="#242B39"/><polyline points="${pts}" fill="none" stroke="#E8A33D" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/><text x="${p}" y="${p+2}" fill="#8E97AA" font-size="11">100</text><text x="${p}" y="${h-4}" fill="#8E97AA" font-size="11">0</text><text x="${w-p}" y="${p+14}" text-anchor="end" fill="#EAEDF3" font-size="13">${esc(first.score)} → ${esc(last.score)}</text></svg>`}
function item(title,copy,kind=''){return `<div class="context-item"><strong class="${kind}">${esc(title)}</strong><p>${esc(copy)}</p></div>`}
function localEvents(){let opp=[],alerts=[];try{opp=JSON.parse(localStorage.getItem('wavelength_opportunities')||'[]')}catch{}try{alerts=JSON.parse(localStorage.getItem('wavelength_alert_log')||'[]')}catch{}const out=[];opp.filter(o=>o.symbol===symbol).slice(-5).reverse().forEach(o=>{const outcomes=['4h','24h','3d','7d'].filter(k=>o.h?.[k]!=null).map(k=>`${k} ${pct(o.h[k])}`).join(' · ');out.push(item(`Opportunity ${new Date(o.start).toLocaleDateString()}`,`Entry ${o.entry??'—'} · score ${o.score??'—'}${outcomes?` · ${outcomes}`:''}${o.done?' · completed':''}`,'up'))});alerts.filter(a=>a.symbol===symbol).slice(0,6).forEach(a=>out.push(item(`${a.type||'Alert'} · ${new Date(a.time).toLocaleString()}`,a.message||'','')));return out.join('')||'<div class="empty">No prior browser-local opportunities or alerts for this coin yet.</div>'}
function render(data){const arr=(data.symbols?.[symbol]||[]).filter(x=>x&&x.ts).sort((a,b)=>Date.parse(a.ts)-Date.parse(b.ts)),latest=arr.at(-1),d3=nearestBefore(arr,72*3600000),d7=nearestBefore(arr,7*24*3600000);$('#historyMeta').textContent=`${symbol} · ${arr.length} durable snapshots · feed ${data.generated_at?new Date(data.generated_at).toLocaleString():'not sampled yet'}`;$('#historyBadge').textContent=arr.length>=2?'HISTORY LIVE':'COLLECTING';$('#historyBadge').className='badge '+(arr.length>=2?'good':'warn');if(!latest){$('#historyMetrics').innerHTML='<div class="empty">The durable feed is ready but has not recorded its first snapshot yet.</div>';$('#historyEvents').innerHTML=localEvents();return}
const delta3=d3?latest.score-d3.score:null,delta7=d7?latest.score-d7.score:null,setupCount=arr.filter(x=>x.setup).length;$('#historyMetrics').innerHTML=[['Current score',`${latest.score}/100`,latest.score>=75?'up':latest.score<45?'down':''],['3-day change',delta3==null?'Collecting':`${delta3>=0?'+':''}${delta3} pts`,delta3>0?'up':delta3<0?'down':''],['7-day change',delta7==null?'Collecting':`${delta7>=0?'+':''}${delta7} pts`,delta7>0?'up':delta7<0?'down':''],['Setups observed',setupCount,'']].map(x=>`<div class="metric"><div class="metric-label">${x[0]}</div><div class="metric-value ${x[2]}">${x[1]}</div></div>`).join('');$('#historyChart').innerHTML=spark(arr.slice(-90));
const changes=[];if(d3){changes.push(item('Score over 3 days',`${d3.score}/100 → ${latest.score}/100 (${delta3>=0?'+':''}${delta3} points).`,delta3>0?'up':delta3<0?'down':''));if(d3.trend!==latest.trend)changes.push(item('Trend state changed',`${d3.trend} → ${latest.trend}.`,latest.trend==='BULLISH'?'up':latest.trend==='BEARISH'?'down':''));if(d3.adx!=null&&latest.adx!=null)changes.push(item('ADX movement',`${n(d3.adx,1)} → ${n(latest.adx,1)}. ${latest.adx>=35?'Trend strength is now above the strong-trend gate.':'Trend strength remains below the 35 gate.'}`,latest.adx>=35?'up':''));if(d3.vs_btc_30d_pct!=null&&latest.vs_btc_30d_pct!=null)changes.push(item('BTC-relative strength',`${pct(d3.vs_btc_30d_pct)} → ${pct(latest.vs_btc_30d_pct)} over the 30-day relative measure.`,latest.vs_btc_30d_pct>0?'up':'down'))}else changes.push(item('Three-day comparison collecting','A real 3-day before/after comparison will appear once the durable feed has at least 72 hours of snapshots.'));$('#historyChanges').innerHTML=changes.join('');
const rows=arr.slice(-12).reverse();$('#historyTable').innerHTML=`<table class="market-table"><thead><tr><th class="left">Time</th><th>Score</th><th>Trend</th><th>ADX</th><th>vs BTC</th><th>Setup</th></tr></thead><tbody>${rows.map(x=>`<tr><td class="left">${esc(new Date(x.ts).toLocaleString())}</td><td>${esc(x.score)}</td><td class="${x.trend==='BULLISH'?'up':x.trend==='BEARISH'?'down':'neutral'}">${esc(x.trend)}</td><td>${n(x.adx,1)}</td><td class="${+x.vs_btc_30d_pct>0?'up':+x.vs_btc_30d_pct<0?'down':''}">${pct(x.vs_btc_30d_pct)}</td><td>${x.setup?'✓':'—'}</td></tr>`).join('')}</tbody></table>`;$('#historyEvents').innerHTML=localEvents()}
async function load(){ensure();try{const r=await fetch(`intelligence-history.json?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(r.status);render(await r.json())}catch(e){$('#historyMeta').textContent='Durable history feed unavailable';$('#historyMetrics').innerHTML='<div class="empty">Could not load server-side intelligence history.</div>';$('#historyEvents').innerHTML=localEvents()}}
load();setInterval(load,240000);
})();
