(()=>{
'use strict';
const qs=new URLSearchParams(location.search),symbol=(qs.get('symbol')||'ETH').toUpperCase().replace(/[^A-Z0-9]/g,''),pair=symbol+'USDT';let timeframe='4h',chart,candleSeries,ema20Series,ema80Series,ema200Series,coinDetail=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const watch=new Set(JSON.parse(localStorage.getItem('wavelength_watchlist')||'[]'));
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));const n=(v,d=2)=>v==null||!Number.isFinite(+v)?'—':(+v).toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d});const money=v=>v==null||!Number.isFinite(+v)?'—':(+v>=1?'$'+(+v).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}):'$'+(+v).toLocaleString('en-US',{maximumFractionDigits:8}));const compact=v=>v==null||!Number.isFinite(+v)?'—':new Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:2}).format(+v);const pct=v=>v==null||!Number.isFinite(+v)?'—':`${+v>=0?'+':''}${n(v,2)}%`;const klass=v=>+v>0?'up':+v<0?'down':'neutral';
async function getJSON(url){const r=await fetch(url);if(!r.ok)throw new Error(`${r.status}: ${url}`);return r.json()}
function emaArray(vals,p){const out=[];if(vals.length<p)return out;let e=vals.slice(0,p).reduce((a,b)=>a+b,0)/p,k=2/(p+1);out.push({i:p-1,v:e});for(let i=p;i<vals.length;i++){e=vals[i]*k+e*(1-k);out.push({i,v:e})}return out}
function rsi(vals,p=14){if(vals.length<=p)return null;let g=0,l=0;for(let i=1;i<=p;i++){const d=vals[i]-vals[i-1];g+=Math.max(0,d);l+=Math.max(0,-d)}g/=p;l/=p;for(let i=p+1;i<vals.length;i++){const d=vals[i]-vals[i-1];g=(g*(p-1)+Math.max(0,d))/p;l=(l*(p-1)+Math.max(0,-d))/p}return l===0?100:100-100/(1+g/l)}
function atrAdx(ks,p=14){if(ks.length<p*2+2)return{atr:null,adx:null};const tr=[],plus=[],minus=[];for(let i=1;i<ks.length;i++){const h=+ks[i][2],lo=+ks[i][3],pc=+ks[i-1][4],ph=+ks[i-1][2],pl=+ks[i-1][3],up=h-ph,down=pl-lo;tr.push(Math.max(h-lo,Math.abs(h-pc),Math.abs(lo-pc)));plus.push(up>down&&up>0?up:0);minus.push(down>up&&down>0?down:0)}let a=tr.slice(0,p).reduce((x,y)=>x+y,0)/p,ps=plus.slice(0,p).reduce((x,y)=>x+y,0)/p,ms=minus.slice(0,p).reduce((x,y)=>x+y,0)/p;const dx=[];for(let i=p;i<tr.length;i++){a=(a*(p-1)+tr[i])/p;ps=(ps*(p-1)+plus[i])/p;ms=(ms*(p-1)+minus[i])/p;const pdi=a?100*ps/a:0,mdi=a?100*ms/a:0;dx.push(pdi+mdi?100*Math.abs(pdi-mdi)/(pdi+mdi):0)}if(dx.length<p)return{atr:a,adx:null};let adx=dx.slice(0,p).reduce((x,y)=>x+y,0)/p;for(let i=p;i<dx.length;i++)adx=(adx*(p-1)+dx[i])/p;return{atr:a,adx}}
function tech(ks){const closes=ks.map(k=>+k[4]),e20a=emaArray(closes,20),e80a=emaArray(closes,80),e200a=emaArray(closes,200),close=closes.at(-1),e20=e20a.at(-1)?.v,e80=e80a.at(-1)?.v,e200=e200a.at(-1)?.v,R=rsi(closes),aa=atrAdx(ks),atrPct=aa.atr/close*100,bull=e20>e80&&close>e200,bear=e20<e80&&close<e200,setup=bull&&R>=50&&R<=75&&aa.adx>=35;return{closes,e20a,e80a,e200a,e20,e80,e200,rsi:R,adx:aa.adx,atr:aa.atr,atrPct,close,bull,bear,setup}}
function initChart(){const el=$('#chart');chart=LightweightCharts.createChart(el,{layout:{background:{type:'solid',color:'#12161F'},textColor:'#8E97AA'},grid:{vertLines:{color:'#1A2029'},horzLines:{color:'#1A2029'}},rightPriceScale:{borderColor:'#242B39'},timeScale:{borderColor:'#242B39',timeVisible:true,secondsVisible:false},crosshair:{mode:0}});candleSeries=chart.addSeries(LightweightCharts.CandlestickSeries,{upColor:'#34D399',downColor:'#F4574F',borderVisible:false,wickUpColor:'#34D399',wickDownColor:'#F4574F'});ema20Series=chart.addSeries(LightweightCharts.LineSeries,{color:'#E8A33D',lineWidth:2,title:'EMA20'});ema80Series=chart.addSeries(LightweightCharts.LineSeries,{color:'#60A5FA',lineWidth:2,title:'EMA80'});ema200Series=chart.addSeries(LightweightCharts.LineSeries,{color:'#8E97AA',lineWidth:2,title:'EMA200'});new ResizeObserver(()=>chart.applyOptions({width:el.clientWidth,height:el.clientHeight})).observe(el)}
function toTime(k){return Math.floor(+k[0]/1000)}
async function loadChart(){try{$('#coinStatus').className='status-pill warn';$('#coinStatus').innerHTML='<span class="dot"></span>SCANNING';const limit=timeframe==='1m'||timeframe==='5m'?500:300,ks=await getJSON(`https://api.binance.com/api/v3/klines?symbol=${encodeURIComponent(pair)}&interval=${timeframe}&limit=${limit}`),t=tech(ks);candleSeries.setData(ks.map(k=>({time:toTime(k),open:+k[1],high:+k[2],low:+k[3],close:+k[4]})));const line=(arr)=>arr.map(x=>({time:toTime(ks[x.i]),value:x.v}));ema20Series.setData(line(t.e20a));ema80Series.setData(line(t.e80a));ema200Series.setData(line(t.e200a));chart.timeScale().fitContent();renderAnalysis(t);$('#chartMeta').textContent=`${pair} · ${timeframe} · EMA 20 / 80 / 200 · ${ks.length} candles`;$('#coinStatus').className='status-pill';$('#coinStatus').innerHTML='<span class="dot"></span>LIVE DATA'}catch(e){console.error(e);$('#coinStatus').className='status-pill bad';$('#coinStatus').innerHTML='<span class="dot"></span>DATA ERROR';$('#analysis').innerHTML='<div class="empty">This Binance pair or timeframe is unavailable.</div>'}}
function renderAnalysis(t){const trend=t.bull?'BULLISH':t.bear?'BEARISH':'MIXED',badge=$('#setupBadge');badge.textContent=t.setup?'V3-LIKE SETUP':'NO V3-LIKE SETUP';badge.className='badge '+(t.setup?'good':'');$('#analysis').innerHTML=`<div class="analysis-row"><span class="analysis-label">EMA 20 vs EMA 80</span><strong class="${t.e20>t.e80?'up':'down'}">${t.e20>t.e80?'FAST ABOVE SLOW ✓':'FAST BELOW SLOW'}</strong></div><div class="analysis-row"><span class="analysis-label">Price vs EMA 200</span><strong class="${t.close>t.e200?'up':'down'}">${t.close>t.e200?'ABOVE TREND ✓':'BELOW TREND'}</strong></div><div class="analysis-row"><span class="analysis-label">RSI 50–75 gate</span><strong class="${t.rsi>=50&&t.rsi<=75?'up':'neutral'}">${n(t.rsi,1)} ${t.rsi>=50&&t.rsi<=75?'✓':'✕'}</strong></div><div class="analysis-row"><span class="analysis-label">ADX ≥ 35 gate</span><strong class="${t.adx>=35?'up':'neutral'}">${n(t.adx,1)} ${t.adx>=35?'✓':'✕'}</strong></div><div class="analysis-row"><span class="analysis-label">Trend state</span><strong class="${trend==='BULLISH'?'up':trend==='BEARISH'?'down':'neutral'}">${trend}</strong></div><div class="analysis-row"><span class="analysis-label">Trading permission</span><strong class="accent">RESEARCH ONLY${symbol==='ETH'?' · V3 VALIDATION ASSET':''}</strong></div>`;$('#techMetrics').innerHTML=[['RSI',n(t.rsi,1),t.rsi>=50&&t.rsi<=75?'up':''],['ADX',n(t.adx,1),t.adx>=35?'up':''],['ATR',n(t.atrPct,2)+'%',''],['EMA20',money(t.e20),''],['EMA80',money(t.e80),''],['EMA200',money(t.e200),''],['Close',money(t.close),''],['Structure',trend,trend==='BULLISH'?'up':trend==='BEARISH'?'down':'neutral']].map(x=>`<div class="metric"><div class="metric-label">${x[0]}</div><div class="metric-value ${x[2]}">${x[1]}</div></div>`).join('')}
async function loadTicker(){try{const d=await getJSON(`https://api.binance.com/api/v3/ticker/24hr?symbol=${encodeURIComponent(pair)}`);$('#coinPrice').textContent=money(+d.lastPrice);$('#coinChange').textContent=`${pct(+d.priceChangePercent)} 24h · high ${money(+d.highPrice)} · low ${money(+d.lowPrice)}`;$('#coinChange').className=`card-meta ${klass(+d.priceChangePercent)}`;$('#coinTitle').textContent=symbol;$('#coinMeta').textContent=`${pair} · Binance spot market`}catch(e){$('#coinTitle').textContent=symbol;$('#coinMeta').textContent='Market ticker unavailable'}}
async function resolveCoinGecko(){try{const search=await getJSON(`https://api.coingecko.com/api/v3/search?query=${encodeURIComponent(symbol)}`),matches=(search.coins||[]).filter(c=>(c.symbol||'').toUpperCase()===symbol),hit=matches.sort((a,b)=>(a.market_cap_rank||99999)-(b.market_cap_rank||99999))[0]||(search.coins||[])[0];if(!hit)return;coinDetail=await getJSON(`https://api.coingecko.com/api/v3/coins/${encodeURIComponent(hit.id)}?localization=false&tickers=false&market_data=true&community_data=false&developer_data=false&sparkline=false`);renderFundamentals()}catch(e){console.warn('CoinGecko',e);$('#marketFacts').innerHTML='<div class="empty">CoinGecko fundamentals unavailable right now.</div>';$('#projectFacts').innerHTML='<div class="empty">Project profile unavailable right now.</div>'}}
function fact(label,value){return `<div class="fact"><dt>${esc(label)}</dt><dd>${value==null||value===''?'—':value}</dd></div>`}
function renderFundamentals(){const c=coinDetail,m=c.market_data||{};if(c.image?.large){$('#coinIcon').src=c.image.large;$('#coinIcon').hidden=false}$('#coinTitle').textContent=`${c.name||symbol} (${symbol})`;$('#coinMeta').textContent=[c.market_cap_rank?`Rank #${c.market_cap_rank}`:null,(c.categories||[])[0],c.genesis_date?`Genesis ${c.genesis_date}`:null].filter(Boolean).join(' · ');$('#marketFacts').innerHTML=[fact('Market cap',m.market_cap?.usd?'$'+compact(m.market_cap.usd):'—'),fact('Fully diluted value',m.fully_diluted_valuation?.usd?'$'+compact(m.fully_diluted_valuation.usd):'—'),fact('24h volume',m.total_volume?.usd?'$'+compact(m.total_volume.usd):'—'),fact('Circulating supply',m.circulating_supply?compact(m.circulating_supply)+' '+symbol:'—'),fact('Total supply',m.total_supply?compact(m.total_supply)+' '+symbol:'—'),fact('Max supply',m.max_supply?compact(m.max_supply)+' '+symbol:'—'),fact('All-time high',money(m.ath?.usd)),fact('From ATH',pct(m.ath_change_percentage?.usd)),fact('7d',pct(m.price_change_percentage_7d)),fact('30d',pct(m.price_change_percentage_30d)),fact('1y',pct(m.price_change_percentage_1y)),fact('24h market-cap change',pct(m.market_cap_change_percentage_24h))].join('');const cats=(c.categories||[]).slice(0,5).join(', '),home=(c.links?.homepage||[]).find(Boolean),explorer=(c.links?.blockchain_site||[]).find(Boolean);$('#projectFacts').innerHTML=[fact('Categories',esc(cats||'—')),fact('Genesis date',esc(c.genesis_date||'—')),fact('Hashing / consensus',esc(c.hashing_algorithm||'—')),fact('CoinGecko ID',esc(c.id)),fact('Homepage',home?`<a href="${esc(home)}" target="_blank" rel="noopener">Official site ↗</a>`:'—'),fact('Explorer',explorer?`<a href="${esc(explorer)}" target="_blank" rel="noopener">Blockchain explorer ↗</a>`:'—')].join('')}
function renderWatch(){const b=$('#watchButton');b.textContent=watch.has(symbol)?'★ On watchlist':'☆ Add to watchlist';b.classList.toggle('accent',watch.has(symbol))}$('#watchButton').addEventListener('click',()=>{watch.has(symbol)?watch.delete(symbol):watch.add(symbol);localStorage.setItem('wavelength_watchlist',JSON.stringify([...watch]));renderWatch()});$$('[data-tf]').forEach(b=>b.addEventListener('click',()=>{timeframe=b.dataset.tf;$$('[data-tf]').forEach(x=>x.classList.toggle('active',x===b));loadChart()}));
initChart();renderWatch();loadTicker();resolveCoinGecko();loadChart();setInterval(loadTicker,10000);
})();
