(()=>{
const q=s=>document.querySelector(s), esc=v=>String(v??'—').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const pct=v=>v==null?'—':`${Number(v).toFixed(2)}%`; const num=v=>v==null?'—':Number(v).toFixed(2);
const badge=(s)=>{const x=String(s||'UNKNOWN').toUpperCase();const c=/PASS|FRESH|READY|VALIDATED|OK|BROAD|BULLISH/.test(x)?'ok':/FAIL|STALE|MISSING|BLOCK|ERROR|HARD/.test(x)?'bad':'warn';return `<span class="badge ${c}">${esc(x)}</span>`};
const table=(heads,rows)=>`<table><thead><tr>${heads.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${heads.length}">No evidence yet.</td></tr>`}</tbody></table>`;
const metric=(label,value,sub='')=>`<div class="metric"><div class="metric-label">${esc(label)}</div><div class="metric-value">${value}</div>${sub?`<div class="metric-sub">${esc(sub)}</div>`:''}</div>`;
async function j(path){const r=await fetch(`${path}?v=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`${path} ${r.status}`);return r.json()}
const specs={
 validation:{path:'validation.json',max:8}, challenger:{path:'strategy-challenger-results.json',max:8}, analytics:{path:'outcome-analytics.json',max:8}, history:{path:'intelligence-history.json',max:8}, graduation:{path:'paper-graduation.json',max:8}, risk:{path:'institutional-risk-stress.json',max:24}
};
function tsOf(x){return x?.generated_at||x?.updated_at||null}
function freshness(name,x,max){const t=tsOf(x);if(!t)return {name,state:'MISSING_TIMESTAMP',age:null,max};const age=(Date.now()-Date.parse(t))/36e5;return {name,state:age>max*2?'STALE':age>max?'AGING':'FRESH',age,max}}
(async()=>{
 const data={},alarms=[]; await Promise.all(Object.entries(specs).map(async([k,s])=>{try{data[k]=await j(s.path)}catch(e){alarms.push({sev:'MISSING',source:k,msg:e.message})}}));
 const fresh=Object.entries(specs).filter(([k])=>data[k]).map(([k,s])=>freshness(k,data[k],s.max)); fresh.filter(f=>f.state!=='FRESH').forEach(f=>alarms.push({sev:f.state,source:f.name,msg:f.age==null?'No generated timestamp':`Age ${f.age.toFixed(1)}h; expected ≤${f.max}h`}));
 const g=data.graduation; if(g?.portfolio_paper_risk_gate?.simultaneous_new_entries_allowed===false)alarms.push({sev:'BLOCK',source:'portfolio',msg:`Co-admission blocked: ${g.portfolio_paper_risk_gate.state}`});
 (g?.strategies||[]).forEach(s=>(s.hard_blockers||[]).forEach(b=>alarms.push({sev:'BLOCK',source:s.strategy_id,msg:b})));
 const c=data.challenger; (c?.strategies||[]).forEach(s=>{if(s.status!=='PASS')alarms.push({sev:s.status||'WARN',source:s.strategy_id,msg:'Strategy challenger not fully passed'});const d=(s.tests||[]).find(t=>t.test==='EXECUTION_DELAY');if(s.strategy_id==='crowding_v2'&&d?.metric?.ex_best_return_pct<0)alarms.push({sev:'THIN',source:'crowding_v2',msg:`Exact-delay ex-best return ${pct(d.metric.ex_best_return_pct)}`})});
 const allFresh=fresh.length===Object.keys(specs).length&&fresh.every(f=>f.state==='FRESH'); q('#ccStatus').className=`status-pill ${alarms.some(a=>/STALE|MISSING|FAIL|ERROR/.test(a.sev))?'bad':alarms.length?'warn':'ok'}`; q('#ccStatus').innerHTML=`<span class="dot"></span>${alarms.length?'ATTENTION':'HEALTHY'}`;
 q('#healthBadge').className=`badge ${allFresh?'ok':'warn'}`;q('#healthBadge').textContent=allFresh?'ALL FRESH':'CHECK ALARMS';q('#healthMeta').textContent=`${fresh.filter(f=>f.state==='FRESH').length}/${Object.keys(specs).length} core feeds fresh · ${alarms.length} attention item(s)`;
 q('#healthGrid').innerHTML=[metric('Core feeds',`${fresh.filter(f=>f.state==='FRESH').length}/${Object.keys(specs).length}`,'fresh'),metric('Alarms',String(alarms.length)),metric('Hypothesis sample',String(data.analytics?.hypothesis_eligible_event_count??0),'canonical V1'),metric('Market context',`${num(data.analytics?.market_context_coverage?.coverage_pct)}%`,'canonical coverage')].join('');
 q('#alarmTable').innerHTML=table(['Severity','Source','Reason'],alarms.map(a=>[badge(a.sev),esc(a.source),esc(a.msg)]));
 const vs=data.validation?.strategies||{};q('#strategyTable').innerHTML=table(['Strategy','Position','Days','Trades','Return','PF','Status','Still unmet'],Object.values(vs).map(s=>[esc(s.name),esc(s.position),num(s.observation_days),esc(s.completed_trades),pct(s.return_pct),num(s.profit_factor),badge(s.status),esc((s.unmet_gates||[]).join(', '))]));
 q('#graduationTable').innerHTML=table(['Strategy','Lifecycle','Forward','PAPER entry','Blockers'],(g?.strategies||[]).map(s=>[esc(s.strategy_id),badge(s.lifecycle_state),`${num(s.forward?.days_observed)}d / ${esc(s.forward?.completed_trades)} trades`,badge(s.new_paper_entries_allowed?'ALLOWED':'BLOCKED'),esc((s.blockers||[]).join(', '))]));
 const mc=data.history?.market_context?.slice(-1)[0]||{};q('#regimeGrid').innerHTML=[metric('Market regime',badge(mc.market_regime||'UNKNOWN')),metric('BTC trend',badge(mc.btc_trend||'UNKNOWN')),metric('BTC volatility',badge(mc.btc_volatility_regime||'UNKNOWN')),metric('Bullish breadth',pct(mc.bullish_breadth_pct),`${esc(mc.universe_n||0)} symbols`)].join('');
 const pr=g?.portfolio_paper_risk_gate||data.risk?.shadow_candidate_research||{};q('#riskGrid').innerHTML=[metric('Co-admission',badge(pr.state||pr.admission_state||'UNKNOWN')),metric('Stress',pct(pr.simultaneous_drawdown_stress_pct)),metric('Warning',pct(pr.warning_threshold_pct)),metric('Hard',pct(pr.hard_threshold_pct))].join('');
 const hs=data.analytics?.hypotheses||[];q('#hypothesisTable').innerHTML=table(['Hypothesis','Status','Discovery N','Fresh requirement','Why it exists'],hs.map(h=>[esc(h.hypothesis_id||`${h.dimension}:${h.value}`),badge(h.status),esc(h.discovery_sample_n??h.segment?.n??'—'),esc(h.minimum_fresh_matching_events??15),esc(h.statement||'Discovery candidate awaiting forward falsification')]));
})().catch(e=>{q('#ccStatus').className='status-pill bad';q('#ccStatus').innerHTML='<span class="dot"></span>ERROR';q('#healthMeta').textContent=e.message});
})();