(()=>{let DATA=null,ROOM=null;const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function verdictText(v){return String(v||'').replaceAll('_',' ')}
function render(room){ROOM=room;if(!room)return;$('symbol').textContent=room.symbol;$('verdict').textContent=verdictText(room.verdict);$('rankline').textContent=`#${room.market_rank||'?'} of ${room.market_universe||'?'} · ${room.name||room.symbol}`;$('conviction').textContent=room.conviction_score==null?'—':`${room.conviction_score}`;$('fusion').textContent=room.fusion_score??'—';$('quality').textContent=room.data_quality??'—';$('stability').textContent=room.decision_stability?.score??'—';$('challengeScore').textContent=room.challenge?.robustness_pct==null?'—':`${room.challenge.robustness_pct}%`;$('challengeStatus').textContent=`${room.challenge?.status||'UNKNOWN'} · survived ${room.challenge?.survived||0}/${room.challenge?.total||0} attacks`;
 const sup=room.support||[],against=room.against||[];$('thesis').textContent=`${room.symbol} is currently ranked #${room.market_rank||'?'} with ${room.conviction_label||'unknown'} conviction. ${sup[0]||'No positive technical thesis is currently available.'}${against[0]?` Main counterpoint: ${against[0]}.`:''}`;
 $('timeframes').innerHTML=(room.timeframes?.line||[]).map(x=>`<span class="${x.state==='UP'?'up':x.state==='DOWN'?'down':'unknown'}"><b>${esc(x.timeframe)}</b> ${x.state==='UP'?'↑':x.state==='DOWN'?'↓':'?'} ${x.score??'—'}</span>`).join('')||'<span class="unknown">No timeframe data</span>';
 $('support').innerHTML=sup.map(x=>`<li>${esc(x)}</li>`).join('')||'<li>No current support text</li>';$('strengthen').innerHTML=(room.triggers?.would_strengthen||[]).map(x=>`<li>${esc(x)}</li>`).join('');$('invalidate').innerHTML=(room.triggers?.would_invalidate||[]).map(x=>`<li>${esc(x)}</li>`).join('');
 $('attacks').innerHTML=(room.challenge?.tests||[]).map(x=>`<div class="attack ${x.survived?'good':'bad'}"><b>${x.survived?'✓':'✕'} ${esc(x.test)}</b><div class="muted">${esc(x.detail)}</div></div>`).join('');
 $('alternatives').innerHTML=(room.alternatives||[]).map(x=>`<div class="alt"><span class="rank">#${x.rank}</span><span><b>${esc(x.symbol)}</b><br><span class="muted">${esc(verdictText(x.verdict))}</span></span><b>${x.rank_score??'—'}</b></div>`).join('')||'<p class="muted">No comparison set.</p>';
 $('execution').innerHTML=(room.execution?.notional_stress_curve||[]).map(x=>`<div class="alt"><span>$${Number(x.notional_usd||0).toLocaleString()}</span><span class="muted">Depth utilisation</span><b>${x.depth_utilisation_pct??'—'}% · ${esc(x.stress)}</b></div>`).join('')||'<p class="muted">Liquidity stress unavailable.</p>';
 $('gaps').innerHTML=(room.evidence_gaps||[]).map(x=>`<span class="pill">${esc(x.replaceAll('_',' '))}</span>`).join('')||'<span class="pill">No dimension marked unavailable</span>';
 $('challengeMini').innerHTML=(room.challenge?.tests||[]).slice(0,3).map(x=>`<div>${x.survived?'✓':'✕'} ${esc(x.test)}</div>`).join('');}
function findRoom(sym){return (DATA?.rooms||[]).find(x=>x.symbol===sym)}
function answer(q){q=(q||'').trim();if(!q)return 'Ask me about the best opportunity, compare two coins, robustness, risks, or what would change a decision.';const u=q.toUpperCase();const rooms=DATA?.rooms||[];const syms=rooms.filter(r=>u.includes(r.symbol)).map(r=>r.symbol);const best=rooms[0];
 if(/BEST.*(NOW|RIGHT|COIN|OPPORTUNITY)|WHAT.*BEST/.test(u)){return best?`Current top cross-sectional opportunity: ${best.symbol} (#${best.market_rank}) with conviction ${best.conviction_score}/100 and rank score ${best.rank_score}. Verdict: ${verdictText(best.verdict)}. Its current main strength is ${best.support?.[0]||'broad evidence alignment'}.`:'No ranked opportunity is available.'}
 if(/NOT OVEREXTENDED|NOT.*EXTEND|AVOID CHAS/.test(u)){const c=rooms.find(r=>!(r.alternatives||[]).some(()=>false)&&!((r.against||[]).join(' ').toLowerCase().includes('rsi'))&&((r.challenge?.tests||[]).find(t=>t.test==='Chasing stress')?.survived));return c?`${c.symbol} is the highest-ranked current candidate passing the chasing-stress check without an RSI-overextension warning. Rank #${c.market_rank}, conviction ${c.conviction_score}/100.`:'No candidate currently meets that filter.'}
 if(syms.length>=2){const a=findRoom(syms[0]),b=findRoom(syms[1]);if(a&&b){const winner=(a.rank_score??-1)>=(b.rank_score??-1)?a:b,loser=winner===a?b:a;return `${winner.symbol} currently ranks ahead of ${loser.symbol}: ${winner.rank_score} vs ${loser.rank_score}. ${winner.symbol} conviction is ${winner.conviction_score}/100 vs ${loser.conviction_score}/100. Robustness: ${winner.challenge?.robustness_pct??'—'}% vs ${loser.challenge?.robustness_pct??'—'}%. This is a research comparison, not a return forecast.`}}
 const sym=syms[0]||ROOM?.symbol;const r=findRoom(sym);if(!r)return 'I could not map that question to a current Wavelength asset.';
 if(/WHY/.test(u))return `${r.symbol} is #${r.market_rank}/${r.market_universe} because its relative score is ${r.rank_score}, fusion ${r.fusion_score}, regime fit ${r.regime_fit??'—'}, and stability ${r.decision_stability?.score??'—'}. Supporting evidence: ${(r.support||[]).slice(0,2).join('; ')||'none listed'}. Counterpoint: ${(r.against||[])[0]||'no primary counterpoint listed'}.`;
 if(/WHAT.*(ATTRACTIVE|BUY|CHANGE|MIND|STRENGTH)/.test(u))return `${r.symbol} would strengthen if: ${(r.triggers?.would_strengthen||[]).join('; ')}. I would weaken or invalidate the thesis if: ${(r.triggers?.would_invalidate||[]).join('; ')}.`;
 if(/ROBUST|CHALLENGE|SURVIV/.test(u))return `${r.symbol} survived ${r.challenge?.survived||0}/${r.challenge?.total||0} adversarial tests (${r.challenge?.robustness_pct??'—'}%, ${r.challenge?.status||'UNKNOWN'}). Failed tests: ${(r.challenge?.tests||[]).filter(x=>!x.survived).map(x=>x.test).join(', ')||'none'}.`;
 if(/RISK|WEAK|BAD|AGAINST/.test(u))return `${r.symbol} risks/weaknesses: ${(r.against||[]).join('; ')||'no technical counterpoints listed'}. Missing evidence: ${(r.evidence_gaps||[]).join(', ')||'none marked unavailable'}. Invalidation triggers: ${(r.triggers?.would_invalidate||[]).join('; ')}.`;
 return `${r.symbol}: rank #${r.market_rank}, conviction ${r.conviction_score}/100, fusion ${r.fusion_score}, robustness ${r.challenge?.robustness_pct??'—'}%, verdict ${verdictText(r.verdict)}. Ask “why ${r.symbol}?”, “what would change my mind on ${r.symbol}?”, or “challenge ${r.symbol}”.`;}
async function init(){try{const r=await fetch('conviction-room.json?'+Date.now());DATA=await r.json();const sel=$('assetSelect');sel.innerHTML=(DATA.rooms||[]).map(x=>`<option value="${esc(x.symbol)}">#${x.market_rank} ${esc(x.symbol)} — ${esc(verdictText(x.verdict))}</option>`).join('');sel.onchange=()=>render(findRoom(sel.value));render(DATA.top_opportunity||DATA.rooms?.[0]);$('askBtn').onclick=()=>{$('askAnswer').textContent=answer($('askInput').value)};$('askInput').addEventListener('keydown',e=>{if(e.key==='Enter')$('askBtn').click()});$('challengeBtn').onclick=()=>{$('attacks').scrollIntoView({behavior:'smooth'});$('askAnswer').textContent=`Challenge complete: ${ROOM.symbol} survived ${ROOM.challenge?.survived||0}/${ROOM.challenge?.total||0} tests (${ROOM.challenge?.robustness_pct??'—'}%). Review the failed attacks below.`}}catch(e){$('askAnswer').textContent='Conviction Room feed is not available yet.'}}
init();})();