(()=>{
'use strict';
const KEY='wavelength_decision_journal_v1';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=(v,d=2)=>v==null||!Number.isFinite(+v)?'—':(+v).toLocaleString('en-GB',{maximumFractionDigits:d,minimumFractionDigits:d});
const pct=v=>v==null||!Number.isFinite(+v)?'—':`${+v>=0?'+':''}${n(+v,2)}%`;
const tone=d=>d==='QUALIFIED'?'good':d==='REJECT'?'bad':'warn';
function rows(){try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}}
function avg(a){const x=a.filter(v=>v!=null&&Number.isFinite(+v)).map(Number);return x.length?x.reduce((s,v)=>s+v,0)/x.length:null}
function summary(all){const counts={QUALIFIED:0,WATCH:0,REJECT:0};all.forEach(r=>counts[r.decision]=(counts[r.decision]||0)+1);const reviewed=all.filter(r=>r.outcomes?.['7d']!=null).length;$('#summaryGrid').innerHTML=[['Total decisions',all.length],['Qualified',counts.QUALIFIED||0],['Watched',counts.WATCH||0],['Rejected',counts.REJECT||0],['Reviewed 7d',reviewed]].slice(0,4).map(([k,v])=>`<div class="summary-card"><span>${esc(k)}</span><b>${v}</b></div>`).join('')}
function review(all){const cards=['QUALIFIED','WATCH','REJECT'].map(d=>{const r=all.filter(x=>x.decision===d),a24=avg(r.map(x=>x.outcomes?.['24h'])),a7=avg(r.map(x=>x.outcomes?.['7d']));let verdict='Building sample';if(a7!=null){if(d==='REJECT')verdict=a7<=0?'Rejections mostly protected capital':'Rejected markets later rose';else verdict=a7>0?'Decision followed by positive return':'Decision followed by weak/negative return'}return `<div class="review-card"><div><span class="badge ${tone(d)}">${d}</span></div><b style="margin-top:10px">${r.length} records</b><div class="card-meta" style="margin-top:6px">Avg 24h ${pct(a24)} · Avg 7d ${pct(a7)}</div><div style="margin-top:9px;font-size:12px">${esc(verdict)}</div></div>`});$('#reviewGrid').innerHTML=cards.join('')}
function reason(r){return (r.decision==='REJECT'?r.against:r.why)?.[0]||'No reason recorded'}
function render(){const all=rows(),df=$('#decisionFilter').value,sf=$('#symbolFilter').value.trim().toUpperCase();summary(all);review(all);const shown=all.filter(r=>(df==='ALL'||r.decision===df)&&(!sf||r.symbol.includes(sf))).slice().reverse();const b=$('#decisionBody');b.innerHTML=shown.length?shown.map(r=>`<tr class="journal-row" data-id="${esc(r.id)}"><td class="left">${new Date(r.at).toLocaleString()}</td><td class="left"><a href="asset.html?symbol=${encodeURIComponent(r.symbol)}" class="asset-link">${esc(r.symbol)}</a></td><td><span class="badge ${tone(r.decision)}">${esc(r.decision)}</span></td><td>${r.score??'—'}</td><td>${r.price==null?'—':'$'+n(r.price,6)}</td><td>${pct(r.outcomes?.['4h'])}</td><td>${pct(r.outcomes?.['24h'])}</td><td>${pct(r.outcomes?.['3d'])}</td><td>${pct(r.outcomes?.['7d'])}</td><td class="left">${esc(reason(r))}</td></tr><tr><td colspan="10"><div class="journal-detail" id="d-${esc(r.id)}"><div class="explain-grid"><div><h4>Why</h4><p>${esc((r.why||[]).join(' · ')||'No positive evidence recorded.')}</p></div><div><h4>Against / rejection reasons</h4><p>${esc((r.against||[]).join(' · ')||'No rejection evidence recorded.')}</p></div><div><h4>Invalidation cues</h4><p>${esc((r.invalidation||[]).join(' · ')||'No invalidation cues recorded.')}</p></div></div><div class="card-meta" style="margin-top:10px">Authority: ${esc(r.authority||'RESEARCH_ONLY')}</div></div></td></tr>`).join(''):'<tr><td colspan="10" class="empty">No matching decisions recorded yet. Open the Overview scanner to begin capturing decisions.</td></tr>';b.querySelectorAll('.journal-row').forEach(tr=>tr.addEventListener('click',e=>{if(e.target.closest('a'))return;$('#d-'+CSS.escape(tr.dataset.id))?.classList.toggle('open')}))}
function init(){$('#decisionFilter').addEventListener('change',render);$('#symbolFilter').addEventListener('input',render);render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();