(()=>{'use strict';
const $=s=>document.querySelector(s),esc=s=>String(s??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),num=(v,d=2)=>v==null||!Number.isFinite(+v)?'—':(+v).toLocaleString('en-GB',{minimumFractionDigits:d,maximumFractionDigits:d}),human=s=>String(s||'').replaceAll('_',' ').toLowerCase().replace(/^./,c=>c.toUpperCase());
const names={candidate_v3:'Candidate V3',crowding_v2:'Crowding v2'};
function badgeClass(state){state=String(state||'UNKNOWN').toUpperCase();if(['PAPER_ELIGIBLE','PAPER_VALIDATED','WITHIN_STRESS_LIMITS'].includes(state))return'good';if(state==='WATCH'||state.includes('WAIT')||state.includes('VALIDATING')||state.includes('WARNING'))return'warn';return'bad'}
function badge(state){state=String(state||'UNKNOWN').toUpperCase();return `<span class="badge ${badgeClass(state)}">${esc(human(state))}</span>`}
function strat(s){const f=s.forward||{},c=s.challenger||{},req=s.requirements||{};return `<article class="metric"><div class="validation-top"><div><div class="strategy-name">${esc(names[s.strategy_id]||s.strategy_id)}</div><div class="card-meta">${esc(human(s.lifecycle_state))}</div></div>${badge(s.state)}</div><div class="grid4"><div><div class="metric-label">Forward days</div><div class="metric-value">${num(f.days_observed,1)} / ${num(req.minimum_forward_days,0)}</div></div><div><div class="metric-label">Fresh trades</div><div class="metric-value">${f.completed_trades??0} / ${req.minimum_completed_trades??'—'}</div></div><div><div class="metric-label">Challengers</div><div class="metric-value">${esc(c.status||'UNKNOWN')}</div></div><div><div class="metric-label">Exact delay</div><div class="metric-value">${c.execution_delay_thin_pass?'THIN':'CLEAR'}</div></div></div><div class="gate-list"><strong>Blockers:</strong> ${(s.blockers||[]).length?esc((s.blockers||[]).map(human).join(' · ')):'None'}</div><div class="card-meta" style="margin-top:8px">New PAPER entries: <strong>${s.new_paper_entries_allowed?'ALLOWED FOR MANUAL REVIEW':'BLOCKED'}</strong></div></article>`}
function metric(label,value){return `<div class="metric"><div class="metric-label">${esc(label)}</div><div class="metric-value">${esc(value)}</div></div>`}
function setOverall(state){const el=$('#overallState');if(!el)return;el.className=`badge ${badgeClass(state)}`;el.textContent=human(state)}
async function load(){try{const r=await fetch(`paper-graduation.json?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(r.status);const p=await r.json();$('#gradMeta').textContent=`Updated ${p.generated_at?new Date(p.generated_at).toLocaleString():'—'} · fail-closed PAPER entry governance`;setOverall(p.overall_state);$('#gradStatus').innerHTML='<span class="dot"></span>GOVERNED';$('#strategyGraduation').innerHTML=(p.strategies||[]).map(strat).join('');const e=p.execution_reality||{};$('#executionReality').innerHTML=[metric('PAPER scans',e.paper_scans_observed??0),metric('Execution attempts',e.execution_attempts??0),metric('Priced fills',e.fills_with_price_evidence??0),metric('Execution errors',e.execution_errors??0),metric('Avg slippage',e.avg_slippage_bps==null?'UNMEASURED':`${num(e.avg_slippage_bps,1)} bps`),metric('Guardian',human(e.guardian_status))].join('');const g=p.portfolio_paper_risk_gate||{};$('#portfolioGate').innerHTML=`${badge(g.state)}<div class="grid2" style="margin-top:12px">${metric('Simultaneous DD stress',g.simultaneous_drawdown_stress_pct==null?'—':`${num(g.simultaneous_drawdown_stress_pct,3)}%`)}${metric('Warning / hard',`${num(g.warning_threshold_pct,1)}% / ${num(g.hard_threshold_pct,1)}%`)}</div><div class="gate-list" style="margin-top:12px"><strong>Simultaneous new entries:</strong> ${g.simultaneous_new_entries_allowed?'ALLOWED':'BLOCKED'}</div><div class="card-meta" style="margin-top:8px">${esc((g.risk_flags||[]).map(human).join(' · ')||'No portfolio risk flags')}</div>`;const ladder=(p.production_eligibility||{}).ladder||[];$('#productionLadder').innerHTML=ladder.map(x=>metric(human(x),x==='LIMITED_CAPITAL_ELIGIBLE'?'MANUAL CAPITAL BOUNDARY':'EVIDENCE GATE')).join('');}catch(e){$('#gradMeta').textContent='Graduation feed unavailable — new PAPER entries fail closed';setOverall('NOT_ELIGIBLE');$('#strategyGraduation').innerHTML='<div class="empty">No current graduation evidence. Entry eligibility must be treated as blocked.</div>';$('#gradStatus').innerHTML='<span class="dot"></span>FAIL CLOSED'}}
load();setInterval(load,60000);
})();