(()=>{
'use strict';
const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));const n=(v,d=2)=>v==null||!Number.isFinite(+v)?'—':(+v).toFixed(d);const pct=v=>v==null?'—':`${v>=0?'+':''}${n(v,2)}%`;
const KEYS=['wavelength_watchlist','wavelength_alert_log','wavelength_opportunities','wavelength_prior_state'];
function load(){try{return JSON.parse(localStorage.getItem('wavelength_opportunities')||'[]')}catch{return[]}}
function stage(count){return count<10?['INSUFFICIENT DATA','warn','Need at least 10 resolved observations before treating factor comparisons as more than descriptive.']:count<25?['EARLY EVIDENCE','warn','Patterns are beginning to form, but sample size is still small.']:count<50?['EMERGING EVIDENCE','good','There is enough data for cautious factor comparisons, but not for automated weighting.']:['USABLE EVIDENCE','good','Sample size is large enough for stronger comparisons; changes should still be reviewed before promotion.']}
function avg(a){const x=a.filter(Number.isFinite);return x.length?x.reduce((p,c)=>p+c,0)/x.length:null}
function win(a){const x=a.filter(Number.isFinite);return x.length?100*x.filter(v=>v>0).length/x.length:null}
function stats(rows,h){const vals=rows.map(o=>o.h?.[h]).filter(Number.isFinite);return{n:vals.length,avg:avg(vals),win:win(vals)}}
const FACTORS=[['strong_trend','ADX ≥35'],['healthy_momentum','RSI 50–75'],['rs_leader','30d RS leader'],['high_intel','Intel ≥75'],['crowded_longs','Crowded longs'],['rs_laggard','30d RS laggard']];
function factorStats(rows,key,h){const yes=rows.filter(o=>o.features?.[key]===true),no=rows.filter(o=>o.features&&o.features[key]===false),a=stats(yes,h),b=stats(no,h),raw=a.avg!=null&&b.avg!=null?a.avg-b.avg:null,shrink=raw==null?null:raw*(a.n/(a.n+10));return{yes:a,no:b,raw,shrunk:shrink}}
function render(){const rows=load(),featured=rows.filter(o=>o.features),resolved=featured.filter(o=>Number.isFinite(o.h?.['24h'])),s=stage(resolved.length);$('#learnStatus').textContent=s[0];$('#learnStatus').className='badge '+s[1];$('#learnMeta').textContent=`${featured.length} captured setups · ${resolved.length} with 24h outcomes · advisory only`;
$('#sampleSummary').innerHTML=[['Captured setups',featured.length],['24h resolved',stats(featured,'24h').n],['3d resolved',stats(featured,'3d').n],['7d resolved',stats(featured,'7d').n],['24h avg',pct(stats(featured,'24h').avg)],['24h win rate',stats(featured,'24h').win==null?'—':n(stats(featured,'24h').win,1)+'%'],['3d avg',pct(stats(featured,'3d').avg)],['7d avg',pct(stats(featured,'7d').avg)]].map(x=>`<div class="metric"><div class="metric-label">${x[0]}</div><div class="metric-value">${x[1]}</div></div>`).join('');
$('#confidenceText').innerHTML=`<p><strong>${s[0]}.</strong> ${esc(s[2])}</p><p>Wavelength uses shrinkage: apparent factor uplift is multiplied by <code>n / (n + 10)</code>. This deliberately suppresses exciting-looking results from tiny samples.</p>`;
const horizons=['24h','3d','7d'];let table='';for(const h of horizons){for(const [key,label] of FACTORS){const f=factorStats(featured,key,h);table+=`<tr><td class="left">${label}</td><td>${h}</td><td>${f.yes.n}</td><td>${pct(f.yes.avg)}</td><td>${f.yes.win==null?'—':n(f.yes.win,1)+'%'}</td><td>${f.no.n}</td><td>${pct(f.no.avg)}</td><td class="${(f.shrunk||0)>0?'up':(f.shrunk||0)<0?'down':''}">${pct(f.shrunk)}</td></tr>`}}$('#factorBody').innerHTML=table||'<tr><td colspan="8" class="empty">No feature-tagged opportunities yet.</td></tr>';
const recs=[];for(const [key,label] of FACTORS){const f=factorStats(featured,key,'24h');if(f.yes.n<5||f.no.n<5||f.shrunk==null)continue;recs.push({label,u:f.shrunk,n:f.yes.n+f.no.n})}recs.sort((a,b)=>Math.abs(b.u)-Math.abs(a.u));$('#recommendations').innerHTML=recs.length?recs.slice(0,6).map(r=>`<div class="analysis-row"><span class="analysis-label">${esc(r.label)}</span><strong class="${r.u>0?'up':'down'}">${r.u>0?'Consider ↑':'Consider ↓'} · shrunk uplift ${pct(r.u)} · n=${r.n}</strong></div>`).join(''):'<div class="empty">No factor has enough opposing samples yet to recommend even a provisional weight change.</div>';
const cohorts={};for(const o of featured){const f=o.features||{},k=[f.strong_trend?'ADX+':'ADX-',f.rs_leader?'RS+':'RS-',f.high_intel?'INTEL+':'INTEL-',f.crowded_longs?'CROWD':'NORMAL'].join(' · ');(cohorts[k]??=[]).push(o)}const cr=Object.entries(cohorts).map(([k,v])=>({k,s:stats(v,'24h')})).filter(x=>x.s.n).sort((a,b)=>(b.s.avg??-999)-(a.s.avg??-999));$('#cohortBody').innerHTML=cr.length?cr.slice(0,10).map(x=>`<tr><td class="left">${esc(x.k)}</td><td>${x.s.n}</td><td class="${(x.s.avg||0)>0?'up':(x.s.avg||0)<0?'down':''}">${pct(x.s.avg)}</td><td>${x.s.win==null?'—':n(x.s.win,1)+'%'}</td></tr>`).join(''):'<tr><td colspan="4" class="empty">Cohort results will appear as tracked setups mature.</td></tr>';
}
function exportData(){const data={schema:'wavelength-research-v1',exported_at:new Date().toISOString(),storage:{}};for(const k of KEYS)data.storage[k]=localStorage.getItem(k);const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`wavelength-research-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('#vaultStatus').textContent='Backup exported.'}
function importData(file){const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(d.schema!=='wavelength-research-v1'||!d.storage)throw new Error('Unsupported backup');for(const k of KEYS)if(k in d.storage&&d.storage[k]!=null)localStorage.setItem(k,d.storage[k]);$('#vaultStatus').textContent='Backup imported. Reloading…';setTimeout(()=>location.reload(),500)}catch{$('#vaultStatus').textContent='Import failed: invalid Wavelength backup.'}};r.readAsText(file)}
$('#exportResearch')?.addEventListener('click',exportData);$('#importResearch')?.addEventListener('click',()=>$('#importFile').click());$('#importFile')?.addEventListener('change',e=>{const f=e.target.files?.[0];if(f)importData(f)});
render();window.addEventListener('storage',render);setInterval(render,15000);
})();
