(()=>{
'use strict';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=(v,d=2)=>v==null||!Number.isFinite(+v)?'—':(+v).toLocaleString('en-GB',{maximumFractionDigits:d,minimumFractionDigits:d});
const pct=v=>v==null||!Number.isFinite(+v)?'—':`${+v>=0?'+':''}${n(v,2)}%`;
const label=s=>String(s||'').replaceAll('_',' ');
const tone=s=>/STRONGER|RISK_ON|GOOD/.test(String(s||''))?'good':/INSUFFICIENT|RISK_OFF|CONFLICT/.test(String(s||''))?'bad':'warn';
let data=null;
async function load(){try{const r=await fetch(`market-memory.json?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(r.status);data=await r.json();render();$('#mmFeed').className='status-pill';$('#mmFeed').innerHTML='<span class="dot"></span>LIVE'}catch(e){console.error(e);$('#mmFeed').className='status-pill bad';$('#mmFeed').innerHTML='<span class="dot"></span>UNAVAILABLE';$('#mmCurrent').innerHTML='<div class="empty">Market Memory feed is not available yet.</div>'}}
function renderKpis(){const r=data.resolved_exact||{},a=data.analogues||{},best=Object.values(a).sort((x,y)=>(y.best_similarity_pct||0)-(x.best_similarity_pct||0))[0];$('#mmKpis').innerHTML=[['Frozen states',data.record_count||0],['Memory runs',data.run_count||0],['Exact 24h',r['24h']||0],['Exact 7d',r['7d']||0],['Best analogue',best?`${best.symbol} ${n(best.best_similarity_pct,0)}%`:'—']].map(([k,v])=>`<div class="mm-kpi"><span>${esc(k)}</span><b>${esc(v)}</b></div>`).join('');$('#mmMeta').textContent=`Updated ${data.generated_at?new Date(data.generated_at).toLocaleString():'—'} · ${data.new_records_this_run||0} new states · ${data.new_exact_outcomes_this_run||0} new exact outcomes`}
function summaryCells(report){const s=report.outcome_summary||{};return ['4h','24h','7d','30d'].map(h=>{const x=s[h]||{};return `<div class="mm-outcome"><small>${h.toUpperCase()} · n=${x.n||0}</small><b>${x.n?pct(x.median_pct):'—'}</b><small>median · win ${x.win_rate_pct==null?'—':n(x.win_rate_pct,0)+'%'}</small></div>`}).join('')}
function renderCurrent(){let rows=Object.values(data.analogues||{}).sort((a,b)=>(b.best_similarity_pct||0)-(a.best_similarity_pct||0));$('#mmCurrent').innerHTML=rows.length?rows.map(r=>`<article class="mm-card"><div class="card-head"><div><a class="mm-link" href="asset.html?symbol=${encodeURIComponent(r.symbol)}"><div class="card-title">${esc(r.symbol)}</div></a><div class="card-meta">${r.analogue_count||0} analogues · ${r.same_symbol_count||0} same-asset · best similarity ${r.best_similarity_pct==null?'—':n(r.best_similarity_pct,1)+'%'}</div></div><span class="badge ${tone((data.maturity||{})['24h'])}">${esc(label((data.maturity||{})['24h']||'INSUFFICIENT_SAMPLE'))}</span></div>${summaryCells(r)}<div class="mm-note" style="margin-top:12px">${(r.analogues||[]).slice(0,3).map(x=>`${esc(x.symbol)} ${n(x.similarity_pct,1)}% · ${x.captured_at?new Date(x.captured_at).toLocaleString():'—'} · 24h ${pct(x.outcomes?.['24h'])}`).join('<br>')||'No resolved historical analogue yet.'}</div></article>`).join(''):'<div class="empty">No historical precedents yet. The memory collector has only just started.</div>'}
function renderMaturity(){const r=data.resolved_exact||{},m=data.maturity||{};$('#mmMaturity').innerHTML=`<table class="mm-table"><thead><tr><th>Horizon</th><th>Resolved</th><th>Maturity</th></tr></thead><tbody>${['1h','4h','12h','24h','3d','7d','30d'].map(h=>`<tr><td>${h}</td><td>${r[h]||0}</td><td><span class="badge ${tone(m[h])}">${esc(label(m[h]||'INSUFFICIENT_SAMPLE'))}</span></td></tr>`).join('')}</tbody></table>`}
function renderMethod(){const x=data.methodology||{},g=data.guardrails||{};$('#mmMethod').innerHTML=`<b>Capture:</b> ${esc(x.capture||'—')}<br><b>Exact outcomes:</b> ${esc(x.exact_forward_outcomes||'—')}<br><b>Path:</b> ${esc(x.path_measurement||'—')}<br><b>Similarity:</b> ${esc(x.similarity||'—')}<br><br><b>Hard boundary:</b> orders ${g.no_order_submission?'OFF':'UNKNOWN'} · live money ${g.no_live_money?'OFF':'UNKNOWN'} · strategy mutation ${g.no_strategy_mutation?'OFF':'UNKNOWN'} · parameter mutation ${g.no_parameter_mutation?'OFF':'UNKNOWN'} · capital authority ${g.no_capital_authority?'OFF':'UNKNOWN'}.`}
function render(){renderKpis();renderCurrent();renderMaturity();renderMethod()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load,{once:true});else load();setInterval(load,300000);
})();