(()=>{
const $=s=>document.querySelector(s), esc=s=>String(s??'—').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
let D={};
function pct(v){return v==null?'—':`${Number(v).toFixed(1)}%`}
function n(v,d=1){return v==null?'—':Number(v).toFixed(d)}
function fill(sel,vals){const el=$(sel); if(!el)return; el.innerHTML=vals.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('')}
function cell(v){if(v==null)return '<span class="cell">—</span>';const x=Math.max(0,Math.min(100,Number(v)));const a=.08+.22*x/100;return `<span class="cell" style="background:rgba(111,137,181,${a})">${x.toFixed(0)}</span>`}
function renderHero(){const rooms=D.rooms||[];const top=rooms[0];const changes=(D.explainable_opportunity_alerts||[]).length;$('#heroKpis').innerHTML=`<div class="mini"><small>Top opportunity</small><b>${esc(top?.symbol||'—')} ${top?.conviction_score!=null?n(top.conviction_score):''}</b></div><div class="mini"><small>Replay snapshots</small><b>${D.replay_mode?.count??0}</b></div><div class="mini"><small>Radar changes</small><b>${changes}</b></div>`}
function renderMap(){const svg=$('#oppMap'),rows=D.opportunity_map||[];const W=700,H=420,pad=44;let h=`<line class="axis" x1="${pad}" y1="${H-pad}" x2="${W-pad}" y2="${H-pad}"/><line class="axis" x1="${pad}" y1="${pad}" x2="${pad}" y2="${H-pad}"/><text x="${W/2}" y="${H-8}" class="label">Conviction →</text><text x="5" y="20" class="label">Robustness ↑</text>`;
 rows.forEach(r=>{const x=pad+(Math.max(0,Math.min(100,+r.x_conviction||0))/100)*(W-pad*2);const y=H-pad-(Math.max(0,Math.min(100,+r.y_robustness||0))/100)*(H-pad*2);const rad=7+Math.max(0,Math.min(18,(+r.size_rank_score||0)/7));h+=`<a href="conviction-room.html?symbol=${encodeURIComponent(r.symbol)}"><circle class="bubble" cx="${x}" cy="${y}" r="${rad}" fill="rgba(111,137,181,.6)" stroke="currentColor"><title>${esc(r.symbol)} • conviction ${n(r.x_conviction)} • robustness ${pct(r.y_robustness)} • rank #${esc(r.rank)}</title></circle><text class="label" x="${x+rad+3}" y="${y+3}">${esc(r.symbol)}</text></a>`});svg.innerHTML=h}
function renderRadar(){const root=$('#radar');root.querySelectorAll('.radar-dot').forEach(x=>x.remove());const rows=(D.wavelength_radar||[]).slice(0,18);rows.forEach((r,i)=>{const ang=(i*137.5)*Math.PI/180;const dist=35+((r.rank||20)%10)*11;const x=165+Math.cos(ang)*dist,y=165+Math.sin(ang)*dist;const d=document.createElement('div');d.className='radar-dot';d.style.left=(x-4)+'px';d.style.top=(y-4)+'px';d.style.color=r.state==='SURGING'?'#7dd3fc':r.state==='DETERIORATING'?'#fca5a5':'#cbd5e1';d.title=`${r.symbol}: ${r.state} • rank ${r.rank}`;root.appendChild(d)});$('#radarList').innerHTML=rows.slice(0,8).map(r=>`<div class="alert"><b>${esc(r.symbol)}</b> <span class="pillx">${esc(r.state)}</span> rank #${esc(r.rank)} ${r.rank_change!=null?`• Δrank ${r.rank_change>0?'+':''}${r.rank_change}`:''} ${r.conviction_change!=null?`• Δconv ${r.conviction_change>0?'+':''}${n(r.conviction_change)}`:''}</div>`).join('')||'<div class="empty">Need a previous durable snapshot before change detection can activate.</div>'}
function setupReplay(){const snaps=D.replay_mode?.snapshots||[];const syms=[...new Set(snaps.map(x=>x.symbol).filter(Boolean))];fill('#replaySymbol',syms);function times(){const s=$('#replaySymbol').value;const q=snaps.filter(x=>x.symbol===s);$('#replayWhen').innerHTML=q.map((x,i)=>`<option value="${i}">${esc(x.observed_at||'unknown')}</option>`).join('');show()}function show(){const s=$('#replaySymbol').value;const q=snaps.filter(x=>x.symbol===s);const r=q[+$('#replayWhen').value||0];if(!r){$('#replayView').innerHTML='<div class="empty">No frozen observation.</div>';return}const o=r.outcomes||{};$('#replayView').innerHTML=`<div class="mc-three"><div class="mini"><small>What Wavelength knew</small><b>${esc(r.verdict)}</b><div>Fusion ${n(r.fusion_score)} • Technical ${n(r.technical)} • Liquidity ${n(r.liquidity)}</div></div><div class="mini"><small>Regime then</small><b>${esc(r.regime||'UNKNOWN')}</b><div>${esc(r.observed_at)}</div></div><div class="mini"><small>What happened next</small><b>24h ${o['24h']==null?'pending':n(o['24h'])+'%'}</b><div>4h ${o['4h']==null?'pending':n(o['4h'])+'%'} • 7d ${o['7d']==null?'pending':n(o['7d'])+'%'}</div></div></div><div class="card-meta" style="margin-top:10px">Frozen at the time. No look-ahead data is used to reconstruct the decision.</div>`}$('#replaySymbol').onchange=times;$('#replayWhen').onchange=show;times()}
function setupScenarios(){const rows=D.scenario_theatre||[];fill('#scenarioSymbol',rows.map(x=>x.symbol));function show(){const r=rows.find(x=>x.symbol===$('#scenarioSymbol').value);$('#scenarioView').innerHTML=(r?.scenarios||[]).map(s=>`<div class="scenario"><b>${esc(s.name)}</b> <span class="pillx">${esc(s.severity)}</span><div>${esc(s.condition)}</div><small>${esc(s.research_effect)}</small></div>`).join('')||'<div class="empty">No scenario data.</div>'}$('#scenarioSymbol').onchange=show;show()}
function renderXray(){const x=D.portfolio_xray||{};const deps=x.shared_dependencies||[];const basket=x.basket||[];$('#xrayView').innerHTML=`<div class="mc-three"><div class="mini"><small>Basket assets</small><b>${basket.length}</b></div><div class="mini"><small>Shared dependency clusters</small><b>${deps.length}</b></div><div class="mini"><small>Tail-risk model</small><b>${x.tail_risk&&Object.keys(x.tail_risk).length?'ACTIVE':'—'}</b></div></div>${deps.map(d=>`<div class="alert"><b>${esc(d.dependency)}</b> — ${d.assets.map(esc).join(', ')}</div>`).join('')||'<div class="empty" style="margin-top:10px">No multi-asset dependency cluster currently detected.</div>'}`}
function setupTimeline(){const all=D.decision_timelines||{};const syms=Object.keys(all);fill('#timelineSymbol',syms);function show(){const q=all[$('#timelineSymbol').value]||[];$('#timelineView').innerHTML=q.map(e=>`<div class="event"><b>${esc(e.verdict)}</b><div>Fusion ${n(e.fusion)}</div><small>${esc(e.at)}</small>${e.outcomes?.['24h']!=null?`<div>24h ${n(e.outcomes['24h'])}%</div>`:''}</div>`).join('')||'<div class="empty">No timeline yet.</div>'}$('#timelineSymbol').onchange=show;show()}
function renderAutopsy(){const q=(D.thesis_autopsy||[]).slice().reverse().slice(0,12);$('#autopsyView').innerHTML=q.map(r=>`<div class="alert"><b>${esc(r.symbol)}</b> • 24h ${n(r.return_24h_pct)}%<div>${(r.possible_contributors||[]).map(esc).join(' · ')}</div><small>${esc(r.observed_at)} • descriptive, not causal</small></div>`).join('')||'<div class="empty">No resolved negative 24h outcomes yet. Autopsy activates automatically as exact outcomes mature.</div>'}
function setupWhy(){const all=D.why_not_engine||{};const syms=Object.keys(all);fill('#whySymbol',syms);function show(){const q=all[$('#whySymbol').value]||[];$('#whyView').innerHTML=q.map(r=>`<div class="alert"><b>${esc(r.symbol)}</b> • rank #${esc(r.rank)} • score ${n(r.rank_score)}<div>${esc(r.reason)}</div></div>`).join('')||'<div class="empty">No alternatives.</div>'}$('#whySymbol').onchange=show;show()}
function renderHeat(){const q=D.evidence_heatmap||[];$('#heatView').innerHTML=`<table><thead><tr><th>Asset</th><th>Conviction</th><th>Rank</th><th>Data</th><th>Stability</th><th>Robustness</th><th>TF align</th><th>Gaps</th></tr></thead><tbody>${q.map(r=>`<tr><td><b>${esc(r.symbol)}</b></td><td>${cell(r.conviction)}</td><td>${cell(r.rank_score)}</td><td>${cell(r.data_quality)}</td><td>${cell(r.stability)}</td><td>${cell(r.robustness)}</td><td>${esc(r.timeframe_alignment??'—')}</td><td>${esc(r.gaps??0)}</td></tr>`).join('')}</tbody></table>`}
function renderAlerts(){const q=D.explainable_opportunity_alerts||[];$('#alertsView').innerHTML=q.map(r=>`<div class="alert"><b>${esc(r.symbol)} — ${esc(r.state)}</b><div>${esc(r.explanation)}</div><small>rank #${esc(r.current_rank)} • conviction ${n(r.current_conviction)}</small></div>`).join('')||'<div class="empty">No material rank/conviction change versus the previous durable Market Command snapshot yet.</div>'}
async function go(){try{const r=await fetch('market-command.json?'+Date.now());if(!r.ok)throw new Error('feed');D=await r.json();$('#feed').className='status-pill ok';$('#feed').innerHTML='<span class="dot"></span>LIVE';renderHero();renderMap();renderRadar();setupReplay();setupScenarios();renderXray();setupTimeline();renderAutopsy();setupWhy();renderHeat();renderAlerts()}catch(e){$('#feed').className='status-pill bad';$('#feed').innerHTML='<span class="dot"></span>UNAVAILABLE';document.querySelectorAll('.empty').forEach(x=>x.textContent='Market Command feed unavailable.')}}
go();
})();