(()=>{'use strict';
if(window.__wlNansenFlowV2)return;window.__wlNansenFlowV2=true;
const esc=s=>String(s??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=(v,d=1)=>v==null||!Number.isFinite(+v)?'—':Number(v).toLocaleString('en-US',{maximumFractionDigits:d,minimumFractionDigits:d});
const money=v=>v==null||!Number.isFinite(+v)?'—':`${+v>=0?'+':'-'}$${Math.abs(+v).toLocaleString('en-US',{maximumFractionDigits:0})}`;
async function get(){try{const r=await fetch(`nansen-flow-intelligence-v2.json?t=${Date.now()}`,{cache:'no-store'});return r.ok?await r.json():null}catch{return null}}
function style(){if(document.querySelector('#wlNansenV2Style'))return;const s=document.createElement('style');s.id='wlNansenV2Style';s.textContent='.nf2-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:10px}.nf2-tile{padding:12px;border:1px solid var(--line,#263143);border-radius:12px}.nf2-row{display:flex;justify-content:space-between;gap:10px;padding:5px 0}.nf2-pos{color:#fca5a5}.nf2-neg{color:#86efac}.nf2-conflict{color:#fcd34d}.nf2-muted{opacity:.7;font-size:12px}.nf2-explain{margin-top:8px;line-height:1.45}';document.head.appendChild(s)}
function tile(x){const cls=+x.latest_netflow_usd>0?'nf2-pos':+x.latest_netflow_usd<0?'nf2-neg':'';return `<div class="nf2-tile"><div class="nf2-row"><strong>${esc(x.symbol)}</strong><b class="${cls}">${money(x.latest_netflow_usd)}</b></div><div class="nf2-row"><span>History</span><span>${x.history_n||0} observations</span></div><div class="nf2-row"><span>Change</span><span>${money(x.netflow_change_usd)}</span></div><div class="nf2-row"><span>Reversal</span><span>${x.direction_reversal?'YES':'NO'}</span></div><div class="nf2-row"><span>Magnitude percentile</span><span>${n(x.absolute_magnitude_percentile)}%</span></div><div class="nf2-row"><span>Extreme state</span><span>${esc(x.extreme_state)}</span></div><div class="nf2-row"><span>Flow / conviction</span><span class="${x.flow_conviction_conflict!=='NONE'?'nf2-conflict':''}">${esc(x.flow_conviction_conflict)}</span></div><div class="nf2-explain nf2-muted">${esc(x.explanation)}</div></div>`}
function renderDataTruth(d){const flow=document.querySelector('#flows')?.closest('.card');if(!flow||document.querySelector('#nansenFlowV2'))return;const sec=document.createElement('section');sec.id='nansenFlowV2';sec.className='card';const u=d.forward_usefulness||{},c=d.coverage||{};sec.innerHTML=`<div class="card-title">Nansen Exchange Flow Intelligence v2</div><div class="card-meta">Direct flow history → acceleration/reversal → own-history percentiles → conviction conflicts → forward 24h usefulness. Descriptive research only.</div><div class="nf2-grid" style="margin-top:12px"><div class="nf2-tile"><strong>Evidence maturity</strong><div class="nf2-row"><span>Direct assets now</span><span>${c.current_direct_assets||0}</span></div><div class="nf2-row"><span>Historical assets</span><span>${c.historical_assets||0}</span></div><div class="nf2-row"><span>Resolved 24h cases</span><span>${u.resolved_n||0}/${u.minimum_required||20}</span></div><div class="nf2-row"><span>Usefulness</span><span>${esc(u.status)}</span></div><div class="nf2-muted">No retrospective backfill. Flow influence must be earned from prospective outcomes.</div></div>${(d.assets||[]).map(tile).join('')}</div>`;flow.insertAdjacentElement('afterend',sec)}
function renderCoin(d){const page=(location.pathname.split('/').pop()||'').toLowerCase();if(!['asset.html','coin.html'].includes(page)||document.querySelector('#nansenCoinFlow'))return;const p=new URLSearchParams(location.search),sym=(p.get('symbol')||p.get('s')||'').toUpperCase();if(!sym)return;const x=(d.assets||[]).find(a=>String(a.symbol).toUpperCase()===sym);if(!x)return;const root=document.querySelector('.page');if(!root)return;const sec=document.createElement('section');sec.id='nansenCoinFlow';sec.className='card';sec.innerHTML=`<div class="card-head"><div><div class="card-title">Nansen Exchange Flow v2</div><div class="card-meta">SEMANTIC_DIRECT labelled exchange-flow context • ${esc(x.source_observation_at)}</div></div></div><div class="nf2-grid">${tile(x)}<div class="nf2-tile"><strong>Forward evidence</strong><div class="nf2-row"><span>Resolved 24h</span><span>${x.resolved_forward_24h_n||0}</span></div><div class="nf2-row"><span>Median later return</span><span>${x.median_forward_24h_pct==null?'—':n(x.median_forward_24h_pct,2)+'%'}</span></div><div class="nf2-muted">Positive netflow is potential exchange inflow/sell-pressure context; negative netflow is potential outflow/accumulation context. Neither is automatic buy/sell permission.</div></div></div>`;root.appendChild(sec)}
async function init(){style();const d=await get();if(!d)return;renderDataTruth(d);renderCoin(d)}
if(document.readyState==='loading')window.addEventListener('DOMContentLoaded',init);else init();
})();
