(()=>{'use strict';
const $=s=>document.querySelector(s),n=(v,d=1)=>v==null||!Number.isFinite(+v)?'—':(+v).toLocaleString('en-GB',{minimumFractionDigits:d,maximumFractionDigits:d}),pct=v=>v==null||!Number.isFinite(+v)?'—':`${+v>=0?'+':''}${n(v,1)}%`,esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function get(url){const r=await fetch(url);if(!r.ok)throw new Error(`${r.status} ${url}`);return r.json()}
function open(sym){location.href=`coin.html?symbol=${encodeURIComponent(sym)}`}
function card(o,copy,kind=''){return `<div class="intel-row" data-symbol="${esc(o.symbol)}"><div class="intel-rank ${kind}">${esc(o.symbol)}</div><div class="intel-main"><div class="intel-title">${esc(o.symbol)} <span class="badge">${n(o.canonical_score??o.score,0)}</span></div><div class="intel-copy">${copy}</div></div></div>`}
function bind(){document.querySelectorAll('[data-symbol]').forEach(el=>el.onclick=()=>open(el.dataset.symbol))}
function renderList(sel,arr,fn,empty='No current candidates in this bucket.'){const el=$(sel);el.innerHTML=arr.length?arr.slice(0,8).map(o=>card(o,fn(o))).join(''):`<div class="empty">${empty}</div>`;bind()}
async function loadFunding(markets){const out=[];await Promise.all(markets.slice(0,16).map(async o=>{try{const p=await get(`https://fapi.binance.com/fapi/v1/premiumIndex?symbol=${encodeURIComponent(o.symbol+'USDT')}`);out.push({...o,funding:+p.lastFundingRate})}catch{}}));return out.sort((a,b)=>Math.abs(b.funding)-Math.abs(a.funding))}
async function load(){try{$('#ocStatus').className='status-pill warn';$('#ocStatus').innerHTML='<span class="dot"></span>SCANNING';const d=await get(`opportunity-radar.json?t=${Date.now()}`),ops=Array.isArray(d.opportunities)?d.opportunities:[];const near=ops.filter(o=>o.ema20_above_ema80&&o.rsi>=50&&o.rsi<=75&&o.adx>=28&&o.adx<35).sort((a,b)=>b.adx-a.adx),trends=ops.filter(o=>o.ema20_above_ema80&&o.rsi>=50&&o.rsi<=70&&o.adx>=20&&o.adx<35).sort((a,b)=>b.canonical_score-a.canonical_score),rs=[...ops].filter(o=>Number.isFinite(+o.canonical_vs_btc_30d_pct)).sort((a,b)=>b.canonical_vs_btc_30d_pct-a.canonical_vs_btc_30d_pct),vol=[...ops].filter(o=>(+o.canonical_atr_pct>=3)||Math.abs(+o.change_24h)>=7).sort((a,b)=>Math.max(+b.canonical_atr_pct,Math.abs(+b.change_24h))-Math.max(+a.canonical_atr_pct,Math.abs(+a.change_24h))),weak=ops.filter(o=>!o.ema20_above_ema80||+o.rsi<50||+o.adx<20||+o.change_24h<-2).sort((a,b)=>(+a.canonical_score)-(+b.canonical_score));
$('#pulseMeta').textContent=`${ops.length} radar candidates · generated ${d.generated_at?new Date(d.generated_at).toLocaleString():'—'} · ${d.canonical_score_model||'Wavelength intelligence'}`;$('#pulseBadge').textContent='RESEARCH ONLY';$('#pulseBadge').className='badge good';$('#pulseMetrics').innerHTML=[['Radar candidates',ops.length],['Near confirmation',near.length],['RS leaders',rs.filter(o=>+o.canonical_vs_btc_30d_pct>10).length],['Vol expansion',vol.length]].map(x=>`<div class="metric"><div class="metric-label">${x[0]}</div><div class="metric-value">${x[1]}</div></div>`).join('');
renderList('#nearList',near,o=>`ADX ${n(o.adx,1)} is approaching 35 with RSI ${n(o.rsi,1)} and fast trend structure already positive. Research context only.`);renderList('#trendList',trends,o=>`Canonical intelligence ${n(o.canonical_score,0)}/100 · ADX ${n(o.adx,1)} · RSI ${n(o.rsi,1)} · 24h ${pct(o.change_24h)}.`);renderList('#rsList',rs.filter(o=>+o.canonical_vs_btc_30d_pct>0),o=>`${pct(o.canonical_vs_btc_30d_pct)} versus BTC over 30d · canonical score ${n(o.canonical_score,0)}/100.`);renderList('#volList',vol,o=>`Canonical ATR ${n(o.canonical_atr_pct,2)}% · 24h move ${pct(o.change_24h)}. Expansion is context, not direction.`);renderList('#weakList',weak,o=>`RSI ${n(o.rsi,1)} · ADX ${n(o.adx,1)} · 24h ${pct(o.change_24h)} · fast-above-slow ${o.ema20_above_ema80?'yes':'no'}.`);
$('#allBody').innerHTML=ops.length?ops.map(o=>`<tr class="market-row" data-symbol="${esc(o.symbol)}"><td class="left"><strong>${esc(o.symbol)}</strong></td><td>${n(o.canonical_score,0)}</td><td>${n(o.radar_score??o.score,0)}</td><td>${esc(o.stage)}</td><td>${n(o.rsi,1)}</td><td>${n(o.adx,1)}</td><td class="${+o.canonical_vs_btc_30d_pct>0?'up':+o.canonical_vs_btc_30d_pct<0?'down':''}">${pct(o.canonical_vs_btc_30d_pct)}</td><td>${n(o.canonical_atr_pct,2)}%</td><td class="${+o.change_24h>0?'up':+o.change_24h<0?'down':''}">${pct(o.change_24h)}</td></tr>`).join(''):'<tr><td colspan="9" class="empty">No radar candidates.</td></tr>';bind();
const funding=await loadFunding(ops);const extremes=funding.filter(o=>Math.abs(o.funding)>=0.0003);$('#crowdingBadge').textContent=extremes.length?'EXTREMES FOUND':'BALANCED';$('#crowdingBadge').className='badge '+(extremes.length?'warn':'good');renderList('#crowdingList',extremes,o=>`${o.funding>=0?'Positive':'Negative'} funding ${n(o.funding*100,4)}% · 24h ${pct(o.change_24h)}. Descriptive positioning signal only.`,'No material funding extremes among currently ranked radar markets.');$('#ocStatus').className='status-pill';$('#ocStatus').innerHTML='<span class="dot"></span>LIVE RESEARCH'}catch(e){console.error(e);$('#ocStatus').className='status-pill bad';$('#ocStatus').innerHTML='<span class="dot"></span>DATA ERROR';document.querySelectorAll('.intel-list').forEach(el=>el.innerHTML='<div class="empty">Opportunity data unavailable.</div>')}}
load();setInterval(load,60000);
})();