(()=>{
'use strict';
const $=s=>document.querySelector(s);const n=(v,d=2)=>v==null||!Number.isFinite(+v)?'—':(+v).toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d});const money=v=>v==null||!Number.isFinite(+v)?'—':'$'+(+v).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});const signedMoney=v=>v==null||!Number.isFinite(+v)?'—':`${+v>=0?'+':'-'}$${Math.abs(+v).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}`;const pct=v=>v==null||!Number.isFinite(+v)?'—':`${+v>=0?'+':''}${n(v,2)}%`;const cls=v=>+v>0?'up':+v<0?'down':'neutral';const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function metric(label,value,c=''){return `<div class="metric"><div class="metric-label">${esc(label)}</div><div class="metric-value ${c}">${value}</div></div>`}
async function load(){try{const r=await fetch(`paper-portfolio.json?t=${Date.now()}`);if(!r.ok)throw new Error(r.status);const d=await r.json();render(d)}catch(e){console.error(e);$('#paperStatus').className='status-pill bad';$('#paperStatus').innerHTML='<span class="dot"></span>FEED ERROR'}}
function render(d){$('#paperStatus').className='status-pill';$('#paperStatus').innerHTML='<span class="dot"></span>PAPER LIVE';$('#paperEquity').textContent=money(d.paper_equity);$('#paperReturn').innerHTML=`Total paper return <strong class="${cls(d.total_return_pct)}">${pct(d.total_return_pct)}</strong> · starting ${money(d.paper_starting_equity)} · ${esc(d.market_regime||'—')}`;
const w=d.weekly||{};$('#weeklyBadge').textContent=w.return_pct==null?'BUILDING':w.return_pct>=0?'POSITIVE WEEK':'NEGATIVE WEEK';$('#weeklyBadge').className='badge '+(w.return_pct==null?'warn':w.return_pct>=0?'good':'bad');$('#weeklyMetrics').innerHTML=[metric('7d P&L',w.pnl==null?'—':money(w.pnl),cls(w.pnl)),metric('7d return',pct(w.return_pct),cls(w.return_pct)),metric('Closed trades',w.closed_trades??0),metric('Win rate',w.win_rate==null?'—':n(w.win_rate,1)+'%'),metric('Profit factor',w.profit_factor==null?'—':n(w.profit_factor,2)),metric('Max drawdown',pct(w.max_drawdown_pct),cls(w.max_drawdown_pct)),metric('Fees',w.fees==null?'—':money(w.fees)),metric('No-trade scans',w.no_trade_scans??0)].join('');
const s=d.last_scan||{};$('#scanMetrics').innerHTML=[metric('Markets scanned',d.scanned_markets??0),metric('Universe cap',d.universe_cap??'—'),metric('Qualified',s.qualified??0),metric('Entries',s.entries??0),metric('Exits',s.exits??0),metric('Open positions',(d.open_positions||[]).length),metric('Cash',money(d.cash)),metric('Generated',d.generated_at?new Date(d.generated_at).toLocaleString():'—')].join('');
const open=d.open_positions||[];$('#openBody').innerHTML=open.length?open.map(p=>`<tr><td class="left"><a href="coin.html?symbol=${encodeURIComponent(p.symbol)}">${esc(p.symbol)}</a></td><td>${n(p.quantity,6)}</td><td>${money(p.entry)}</td><td>${money(p.entry_value)}</td><td>${money(p.current)}</td><td>${money(p.current_value)}</td><td class="${cls(p.unrealized_pnl)}"><strong>${signedMoney(p.unrealized_pnl)}</strong></td><td class="${cls(p.unrealized_net_pct)}">${pct(p.unrealized_net_pct)}</td><td>${money(p.estimated_round_trip_fees)}</td><td>${money(p.stop)}</td><td>${n((p.age_hours||0)/24,1)}d</td><td>${p.intel??'—'}</td><td class="${cls(p.vs_btc30)}">${pct(p.vs_btc30)}</td></tr>`).join(''):'<tr><td colspan="13" class="empty">No open paper positions. Wavelength will wait rather than force a trade.</td></tr>';
const closed=(d.recent_closed_trades||[]).slice().reverse();$('#closedBody').innerHTML=closed.length?closed.map(t=>`<tr><td class="left"><a href="coin.html?symbol=${encodeURIComponent(t.symbol)}">${esc(t.symbol)}</a></td><td>${esc((t.reason||'—').replaceAll('_',' '))}</td><td class="${cls(t.pnl)}">${signedMoney(t.pnl)}</td><td class="${cls(t.pnl_pct)}">${pct(t.pnl_pct)}</td><td>${money(t.entry)}</td><td>${money(t.exit)}</td><td>${t.intel??'—'}</td><td>${esc(t.regime||'—')}</td></tr>`).join(''):'<tr><td colspan="8" class="empty">No closed paper trades yet.</td></tr>';
const q=d.rules||{};$('#rules').innerHTML=[['Risk per trade',`${n(q.risk_per_trade_pct,2)}% of paper equity`],['Max simultaneous positions',q.max_positions??'—'],['Position cap',`${n(q.max_notional_per_position_pct,1)}% of equity`],['Protective stop',`${n(q.stop_atr_multiple,1)}× ATR`],['Maximum hold',`${n(q.max_hold_days,1)} days`],['Fees + slippage',`${n(q.fee_per_side_pct,2)}% fee + ${n(q.slippage_per_side_pct,2)}% slippage per side`],['Minimum Intelligence',q.minimum_intelligence_score??'—'],['Max pair correlation',q.max_pair_correlation==null?'—':n(q.max_pair_correlation,2)],['Daily trade quota',q.forced_daily_trade?'FORCED':'NONE · no-trade is allowed']].map(x=>`<div class="analysis-row"><span class="analysis-label">${esc(x[0])}</span><strong>${esc(x[1])}</strong></div>`).join('')}
load();setInterval(load,60000);
})();
