(()=>{
'use strict';
const $=s=>document.querySelector(s);const n=(v,d=2)=>v==null||!Number.isFinite(+v)?'—':(+v).toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d});const money=v=>v==null||!Number.isFinite(+v)?'—':'$'+(+v).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});const signedMoney=v=>v==null||!Number.isFinite(+v)?'—':`${+v>=0?'+':'-'}$${Math.abs(+v).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}`;const pct=v=>v==null||!Number.isFinite(+v)?'—':`${+v>=0?'+':''}${n(v,2)}%`;const cls=v=>+v>0?'up':+v<0?'down':'neutral';const esc=s=>String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
const PRICE_API='https://data-api.binance.vision/api/v3/ticker/price';let snapshot=null,accounting=null,liveAt=null,liveBusy=false;
function metric(label,value,c=''){return `<div class="metric"><div class="metric-label">${esc(label)}</div><div class="metric-value ${c}">${value}</div></div>`}
async function load(){try{const [pr,ar]=await Promise.all([fetch(`paper-portfolio.json?t=${Date.now()}`),fetch(`paper-accounting.json?t=${Date.now()}`).catch(()=>null)]);if(!pr.ok)throw new Error(pr.status);snapshot=await pr.json();if(ar&&ar.ok)accounting=await ar.json();render(snapshot)}catch(e){console.error(e);$('#paperStatus').className='status-pill bad';$('#paperStatus').innerHTML='<span class="dot"></span>FEED ERROR'}}
async function livePrice(symbol){const r=await fetch(`${PRICE_API}?symbol=${encodeURIComponent(symbol+'USDT')}`,{cache:'no-store'});if(!r.ok)throw new Error(`price ${symbol} ${r.status}`);const d=await r.json();const px=+d.price;if(!Number.isFinite(px))throw new Error(`bad price ${symbol}`);return px}
function withLivePrices(d,prices){const fee=(+d.rules?.fee_per_side_pct||0)/100,slip=(+d.rules?.slippage_per_side_pct||0)/100;const x=structuredClone(d);x.open_positions=(x.open_positions||[]).map(p=>{const market=prices[p.symbol];if(!Number.isFinite(market))return p;const qty=+p.quantity||0,entryValue=Number.isFinite(+p.entry_value)?+p.entry_value:qty*(+p.entry||0),entryFee=Number.isFinite(+p.entry_fee)?+p.entry_fee:entryValue*fee;const currentValue=qty*market,exitExec=market*(1-slip),exitGross=qty*exitExec,exitFee=exitGross*fee,pnl=exitGross-exitFee-entryValue-entryFee;return {...p,current:market,current_value:currentValue,estimated_exit_fee:exitFee,estimated_round_trip_fees:entryFee+exitFee,unrealized_pnl:pnl,unrealized_pct:(market/(+p.entry)-1)*100,unrealized_net_pct:(entryValue+entryFee)>0?pnl/(entryValue+entryFee)*100:null}});x.paper_equity=(+x.cash||0)+x.open_positions.reduce((a,p)=>a+(+p.current_value||0),0);x.total_return_pct=(+x.paper_starting_equity||0)>0?(x.paper_equity/(+x.paper_starting_equity)-1)*100:x.total_return_pct;return x}
async function markToMarket(){if(liveBusy||!snapshot||(snapshot.open_positions||[]).length===0)return;liveBusy=true;try{const pairs=await Promise.all((snapshot.open_positions||[]).map(async p=>[p.symbol,await livePrice(p.symbol)]));liveAt=new Date();render(withLivePrices(snapshot,Object.fromEntries(pairs)),true)}catch(e){console.warn('Live mark-to-market fallback to server snapshot',e)}finally{liveBusy=false}}
function realisedPnl(d){if(accounting&&Number.isFinite(+accounting.lifetime_realized_pnl))return +accounting.lifetime_realized_pnl;const total=+d.closed_trades_total||0,rows=d.recent_closed_trades||[];if(total===0)return 0;if(rows.length===total&&rows.every(t=>Number.isFinite(+t.pnl)))return rows.reduce((a,t)=>a+(+t.pnl||0),0);return null}
function render(d,isLive=false){$('#paperStatus').className='status-pill';$('#paperStatus').innerHTML=`<span class="dot"></span>${isLive?'LIVE P&L · 10S':'PAPER LIVE'}`;$('#paperEquity').textContent=money(d.paper_equity);const since=accounting?.paper_started_at?` · since ${new Date(accounting.paper_started_at).toLocaleDateString()}`:'';$('#paperReturn').innerHTML=`Total paper return <strong class="${cls(d.total_return_pct)}">${pct(d.total_return_pct)}</strong> · starting ${money(d.paper_starting_equity)} · ${esc(d.market_regime||'—')}${since}${isLive&&liveAt?` · live ${liveAt.toLocaleTimeString()}`:''}`;
const w=d.weekly||{},start=+d.paper_starting_equity||0,totalPnl=Number.isFinite(+d.paper_equity)?+d.paper_equity-start:null,open=d.open_positions||[],openNet=open.reduce((a,p)=>a+(Number.isFinite(+p.unrealized_pnl)?+p.unrealized_pnl:0),0),exitFees=open.reduce((a,p)=>a+(Number.isFinite(+p.estimated_exit_fee)?+p.estimated_exit_fee:0),0),realised=realisedPnl(d),feesPaid=Number.isFinite(+d.fees_paid_total)?+d.fees_paid_total:null,lifetimeClosed=accounting?.lifetime_closed_trades??d.closed_trades_total??0;$('#weeklyBadge').textContent=totalPnl==null?'BUILDING':totalPnl>=0?'PORTFOLIO POSITIVE':'PORTFOLIO NEGATIVE';$('#weeklyBadge').className='badge '+(totalPnl==null?'warn':totalPnl>=0?'good':'bad');$('#weeklyMetrics').innerHTML=[metric('Total P&L vs $10k',totalPnl==null?'—':signedMoney(totalPnl),cls(totalPnl)),metric('Total return',pct(d.total_return_pct),cls(d.total_return_pct)),metric('7d change',w.pnl==null?'—':signedMoney(w.pnl),cls(w.pnl)),metric('7d return',pct(w.return_pct),cls(w.return_pct)),metric('Lifetime realised P&L',realised==null?'—':signedMoney(realised),cls(realised)),metric(isLive?'Live open net P&L':'Open net P&L',signedMoney(openNet),cls(openNet)),metric('Fees paid',feesPaid==null?'—':money(feesPaid)),metric('Est. exit fees',money(exitFees)),metric('Lifetime closed trades',lifetimeClosed),metric('Win rate',w.win_rate==null?'—':n(w.win_rate,1)+'%'),metric('Profit factor',w.profit_factor==null?'—':n(w.profit_factor,2)),metric('Max drawdown',pct(w.max_drawdown_pct),cls(w.max_drawdown_pct))].join('');
const s=d.last_scan||{};$('#scanMetrics').innerHTML=[metric('Markets scanned',d.scanned_markets??0),metric('Universe cap',d.universe_cap??'—'),metric('Qualified',s.qualified??0),metric('Entries',s.entries??0),metric('Exits',s.exits??0),metric('Open positions',open.length),metric('Cash',money(d.cash)),metric(isLive?'Live priced':'Generated',isLive&&liveAt?liveAt.toLocaleTimeString():d.generated_at?new Date(d.generated_at).toLocaleString():'—')].join('');
$('#openBody').innerHTML=open.length?open.map(p=>`<tr><td class="left"><a href="coin.html?symbol=${encodeURIComponent(p.symbol)}">${esc(p.symbol)}</a></td><td>${n(p.quantity,6)}</td><td>${money(p.entry)}</td><td>${money(p.entry_value)}</td><td>${money(p.current)}</td><td>${money(p.current_value)}</td><td class="${cls(p.unrealized_pnl)}"><strong>${signedMoney(p.unrealized_pnl)}</strong></td><td class="${cls(p.unrealized_net_pct)}">${pct(p.unrealized_net_pct)}</td><td>${money(p.estimated_round_trip_fees)}</td><td>${money(p.stop)}</td><td>${n((p.age_hours||0)/24,1)}d</td><td>${p.intel??'—'}</td><td class="${cls(p.vs_btc30)}">${pct(p.vs_btc30)}</td></tr>`).join(''):'<tr><td colspan="13" class="empty">No open paper positions. Wavelength will wait rather than force a trade.</td></tr>';
const closed=(d.recent_closed_trades||[]).slice().reverse();$('#closedBody').innerHTML=closed.length?closed.map(t=>`<tr><td class="left"><a href="coin.html?symbol=${encodeURIComponent(t.symbol)}">${esc(t.symbol)}</a></td><td>${esc((t.reason||'—').replaceAll('_',' '))}</td><td class="${cls(t.pnl)}">${signedMoney(t.pnl)}</td><td class="${cls(t.pnl_pct)}">${pct(t.pnl_pct)}</td><td>${money(t.entry)}</td><td>${money(t.exit)}</td><td>${t.intel??'—'}</td><td>${esc(t.regime||'—')}</td></tr>`).join(''):'<tr><td colspan="8" class="empty">No closed paper trades yet.</td></tr>';
const q=d.rules||{};$('#rules').innerHTML=[['Risk per trade',`${n(q.risk_per_trade_pct,2)}% of paper equity`],['Max simultaneous positions',q.max_positions??'—'],['Position cap',`${n(q.max_notional_per_position_pct,1)}% of equity`],['Protective stop',`${n(q.stop_atr_multiple,1)}× ATR`],['Maximum hold',`${n(q.max_hold_days,1)} days`],['Fees + slippage',`${n(q.fee_per_side_pct,2)}% fee + ${n(q.slippage_per_side_pct,2)}% slippage per side`],['Minimum Intelligence',q.minimum_intelligence_score??'—'],['Max pair correlation',q.max_pair_correlation==null?'—':n(q.max_pair_correlation,2)],['Daily trade quota',q.forced_daily_trade?'FORCED':'NONE · no-trade is allowed']].map(x=>`<div class="analysis-row"><span class="analysis-label">${esc(x[0])}</span><strong>${esc(x[1])}</strong></div>`).join('')}
load().then(markToMarket);setInterval(load,60000);setInterval(markToMarket,10000);
})();
