(()=>{'use strict';
const GENERATED_KEYS=['generated_at','updated_at'];const OBSERVED_KEYS=['observed_at','recorded_at','as_of','timestamp'];
const get=(o,p)=>String(p||'').split('.').reduce((v,k)=>v==null?null:v[k],o);const validTs=v=>v&&Number.isFinite(Date.parse(v));
const firstTs=(o,paths,keys)=>{for(const p of paths||[]){const v=get(o,p);if(validTs(v))return v}for(const k of keys){const v=o?.[k];if(validTs(v))return v}return null};
const ageMin=(ts,now)=>validTs(ts)?Math.max(0,(now-Date.parse(ts))/60000):null;const isEvent=s=>String(s?.cadence||'').startsWith('EVENT_DRIVEN');
const truthyConflict=d=>{for(const k of ['conflict','data_conflict','source_conflict','source_disagreement','evidence_conflict']){const v=d?.[k];if(v===true||String(v||'').toUpperCase()==='CONFLICT')return `${k} reported`}for(const k of ['state','status','data_state','evidence_state','consensus_state']){if(/CONFLICT|DISAGREE/i.test(String(d?.[k]||'')))return `${k}: ${d[k]}`}return null};
function directState(s,d,now,hb,policy){const generated=firstTs(d,s.generated_at_paths,GENERATED_KEYS),observed=firstTs(d,s.observed_at_paths,OBSERVED_KEYS),eventBasis=observed||generated,eventAge=ageMin(eventBasis,now),conflict=truthyConflict(d);if(isEvent(s)){const heartbeat=hb?.checked_at,heartbeatAge=ageMin(heartbeat,now),hmax=Math.max(1,Number(policy?.event_driven_heartbeat_max_age_minutes||150));let state=conflict?'CONFLICT':!hb||hb.available_and_parseable!==true?'DEGRADED':heartbeatAge==null?'DEGRADED':heartbeatAge>hmax?'STALE':heartbeatAge>=hmax*.75?'AGING':(eventAge!=null&&eventAge>Number(s.max_age_minutes||0)?'CURRENT_NO_NEW_EVENT':'FRESH');return {generated_at:generated,observed_at:observed,effective_timestamp:heartbeat||eventBasis,age_minutes:heartbeatAge,event_age_minutes:eventAge,heartbeat_at:heartbeat,heartbeat_age_minutes:heartbeatAge,direct_state:state,conflict_reason:conflict,no_timestamp:heartbeatAge==null,event_driven:true}}
const basis=eventBasis,age=eventAge,max=Math.max(1,Number(s.max_age_minutes||0)),agingAt=max*.75;let state=conflict?'CONFLICT':age==null?'DEGRADED':age>max?'STALE':age>=agingAt?'AGING':'FRESH';return {generated_at:generated,observed_at:observed,effective_timestamp:basis,age_minutes:age,event_age_minutes:age,heartbeat_at:null,heartbeat_age_minutes:null,direct_state:state,conflict_reason:conflict,no_timestamp:age==null,event_driven:false}}
async function inspect(){const m=await fetch(`source-manifest.json?t=${Date.now()}`,{cache:'no-store'}).then(r=>{if(!r.ok)throw Error(r.status);return r.json()});const now=Date.now(),defs=m.sources||[],rows={},policy=m.freshness_policy||{};let hbMap={};const hbPath=policy.event_driven_heartbeat_path;if(hbPath){try{const hr=await fetch(`${hbPath}?t=${Date.now()}`,{cache:'no-store'});if(hr.ok){const h=await hr.json();hbMap=Object.fromEntries((h.sources||[]).map(x=>[x.id,x]))}}catch{}}
await Promise.all(defs.map(async s=>{try{const r=await fetch(`${s.path}?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error(r.status);const d=await r.json();rows[s.id]={...s,available:true,...directState(s,d,now,hbMap[s.id],policy)}}catch(e){rows[s.id]={...s,available:false,generated_at:null,observed_at:null,effective_timestamp:null,age_minutes:null,event_age_minutes:null,heartbeat_at:hbMap[s.id]?.checked_at||null,heartbeat_age_minutes:ageMin(hbMap[s.id]?.checked_at,now),direct_state:'MISSING',conflict_reason:null,no_timestamp:false,error:String(e)}}}));
const resolving=new Set();function resolve(id){const r=rows[id];if(!r)return null;if(r.effective_state)return r;if(resolving.has(id)){r.effective_state='CONFLICT';r.reasons=['Dependency cycle detected'];return r}resolving.add(id);const deps=(r.dependencies||[]).map(resolve).filter(Boolean),reasons=[];let state=r.direct_state;for(const d of deps){if(d.effective_state==='CONFLICT'){state='CONFLICT';reasons.push(`Upstream ${d.label}: CONFLICT`)}else if(d.effective_state==='MISSING'){if(state!=='CONFLICT')state='DEGRADED';reasons.push(`Upstream ${d.label}: MISSING`)}else if(['STALE','DEGRADED'].includes(d.effective_state)){if(!['CONFLICT','MISSING','STALE'].includes(state))state='DEGRADED';reasons.push(`Upstream ${d.label}: ${d.effective_state}`)}else if(d.effective_state==='AGING'&&['FRESH','CURRENT_NO_NEW_EVENT'].includes(state)){state='AGING';reasons.push(`Upstream ${d.label}: AGING`)}}
if(r.direct_state==='STALE'){state='STALE';reasons.unshift(r.event_driven?`Event-driven source heartbeat breached ${policy.event_driven_heartbeat_max_age_minutes||150}m SLA`:`Scheduled/source freshness SLA breached: ${r.max_age_minutes}m limit`)}if(r.direct_state==='CURRENT_NO_NEW_EVENT')reasons.unshift(`Collector checked recently; no substantive event within ${r.max_age_minutes}m event window`);if(r.direct_state==='MISSING')state='MISSING';if(r.direct_state==='CONFLICT')state='CONFLICT';if(r.direct_state==='AGING')reasons.unshift(r.event_driven?'Event-driven collector heartbeat is approaching its freshness limit':`Evidence is approaching its ${r.max_age_minutes}m freshness limit`);if(r.no_timestamp)reasons.unshift(r.event_driven?'No usable collector heartbeat':'Artifact is available but exposes no usable observation or generation timestamp');if(r.conflict_reason)reasons.unshift(r.conflict_reason);r.effective_state=state;r.fresh=['FRESH','CURRENT_NO_NEW_EVENT'].includes(state);r.reasons=reasons;r.upstreams=deps.map(d=>({id:d.id,label:d.label,state:d.effective_state,age_minutes:d.age_minutes,path:d.path}));resolving.delete(id);return r}
defs.forEach(s=>resolve(s.id));function lineage(id,seen=new Set()){if(seen.has(id)||!rows[id])return[];seen.add(id);const r=rows[id];return [{id:r.id,label:r.label,path:r.path,state:r.effective_state,generated_at:r.generated_at,observed_at:r.observed_at,age_minutes:r.age_minutes,event_age_minutes:r.event_age_minutes,heartbeat_at:r.heartbeat_at,criticality:r.criticality},...(r.dependencies||[]).flatMap(d=>lineage(d,seen))]}return {manifest:m,rows:defs.map(s=>({...rows[s.id],lineage:lineage(s.id)})),checked_at:new Date(now).toISOString()}}
function primary(rows){const p=rows.filter(x=>String(x.criticality||'PRIMARY').toUpperCase()==='PRIMARY');return p.length?p:rows}
function status(rows){const active=primary(rows);if(!active.length)return'UNKNOWN';const states=active.map(x=>x.effective_state);if(states.includes('CONFLICT'))return'CONFLICT';if(states.includes('MISSING'))return'MISSING DATA';if(states.includes('STALE'))return'STALE DATA';if(states.includes('DEGRADED'))return'DEGRADED';if(states.includes('AGING'))return'AGING DATA';if(states.includes('CURRENT_NO_NEW_EVENT'))return'CURRENT · NO NEW EVENT';return'FRESH'}
async function badge(){const top=document.querySelector('.topbar');if(!top||document.querySelector('#wlProvenanceBadge'))return;const a=document.createElement('a');a.id='wlProvenanceBadge';a.href='provenance.html';a.className='status-pill warn';a.innerHTML='<span class="dot"></span>DATA CHECK';top.appendChild(a);try{const x=await inspect(),s=status(x.rows),active=primary(x.rows),affected=active.filter(r=>!['FRESH','CURRENT_NO_NEW_EVENT'].includes(r.effective_state)),advisory=x.rows.filter(r=>String(r.criticality||'PRIMARY').toUpperCase()==='ADVISORY'&&!['FRESH','CURRENT_NO_NEW_EVENT'].includes(r.effective_state));a.className=`status-pill ${['FRESH','CURRENT · NO NEW EVENT'].includes(s)?'':['AGING DATA','STALE DATA','DEGRADED'].includes(s)?'warn':'bad'}`;a.innerHTML=`<span class="dot"></span>${s}`;a.title=affected.length===0?`Primary continuity feeds current${advisory.length?` · ${advisory.length} advisory/legacy source(s) degraded or stale`:''}`:`${affected.length} primary source(s) affected · click for transitive provenance`}catch(e){a.className='status-pill bad';a.innerHTML='<span class="dot"></span>SOURCE UNKNOWN'}}window.WavelengthProvenance={inspect,status,primary};if(document.readyState==='loading')window.addEventListener('DOMContentLoaded',badge);else badge();})();