(()=>{
'use strict';
const API='https://data-api.binance.vision';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=(v,d=2)=>Number.isFinite(+v)?(+v).toFixed(d):'—';
const pct=v=>Number.isFinite(+v)?`${+v>=0?'+':''}${(+v).toFixed(2)}%`:'—';
const cls=v=>+v>0?'up':+v<0?'down':'neutral';
const load=(k,d=[])=>{try{return JSON.parse(localStorage.getItem(k)||'null')??d}catch{return d}};
const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
async function j(u){const r=await fetch(`${u}${u.includes('?')?'&':'?'}t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`${u} ${r.status}`);return r.json()}
const style=document.createElement('style');style.textContent=`
.radarx-shell{display:grid;gap:16px;margin:18px 0}.radarx-grid2{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.radarx-card{border:1px solid var(--border,#24303a);border-radius:16px;padding:18px;background:rgba(255,255,255,.012)}.radarx-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;margin-bottom:14px}.radarx-title{font:700 18px 'Bricolage Grotesque',sans-serif}.radarx-meta{font:500 12px 'IBM Plex Mono',monospace;opacity:.62;margin-top:3px}.radarx-row{display:grid;grid-template-columns:110px 1fr auto;gap:10px;align-items:center;padding:9px 0;border-bottom:1px solid rgba(255,255,255,.06)}.radarx-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.radarx-kpi{padding:12px;border-radius:12px;background:rgba(255,255,255,.025)}.radarx-kpi b{display:block;font:700 20px 'IBM Plex Mono',monospace;margin-top:5px}.radarx-spark{height:84px;margin-top:8px}.radarx-spark svg{width:100%;height:100%}.radarx-pill{display:inline-block;border:1px solid currentColor;border-radius:999px;padding:4px 8px;font:700 11px 'IBM Plex Mono',monospace}.radarx-block{padding:10px 0;border-bottom:1px solid rgba(255,255,255,.06)}.radarx-select{max-width:190px}.radarx-summary{font-size:15px;line-height:1.55}.radarx-bar{height:8px;border-radius:99px;background:rgba(255,255,255,.07);overflow:hidden}.radarx-bar i{display:block;height:100%;background:currentColor}.radarx-table{width:100%;border-collapse:collapse}.radarx-table td,.radarx-table th{padding:8px 6px;border-bottom:1px solid rgba(255,255,255,.06);text-align:right}.radarx-table th:first-child,.radarx-table td:first-child{text-align:left}@media(max-width:900px){.radarx-grid2,.radarx-kpis{grid-template-columns:1fr}.radarx-row{grid-template-columns:90px 1fr}.radarx-row>:last-child{grid-column:2}}
`;document.head.appendChild(style);
let radar=null,paper=null;
function inject(){if($('#radarIntelV2'))return;const footer=document.querySelector('footer');if(!footer)return;const s=document.createElement('section');s.id='radarIntelV2';s.className='radarx-shell';s.innerHTML=`
<div class="radarx-grid2"><div class="radarx-card"><div class="radarx-head"><div><div class="radarx-title">Setup trajectory</div><div class="radarx-meta">Score direction, rank movement and setup decay</div></div><span class="badge warn">1H EVOLUTION</span></div><div id="rxTrajectory"><div class="empty">Collecting radar history…</div></div></div><div class="radarx-card"><div class="radarx-head"><div><div class="radarx-title">Next 4h decision point</div><div class="radarx-meta">Countdown to the next closed 4h UTC candle</div></div></div><div id="rxCountdown"></div></div></div>
<div class="radarx-grid2"><div class="radarx-card"><div class="radarx-head"><div><div class="radarx-title">Why isn't this a trade yet?</div><div class="radarx-meta">Observed blockers versus gates only known at the 4h paper scan</div></div><select id="rxCoin" class="select radarx-select"></select></div><div id="rxBlockers"></div></div><div class="radarx-card"><div class="radarx-head"><div><div class="radarx-title">What would change this?</div><div class="radarx-meta">Conditions that can improve or weaken the hourly score</div></div></div><div id="rxWhatChanges"></div></div></div>
<div class="radarx-grid2"><div class="radarx-card"><div class="radarx-head"><div><div class="radarx-title">Live score history</div><div class="radarx-meta">Hourly radar score path for the selected coin</div></div></div><div id="rxScoreHistory"><div class="empty">Collecting snapshots…</div></div></div><div class="radarx-card"><div class="radarx-head"><div><div class="radarx-title">One-line Wavelength read</div><div class="radarx-meta">Deterministic explanation from the current data</div></div></div><div id="rxSummary" class="radarx-summary"></div></div></div>
<div class="radarx-grid2"><div class="radarx-card"><div class="radarx-head"><div><div class="radarx-title">Setup survival & false positives</div><div class="radarx-meta">Do 80+ setups remain meaningful four hours later?</div></div></div><div id="rxSurvival"></div></div><div class="radarx-card"><div class="radarx-head"><div><div class="radarx-title">Score quality vs outcome</div><div class="radarx-meta">Forward 4h return by score bucket</div></div></div><div id="rxBuckets"></div></div></div>
<div class="radarx-grid2"><div class="radarx-card"><div class="radarx-head"><div><div class="radarx-title">Trade blocker analytics</div><div class="radarx-meta">What most often prevents interesting radar names becoming paper positions</div></div></div><div id="rxBlockerStats"></div></div><div class="radarx-card"><div class="radarx-head"><div><div class="radarx-title">Confidence calibration</div><div class="radarx-meta">Do higher radar scores actually produce stronger forward outcomes?</div></div></div><div id="rxCalibration"></div></div></div>`;footer.parentNode.insertBefore(s,footer);$('#rxCoin').addEventListener('change',renderSelected)}
function history(){return load('wavelength_radar_intel_v2',[])}
function capture(){if(!radar)return;const h=history(),stamp=new Date(radar.generated_at||Date.now()).getTime();if(!Number.isFinite(stamp))return;if(h.some(x=>x.ts===stamp))return;h.push({ts:stamp,generated_at:radar.generated_at,items:(radar.opportunities||[]).map((x,i)=>({symbol:x.symbol,rank:i+1,score:+x.score,stage:x.stage,price:+x.price,rsi:+x.rsi,adx:+x.adx,volume_ratio:+x.volume_ratio,atr_pct:+x.atr_pct,ema20_above_ema80:!!x.ema20_above_ema80,breakout_20h:!!x.breakout_20h,change_24h:+x.change_24h}))});save('wavelength_radar_intel_v2',h.slice(-500))}
function getPrev(symbol,ts){const h=history().filter(x=>x.ts<ts).sort((a,b)=>b.ts-a.ts);for(const s of h){const x=s.items.find(z=>z.symbol===symbol);if(x)return {snap:s,item:x}}return null}
function trendWord(x,prev){if(!prev)return ['NEW','neutral'];const d=x.score-prev.item.score;if(d>=10)return [`IMPROVING +${d}`,'up'];if(d<=-10)return [`FADING ${d}`,'down'];if(d>0)return [`IMPROVING +${d}`,'up'];if(d<0)return [`SOFTENING ${d}`,'down'];return ['STABLE','neutral']}
function renderTrajectory(){const items=radar?.opportunities||[],ts=new Date(radar?.generated_at||Date.now()).getTime();if(!items.length){$('#rxTrajectory').innerHTML='<div class="empty">No surfaced radar opportunities.</div>';return}$('#rxTrajectory').innerHTML=items.slice(0,8).map((x,i)=>{const prev=getPrev(x.symbol,ts),[tw,tc]=trendWord(x,prev),rd=prev?prev.item.rank-(i+1):null,rank=rd==null?'new':rd>0?`↑${rd}`:rd<0?`↓${Math.abs(rd)}`:'—';return `<div class="radarx-row"><strong>${esc(x.symbol)}</strong><span><span class="radarx-pill ${tc}">${esc(tw)}</span> · score ${x.score} · ${esc(String(x.stage).replaceAll('_',' '))}</span><b class="${rd>0?'up':rd<0?'down':''}">#${i+1} ${rank}</b></div>`}).join('')}
function next4h(){const now=new Date(),u=Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate(),now.getUTCHours(),0,0,0),hour=now.getUTCHours(),nextHour=(Math.floor(hour/4)+1)*4;let t=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate(),nextHour,0,0,0));if(nextHour>=24)t=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate()+1,0,0,0));return t}
function renderCountdown(){const el=$('#rxCountdown');if(!el)return;const t=next4h(),ms=Math.max(0,t-Date.now()),hh=Math.floor(ms/36e5),mm=Math.floor(ms%36e5/6e4),ss=Math.floor(ms%6e4/1000);el.innerHTML=`<div style="font:800 36px 'IBM Plex Mono',monospace">${String(hh).padStart(2,'0')}:${String(mm).padStart(2,'0')}:${String(ss).padStart(2,'0')}</div><div class="radarx-meta" style="margin-top:8px">Next closed 4h decision point: ${t.toLocaleString('en-GB',{timeZone:'UTC',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})} UTC. The paper engine may still reject a setup after that close.</div>`}
function selected(){const s=$('#rxCoin')?.value;return (radar?.opportunities||[]).find(x=>x.symbol===s)||(radar?.opportunities||[])[0]}
function populateCoins(){const sel=$('#rxCoin'),xs=radar?.opportunities||[];if(!sel)return;const old=sel.value;sel.innerHTML=xs.map(x=>`<option value="${esc(x.symbol)}">${esc(x.symbol)} · ${x.score}</option>`).join('');if(xs.some(x=>x.symbol===old))sel.value=old}
function blockerList(x){if(!x)return [];const open=paper?.open_positions||[],rules=paper?.rules||{},held=open.some(p=>p.symbol===x.symbol),out=[];if(held)return [{type:'INFO',text:'Already held as an open paper position.',hard:false}];out.push({type:'WAIT',text:'Hourly radar is an early-warning layer. A closed 4h paper-engine evaluation is still required.',hard:true});if(x.stage!=='NEAR_CONFIRMATION')out.push({type:'RADAR',text:`Hourly stage is ${String(x.stage||'WATCH').replaceAll('_',' ')}, below Near Confirmation.`,hard:true});if(open.length>=+(rules.max_positions||3))out.push({type:'CAPACITY',text:`Portfolio is full (${open.length}/${rules.max_positions||3} positions). A new entry cannot be added unless capacity opens.`,hard:true});if(Number.isFinite(+x.rsi)&&!(+x.rsi>=50&&+x.rsi<=72))out.push({type:'MOMENTUM',text:`1h RSI ${num(x.rsi,1)} is outside the healthy 50–72 radar zone.`,hard:true});if(+x.adx<25)out.push({type:'TREND',text:`1h ADX ${num(x.adx,1)} is below 25.`,hard:true});if(+x.volume_ratio<1.25)out.push({type:'VOLUME',text:`Recent volume ${num(x.volume_ratio,2)}× is below the 1.25× expansion threshold.`,hard:false});out.push({type:'NEXT SCAN',text:'4h Intelligence, relative-strength eligibility, correlation and position sizing are evaluated by the paper engine and may still reject the setup.',hard:false});return out}
function recordBlockers(x,bs){if(!x)return;const day=new Date().toISOString().slice(0,13),key=`${day}:${x.symbol}`;const h=load('wavelength_radar_blockers_v2',[]);if(h.some(z=>z.key===key))return;h.push({key,ts:Date.now(),symbol:x.symbol,score:x.score,blockers:bs.filter(b=>b.hard).map(b=>b.type)});save('wavelength_radar_blockers_v2',h.slice(-2000))}
function renderBlockers(){const x=selected();if(!x){$('#rxBlockers').innerHTML='<div class="empty">No selected opportunity.</div>';return}const bs=blockerList(x);recordBlockers(x,bs);$('#rxBlockers').innerHTML=bs.map(b=>`<div class="radarx-block"><strong>${esc(b.type)}</strong> · ${esc(b.text)}</div>`).join('')}
function pointsNow(x){if(!x)return [];return [
 {label:'EMA20 > EMA80',on:!!x.ema20_above_ema80,pts:25,gain:'EMA trend must turn bullish to gain 25',lose:'Losing EMA20 > EMA80 removes 25'},
 {label:'RSI 50–72',on:+x.rsi>=50&&+x.rsi<=72,pts:20,gain:`RSI entering 50–72 adds 20`,lose:'RSI leaving 50–72 removes 20'},
 {label:'ADX ≥25',on:+x.adx>=25,pts:20,gain:'ADX reaching 25 adds 20',lose:'ADX below 25 removes 20'},
 {label:'ADX ≥35 bonus',on:+x.adx>=35,pts:10,gain:'ADX reaching 35 adds another 10',lose:'ADX below 35 removes 10'},
 {label:'Volume ≥1.25×',on:+x.volume_ratio>=1.25,pts:15,gain:'Volume expansion to 1.25× adds 15',lose:'Volume falling below 1.25× removes 15'},
 {label:'20h breakout',on:!!x.breakout_20h,pts:10,gain:'A new 20h breakout adds 10',lose:'No longer breaking the prior 20h high removes 10'}
]}
function renderWhatChanges(){const x=selected();if(!x)return;const ps=pointsNow(x),g=ps.filter(p=>!p.on).map(p=>p.gain),l=ps.filter(p=>p.on).map(p=>p.lose);$('#rxWhatChanges').innerHTML=`<div class="radarx-meta">Could improve</div>${g.length?g.map(t=>`<div class="radarx-block up">+ ${esc(t)}</div>`).join(''):'<div class="radarx-block">Already holds all positive radar components.</div>'}<div class="radarx-meta" style="margin-top:12px">Could weaken</div>${l.slice(0,5).map(t=>`<div class="radarx-block down">− ${esc(t)}</div>`).join('')}${+x.atr_pct<=8?'<div class="radarx-block down">− ATR volatility above 8% would apply a 10-point penalty.</div>':''}`}
function scoreSeries(symbol){return history().map(s=>{const x=s.items.find(i=>i.symbol===symbol);return x?{ts:s.ts,score:x.score,price:x.price}:null}).filter(Boolean).slice(-36)}
function spark(points){if(points.length<2)return '<div class="empty">Need at least two recorded radar snapshots.</div>';const W=700,H=100,p=12,min=Math.min(...points.map(x=>x.score),50),max=Math.max(...points.map(x=>x.score),100),xy=points.map((x,i)=>[p+i*(W-2*p)/(points.length-1),H-p-(x.score-min)*(H-2*p)/(max-min||1)]),d=xy.map((q,i)=>(i?'L':'M')+q[0].toFixed(1)+','+q[1].toFixed(1)).join(' ');return `<div class="radarx-spark"><svg viewBox="0 0 ${W} ${H}"><path d="${d}" fill="none" stroke="currentColor" stroke-width="3"/></svg></div><div class="radarx-meta">${points.length} recorded observations · ${new Date(points[0].ts).toLocaleString()} → ${new Date(points.at(-1).ts).toLocaleString()}</div>`}
function renderScoreHistory(){const x=selected();$('#rxScoreHistory').innerHTML=x?spark(scoreSeries(x.symbol)):'<div class="empty">No selected opportunity.</div>'}
function summaryText(x){if(!x)return 'No active radar opportunity to summarise.';const pos=[];if(x.ema20_above_ema80)pos.push('bullish hourly structure');if(+x.adx>=35)pos.push('strong trend strength');else if(+x.adx>=25)pos.push('developing trend strength');if(+x.volume_ratio>=1.25)pos.push('volume expansion');if(x.breakout_20h)pos.push('a 20-hour breakout');if(+x.rsi>=50&&+x.rsi<=72)pos.push('healthy momentum');const neg=[];if(+x.rsi>72)neg.push('momentum is stretched');if(+x.adx<25)neg.push('trend strength is still weak');if(+x.volume_ratio<1.25)neg.push('volume is not yet expanding');if(!x.breakout_20h)neg.push('there is no fresh 20-hour breakout');const pre=pos.length?pos.join(', '):'limited positive confirmation';return `${x.symbol} is ${String(x.stage||'WATCH').replaceAll('_',' ').toLowerCase()} at ${x.score}/100 because it has ${pre}.${neg.length?' Caution: '+neg.join(', ')+'.':''} This is an hourly research priority, not a probability or a trade instruction.`}
function renderSummary(){const x=selected();$('#rxSummary').textContent=summaryText(x)}
function futurePair(snap,symbol,hours=4){const target=snap.ts+hours*36e5;const hs=history().filter(z=>z.ts>=target&&z.ts<=target+2*36e5).sort((a,b)=>a.ts-b.ts);if(!hs.length)return null;const now=snap.items.find(i=>i.symbol===symbol),later=hs[0].items.find(i=>i.symbol===symbol);if(!now||!Number.isFinite(now.price))return null;return {later:later||null,ret:later&&Number.isFinite(later.price)?100*(later.price/now.price-1):null,survived:!!later&&later.score>=65,failed:!later||later.score<55}}
function samples(){const h=history(),out=[];for(const s of h){for(const x of s.items){const f=futurePair(s,x.symbol,4);if(f)out.push({ts:s.ts,symbol:x.symbol,score:x.score,price:x.price,...f})}}return out}
function renderSurvival(){const a=samples().filter(x=>x.score>=80),n=a.length,surv=a.filter(x=>x.survived).length,fail=a.filter(x=>x.failed).length;if(n<5){$('#rxSurvival').innerHTML=`<div class="empty">Collecting forward evidence: ${n}/5 resolved 80+ setup observations. No conclusion yet.</div>`;return}$('#rxSurvival').innerHTML=`<div class="radarx-kpis"><div class="radarx-kpi"><span class="radarx-meta">Resolved 80+</span><b>${n}</b></div><div class="radarx-kpi"><span class="radarx-meta">Still ≥65 after 4h</span><b>${pct(100*surv/n)}</b></div><div class="radarx-kpi"><span class="radarx-meta">False-positive proxy</span><b>${pct(100*fail/n)}</b></div><div class="radarx-kpi"><span class="radarx-meta">Caution</span><b>${n<20?'EARLY':'USABLE'}</b></div></div><div class="radarx-meta" style="margin-top:10px">False-positive proxy = absent from surfaced radar or score &lt;55 around four hours later. Browser-captured evidence only.</div>`}
function bucket(score){return score>=90?'90–100':score>=80?'80–89':score>=70?'70–79':'55–69'}
function bucketStats(){const m={};for(const x of samples().filter(x=>Number.isFinite(x.ret))){const b=bucket(x.score);(m[b]??=[]).push(x.ret)}return m}
function renderBuckets(){const m=bucketStats(),order=['90–100','80–89','70–79','55–69'];const rows=order.map(b=>{const a=m[b]||[],avg=a.length?a.reduce((s,v)=>s+v,0)/a.length:null,win=a.length?100*a.filter(v=>v>0).length/a.length:null;return `<tr><td>${b}</td><td>${a.length}</td><td class="${cls(avg)}">${pct(avg)}</td><td>${pct(win)}</td></tr>`}).join('');$('#rxBuckets').innerHTML=`<table class="radarx-table"><thead><tr><th>Score</th><th>n</th><th>Avg 4h</th><th>Positive</th></tr></thead><tbody>${rows}</tbody></table><div class="radarx-meta" style="margin-top:10px">Treat buckets with n&lt;10 as descriptive only.</div>`}
function renderBlockerStats(){const h=load('wavelength_radar_blockers_v2',[]),m={};h.forEach(x=>(x.blockers||[]).forEach(b=>m[b]=(m[b]||0)+1));const a=Object.entries(m).sort((x,y)=>y[1]-x[1]);if(!a.length){$('#rxBlockerStats').innerHTML='<div class="empty">Collecting blocker observations.</div>';return}const mx=a[0][1];$('#rxBlockerStats').innerHTML=a.map(([k,v])=>`<div class="radarx-row"><strong>${esc(k)}</strong><div class="radarx-bar"><i style="width:${100*v/mx}%"></i></div><b>${v}</b></div>`).join('')+'<div class="radarx-meta" style="margin-top:10px">Counts are observations, not independent trades.</div>'}
function renderCalibration(){const m=bucketStats(),order=['55–69','70–79','80–89','90–100'],vals=order.map(b=>{const a=m[b]||[];return {b,n:a.length,avg:a.length?a.reduce((s,v)=>s+v,0)/a.length:null}}),resolved=vals.reduce((s,x)=>s+x.n,0);if(resolved<10){$('#rxCalibration').innerHTML=`<div class="empty">${resolved}/10 resolved score/outcome observations. Too early to judge whether higher scores are genuinely better calibrated.</div>`;return}const usable=vals.filter(x=>x.n>=3&&Number.isFinite(x.avg));let mono=true;for(let i=1;i<usable.length;i++)if(usable[i].avg<usable[i-1].avg)mono=false;$('#rxCalibration').innerHTML=`<div class="radarx-kpis">${vals.map(x=>`<div class="radarx-kpi"><span class="radarx-meta">${x.b}</span><b class="${cls(x.avg)}">${x.n?pct(x.avg):'—'}</b><span class="radarx-meta">n=${x.n}</span></div>`).join('')}</div><div class="radarx-block"><strong>${mono?'EARLY CALIBRATION CONSISTENT':'CALIBRATION NOT YET ORDERED'}</strong> · Higher scores ${mono?'currently have non-decreasing average 4h outcomes in usable buckets':'do not yet show a clean monotonic relationship with 4h outcomes'}.</div>`}
function renderSelected(){renderBlockers();renderWhatChanges();renderScoreHistory();renderSummary()}
async function refresh(){try{[radar,paper]=await Promise.all([j('opportunity-radar.json'),j('paper-portfolio.json')]);capture();populateCoins();renderTrajectory();renderSelected();renderSurvival();renderBuckets();renderBlockerStats();renderCalibration()}catch(e){console.warn('radar intelligence',e)}}
inject();refresh();renderCountdown();setInterval(renderCountdown,1000);setInterval(refresh,60000);
})();
