(()=>{
'use strict';
const $=s=>document.querySelector(s), API='https://data-api.binance.vision';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=(v,d=2)=>Number.isFinite(+v)?(+v).toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d}):'—';
const pct=v=>Number.isFinite(+v)?`${+v>=0?'+':''}${num(v,2)}%`:'—';
const money=v=>Number.isFinite(+v)?`${+v>=0?'+':''}$${Math.abs(+v).toFixed(2)}`:'—';
const cls=v=>+v>0?'up':+v<0?'down':'neutral';
const age=t=>{const h=(Date.now()-new Date(t).getTime())/36e5;return Number.isFinite(h)?(h<1?`${Math.max(0,Math.round(h*60))}m`:h<48?`${h.toFixed(1)}h`:`${(h/24).toFixed(1)}d`):'—'};
async function j(u){const r=await fetch(`${u}${u.includes('?')?'&':'?'}t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`${u} ${r.status}`);return r.json()}
function metric(l,v,c=''){return `<div class="metric"><div class="metric-label">${esc(l)}</div><div class="metric-value ${c}">${v}</div></div>`}
function rows(xs){return xs.map(([a,b,c])=>`<div class="analysis-row"><span class="analysis-label">${esc(a)}</span><strong class="${c||''}">${b}</strong></div>`).join('')}
function store(k,v){localStorage.setItem(k,JSON.stringify(v))} function load(k,d=[]){try{return JSON.parse(localStorage.getItem(k)||'null')??d}catch{return d}}
let feeds={};
function appendUnique(key,item,limit=500){const a=load(key,[]);if(!a.some(x=>x.key===item.key)){a.push(item);store(key,a.slice(-limit))}return a}
function capture(r,p,v,l){const ts=Date.now();const key=new Date(ts).toISOString().slice(0,16);const snap={key,ts,radar:{generated_at:r?.generated_at,scanned:r?.scanned_markets,opportunities:(r?.opportunities||[]).map(x=>({symbol:x.symbol,score:x.score,stage:x.stage,price:x.price,adx:x.adx,volume_ratio:x.volume_ratio,change_24h:x.change_24h}))},paper:{equity:p?.paper_equity,cash:p?.cash,regime:p?.market_regime,open:(p?.open_positions||[]).map(x=>({symbol:x.symbol,pnl:x.unrealized_pnl,net:x.unrealized_net_pct,current:x.current,stop:x.stop,intel:x.intel}))},validation:{v3:v?.strategies?.v3?.status,crowding:v?.strategies?.crowding_v2?.status},learning:{stage:l?.stage,resolved:l?.resolved_setups}};appendUnique('wavelength_replay_v1',snap,300);const bh={key,ts,total:(r?.opportunities||[]).length,watch:(r?.opportunities||[]).filter(x=>x.stage==='WATCH').length,developing:(r?.opportunities||[]).filter(x=>x.stage==='DEVELOPING').length,near:(r?.opportunities||[]).filter(x=>x.stage==='NEAR_CONFIRMATION').length};appendUnique('wavelength_radar_breadth_v1',bh,500);const hist=load('wavelength_radar_coin_history_v1',[]);for(const x of r?.opportunities||[]){const k=`${key}:${x.symbol}`;if(!hist.some(z=>z.key===k))hist.push({key:k,ts,symbol:x.symbol,score:x.score,stage:x.stage,price:x.price})}store('wavelength_radar_coin_history_v1',hist.slice(-4000));}
function today(r,p,v,l){const open=p?.open_positions||[], opp=r?.opportunities||[], top=opp[0], net=open.reduce((a,x)=>a+(+x.unrealized_pnl||0),0), stressed=open.filter(x=>Number.isFinite(+x.current)&&Number.isFinite(+x.stop)&&100*(+x.current-+x.stop)/(+x.current)<3);$('#todayGrid').innerHTML=[metric('Paper equity',Number.isFinite(+p?.paper_equity)?'$'+(+p.paper_equity).toFixed(2):'—',cls((+p?.paper_equity||0)-(+p?.paper_starting_equity||0))),metric('Open net P&L',money(net),cls(net)),metric('Top radar',top?`${esc(top.symbol)} · ${top.score}`:'None'),metric('Near confirmation',opp.filter(x=>x.stage==='NEAR_CONFIRMATION').length),metric('Stop pressure',stressed.length,stressed.length?'down':''),metric('Regime',esc(p?.market_regime||'—')),metric('V3 validation',esc(v?.strategies?.v3?.status||'—')),metric('Learning',esc(l?.stage||'—'))].join('');$('#todayBadge').textContent=stressed.length?'ATTENTION':opp.some(x=>x.stage==='NEAR_CONFIRMATION')?'ACTIVE':'CALM';$('#todayBadge').className='badge '+(stressed.length?'bad':opp.some(x=>x.stage==='NEAR_CONFIRMATION')?'warn':'good');const bits=[];if(top)bits.push(`${top.symbol} is the highest hourly radar candidate at ${top.score}/100 (${String(top.stage).replaceAll('_',' ').toLowerCase()}).`);if(open.length)bits.push(`${open.length} paper position${open.length===1?' is':'s are'} open with ${money(net)} estimated net P&L if closed now.`);if(stressed.length)bits.push(`${stressed.map(x=>x.symbol).join(', ')} ${stressed.length===1?'is':'are'} within 3% of the current stop.`);bits.push('No UI metric can enable orders or change the frozen 4h decision rules.');$('#todayNarrative').innerHTML=`<p>${esc(bits.join(' '))}</p>`}
function notifications(r,p,v){const old=load('wavelength_research_prior_v1',{}), out=load('wavelength_research_notifications_v1',[]), now=Date.now();const add=(type,text)=>out.unshift({ts:now,type,text});const top=(r?.opportunities||[]).filter(x=>x.stage==='NEAR_CONFIRMATION').map(x=>x.symbol);for(const s of top)if(!(old.near||[]).includes(s))add('RADAR',`${s} entered Near Confirmation`);for(const x of p?.open_positions||[]){const b=100*(+x.current-+x.stop)/(+x.current);if(Number.isFinite(b)&&b<3&&!(old.stop||[]).includes(x.symbol))add('RISK',`${x.symbol} moved within ${b.toFixed(2)}% of its paper stop`)}const v3=v?.strategies?.v3?.status;if(old.v3&&v3&&old.v3!==v3)add('VALIDATION',`Candidate V3 changed ${old.v3} → ${v3}`);store('wavelength_research_prior_v1',{near:top,stop:(p?.open_positions||[]).filter(x=>100*(+x.current-+x.stop)/(+x.current)<3).map(x=>x.symbol),v3});store('wavelength_research_notifications_v1',out.slice(0,100));renderNotifications()}
function renderNotifications(){const x=load('wavelength_research_notifications_v1',[]);$('#notificationCentre').innerHTML=x.length?x.slice(0,12).map(e=>`<div class="analysis-row"><span><strong>${esc(e.type)}</strong><br><span class="card-meta">${new Date(e.ts).toLocaleString()}</span></span><span>${esc(e.text)}</span></div>`).join(''):'<div class="empty">No meaningful changes recorded yet.</div>'}
function confidence(r){const x=(r?.opportunities||[])[0];if(!x){$('#signalConfidence').innerHTML='<div class="empty">No radar candidates.</div>';return}const parts=[['EMA trend',x.ema20_above_ema80?'+25':'0'],['Healthy RSI',Number.isFinite(+x.rsi)&&+x.rsi>=50&&+x.rsi<=72?'+20':'0'],['ADX ≥25',+x.adx>=25?'+20':'0'],['ADX ≥35',+x.adx>=35?'+10':'0'],['Volume ≥1.25×',+x.volume_ratio>=1.25?'+15':'0'],['20h breakout',x.breakout_20h?'+10':'0'],['High-vol penalty',+x.atr_pct>8?'-10':'0']];$('#signalConfidence').innerHTML=`<div style="font-size:28px;font-weight:800">${esc(x.symbol)} · ${x.score}/100</div><div class="card-meta" style="margin:4px 0 10px">${esc(String(x.stage||'').replaceAll('_',' '))} · explanation, not probability</div>${rows(parts.map(a=>[a[0],a[1]]))}`}
async function benchmark(p,h){const pts=h?.equity_curve||[];if(!pts.length){$('#benchmarks').innerHTML='<div class="empty">No paper history yet.</div>';return}const start=+pts[0].time_ms, paper0=+pts[0].equity, paper=+p.paper_equity;async function ret(sym){const q=await j(`${API}/api/v3/klines?symbol=${sym}USDT&interval=1h&startTime=${Math.floor(start)}&limit=1000`);if(!q.length)return null;const a=+q[0][4],b=+q[q.length-1][4];return a?100*(b/a-1):null}try{const [btc,eth]=await Promise.all([ret('BTC'),ret('ETH')]),pr=paper0?100*(paper/paper0-1):null;$('#benchmarks').innerHTML=[metric('Wavelength',pct(pr),cls(pr)),metric('BTC hold',pct(btc),cls(btc)),metric('ETH hold',pct(eth),cls(eth)),metric('vs BTC',Number.isFinite(pr)&&Number.isFinite(btc)?pct(pr-btc):'—',cls(pr-btc))].join('')+'<div class="card-meta" style="margin-top:10px">Same-window mark-to-market comparison; not risk-adjusted and not proof of skill.</div>'}catch(e){$('#benchmarks').innerHTML='<div class="empty">Benchmark market data unavailable.</div>'}}
function expectancy(p){const t=p?.recent_closed_trades||[];if(!t.length){$('#expectancy').innerHTML='<div class="empty">No closed trades yet. Expectancy will remain blank rather than infer from open P&L.</div>';return}const wins=t.filter(x=>+x.pnl>0),loss=t.filter(x=>+x.pnl<0),aw=wins.length?wins.reduce((a,x)=>a+(+x.pnl_pct||0),0)/wins.length:0,al=loss.length?Math.abs(loss.reduce((a,x)=>a+(+x.pnl_pct||0),0)/loss.length):0,wr=100*wins.length/t.length,pay=al?aw/al:null,be=aw+al?100*al/(aw+al):null,ex=(wr/100)*aw-(1-wr/100)*al;$('#expectancy').innerHTML=[metric('Sample',t.length),metric('Win rate',pct(wr)),metric('Avg win',pct(aw)),metric('Avg loss',loss.length?`-${num(al,2)}%`:'—'),metric('Payoff',pay==null?'—':num(pay,2)+'×'),metric('Breakeven WR',be==null?'—':pct(be)),metric('Expectancy/trade',pct(ex),cls(ex))].join('')}
async function pathStats(p){const xs=p?.open_positions||[];if(!xs.length){$('#maeMfe').innerHTML='<div class="empty">No open positions.</div>';return}const out=[];for(const x of xs){try{const start=Date.now()-(+x.age_hours||0)*36e5;const k=await j(`${API}/api/v3/klines?symbol=${x.symbol}USDT&interval=1h&startTime=${Math.floor(start)}&limit=200`);const hi=Math.max(...k.map(z=>+z[2])),lo=Math.min(...k.map(z=>+z[3])),e=+x.entry;out.push([x.symbol,100*(lo/e-1),100*(hi/e-1)])}catch{out.push([x.symbol,null,null])}}$('#maeMfe').innerHTML=out.map(([s,mae,mfe])=>`<div class="analysis-row"><strong>${esc(s)}</strong><span><span class="down">MAE ${pct(mae)}</span> · <span class="up">MFE ${pct(mfe)}</span></span></div>`).join('')+'<div class="card-meta" style="margin-top:10px">Current-position path stats use hourly highs/lows since estimated entry time.</div>'}
function missed(r,p){const held=new Set((p?.open_positions||[]).map(x=>x.symbol));const xs=(r?.opportunities||[]).filter(x=>x.score>=75&&!held.has(x.symbol));$('#missedOpps').innerHTML=xs.length?xs.slice(0,10).map(x=>`<div class="analysis-row"><span><strong>${esc(x.symbol)}</strong><br><span class="card-meta">${esc(String(x.stage).replaceAll('_',' '))}</span></span><span>Score ${x.score} · 24h <span class="${cls(x.change_24h)}">${pct(x.change_24h)}</span></span></div>`).join('')+'<div class="card-meta" style="margin-top:10px">These are current high-quality radar candidates not held by the paper portfolio. Forward outcome tracking builds from browser-captured radar history.</div>':'<div class="empty">No current score ≥75 radar candidates are outside the paper portfolio.</div>'}
function attribution(p){const open=p?.open_positions||[],closed=p?.recent_closed_trades||[];const by={};for(const x of [...open,...closed]){const k=x.regime||p.market_regime||'UNKNOWN';by[k]=(by[k]||0)+(+x.pnl||+x.unrealized_pnl||0)}const coins=[...open.map(x=>[x.symbol,+x.unrealized_pnl||0]),...closed.map(x=>[x.symbol,+x.pnl||0])].sort((a,b)=>b[1]-a[1]);$('#attribution').innerHTML=(coins.length?`<div class="card-meta">By coin</div>${rows(coins.slice(0,8).map(x=>[x[0],money(x[1]),cls(x[1])]))}`:'<div class="empty">No attributable P&L yet.</div>')+(Object.keys(by).length?`<div class="card-meta" style="margin-top:12px">By regime</div>${rows(Object.entries(by).map(x=>[x[0],money(x[1]),cls(x[1])]))}`:'')}
function stopAlerts(p){const xs=(p?.open_positions||[]).map(x=>({...x,buffer:100*(+x.current-+x.stop)/(+x.current)})).sort((a,b)=>a.buffer-b.buffer);$('#stopAlerts').innerHTML=xs.length?xs.map(x=>`<div class="analysis-row"><strong>${esc(x.symbol)}</strong><span class="${x.buffer<1?'down':x.buffer<3?'neutral':''}">${num(x.buffer,2)}% above stop</span></div>`).join(''):'<div class="empty">No open positions.</div>'}
function lineSvg(points){if(points.length<2)return '<div class="empty">Need at least two observations.</div>';const W=700,H=210,p=18,vals=points.map(x=>+x.total),mn=0,mx=Math.max(1,...vals),xy=points.map((x,i)=>[p+i*(W-2*p)/(points.length-1),H-p-(+x.total-mn)*(H-2*p)/(mx-mn)]),path=xy.map((q,i)=>(i?'L':'M')+q[0].toFixed(1)+','+q[1].toFixed(1)).join(' ');return `<svg viewBox="0 0 ${W} ${H}"><path d="${path}" fill="none" stroke="currentColor" stroke-width="3"/><text x="18" y="14" fill="currentColor" opacity=".7" font-size="12">Radar opportunities high ${mx}</text></svg>`}
function histories(){const b=load('wavelength_radar_breadth_v1',[]);$('#breadthHistory').innerHTML=lineSvg(b);const h=load('wavelength_radar_coin_history_v1',[]),syms=[...new Set(h.map(x=>x.symbol))].sort(),sel=$('#radarCoin');const prev=sel.value;sel.innerHTML=syms.map(s=>`<option>${esc(s)}</option>`).join('');if(syms.includes(prev))sel.value=prev;renderCoinHistory()}
function renderCoinHistory(){const s=$('#radarCoin').value,h=load('wavelength_radar_coin_history_v1',[]).filter(x=>x.symbol===s).slice(-20);$('#coinRadarHistory').innerHTML=h.length?h.reverse().map(x=>`<div class="analysis-row"><span>${new Date(x.ts).toLocaleString()}</span><strong>${esc(String(x.stage).replaceAll('_',' '))} · ${x.score}</strong></div>`).join(''):'<div class="empty">No history for this coin yet.</div>'}
function notes(){const n=load('wavelength_research_notes_v1',[]);$('#notesList').innerHTML=n.length?n.slice().reverse().map(x=>`<div class="analysis-row"><span>${new Date(x.ts).toLocaleString()}</span><span>${esc(x.text)}</span></div>`).join(''):'<div class="empty">No notes yet.</div>'}
function replay(){const r=load('wavelength_replay_v1',[]),sel=$('#replaySelect');sel.innerHTML=r.slice().reverse().map((x,i)=>`<option value="${x.ts}">${new Date(x.ts).toLocaleString()}</option>`).join('');renderReplay()}
function renderReplay(){const ts=+$(`#replaySelect`).value,r=load('wavelength_replay_v1',[]).find(x=>x.ts===ts);if(!r){$('#replayView').innerHTML='<div class="empty">No replay snapshot yet.</div>';return}const top=r.radar?.opportunities?.[0],open=r.paper?.open||[];$('#replayView').innerHTML=[metric('Paper equity',Number.isFinite(+r.paper?.equity)?'$'+(+r.paper.equity).toFixed(2):'—'),metric('Regime',esc(r.paper?.regime||'—')),metric('Open positions',open.length),metric('Top radar',top?`${esc(top.symbol)} · ${top.score}`:'None'),metric('V3',esc(r.validation?.v3||'—')),metric('Learning',esc(r.learning?.stage||'—'))].join('')}
function promotion(p,h){const trades=+p?.closed_trades_total||0,pts=h?.equity_curve||[],days=pts.length?(Date.now()-+pts[0].time_ms)/864e5:0,ret=(+p?.paper_starting_equity)>0?100*(+p.paper_equity/+p.paper_starting_equity-1):0,dd=+p?.weekly?.max_drawdown_pct||0;const gates=[['Closed trades',trades,30,trades>=30],['Calendar days',days,90,days>=90],['Positive total return',ret,0,ret>0],['Max drawdown better than -15%',dd,-15,dd>-15]];$('#promotionGates').innerHTML=gates.map(([n,v,t,ok])=>`<div class="analysis-row"><span>${esc(n)}</span><strong class="${ok?'up':'neutral'}">${ok?'PASS':'WAIT'} · ${typeof v==='number'?num(v,1):v}${n.includes('days')||n.includes('trades')?'':n.includes('return')||n.includes('drawdown')?'%':''}</strong></div>`).join('')+'<div class="card-meta" style="margin-top:10px">Passing these UI gates would only justify a review for Alpaca paper execution — never automatic live-money promotion.</div>'}
function quality(r,p,v,l){const now=Date.now(),items=[['Hourly radar',r?.generated_at,2],['Paper portfolio',p?.generated_at,6],['Validation',v?.generated_at,6],['Server learning',l?.generated_at,6]];$('#dataQuality').innerHTML=items.map(([n,t,max])=>{const hrs=t?(now-new Date(t).getTime())/36e5:Infinity,ok=hrs<=max;return `<div class="analysis-row"><span>${esc(n)}</span><strong class="${ok?'up':'down'}">${ok?'FRESH':'STALE / MISSING'} · ${t?age(t):'—'}</strong></div>`}).join('')}
async function main(){const rs=await Promise.allSettled([j('opportunity-radar.json'),j('paper-portfolio.json'),j('paper-history.json'),j('validation.json'),j('learning-status.json')]);const [r,p,h,v,l]=rs.map(x=>x.status==='fulfilled'?x.value:null);feeds={r,p,h,v,l};capture(r,p,v,l);today(r,p,v,l);notifications(r,p,v);confidence(r);expectancy(p);missed(r,p);attribution(p);stopAlerts(p);histories();notes();replay();promotion(p,h);quality(r,p,v,l);benchmark(p,h);pathStats(p);$('#researchStatus').className='status-pill';$('#researchStatus').innerHTML='<span class="dot"></span>RESEARCH LIVE';}
$('#clearNotifications')?.addEventListener('click',()=>{store('wavelength_research_notifications_v1',[]);renderNotifications()});$('#saveNote')?.addEventListener('click',()=>{const t=$('#noteText').value.trim();if(!t)return;const n=load('wavelength_research_notes_v1',[]);n.push({ts:Date.now(),text:t});store('wavelength_research_notes_v1',n.slice(-500));$('#noteText').value='';notes()});$('#radarCoin')?.addEventListener('change',renderCoinHistory);$('#replaySelect')?.addEventListener('change',renderReplay);main().catch(e=>{console.error(e);$('#researchStatus').className='status-pill bad';$('#researchStatus').innerHTML='<span class="dot"></span>RESEARCH ERROR'});setInterval(main,60000);
})();
