(()=>{
const nav=document.querySelector('.nav');if(!nav)return;
const p=(location.pathname.split('/').pop()||'index.html').toLowerCase();
const items=[['index.html','Overview'],['wavelength-today.html','Today'],['index.html#markets','Markets'],['market-workbench.html','Workbench'],['research-intelligence.html','Market Intel'],['purchase-intelligence.html','Purchase Intel'],['trade-decisions.html','Trade Decisions'],['opportunity-centre.html','Opportunities'],['decisions.html','Decisions'],['calibration.html','Calibration'],['portfolio-command.html','Portfolio'],['validation-dashboard.html','Validation'],['daily-briefing.html','Daily Brief'],['activity.html','Activity'],['alerts.html','Alerts'],['data-quality.html','Data Health'],['provenance.html','Sources'],['hypotheses.html','Hypotheses'],['index.html#intelligence','Intelligence'],['learning.html','Learning'],['paper.html','Paper P&L'],['research.html','Research'],['control-centre.html','Control Centre'],['outcomes.html','Outcomes'],['graduation.html','Graduation'],['governance.html','Governance'],['compare.html','Compare'],['mobile.html','Mobile'],['strategies.html','Strategies'],['bot.html','Bot']];
nav.innerHTML=items.map(([h,l])=>{const base=h.split('#')[0],active=(p===base||(!p&&base==='index.html'))&&!h.includes('#');return `<a${active?' class="active"':''} href="${h}">${l}</a>`}).join('');
if(!document.querySelector('link[data-wl-hardening]')){const l=document.createElement('link');l.rel='stylesheet';l.href='platform-hardening.css';l.dataset.wlHardening='1';document.head.appendChild(l)}
const top=document.querySelector('.topbar');if(top&&!document.querySelector('.strategy-boundary')){const b=document.createElement('button');b.className='pill-btn strategy-boundary';b.textContent='⌘ Search';b.title='Open Wavelength command palette (Ctrl/Cmd+K)';b.onclick=()=>window.WavelengthCommandPalette?.open();top.appendChild(b)}
window.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('.metric,.ev-kpi,.analysis-row,.pro-kpi').forEach(el=>{if(!el.title)el.title='Metric source/timeframe may differ. See Sources / Governance for evidence provenance, maturity and research locks.'})});
function load(src,key){if(document.querySelector(`script[data-${key}]`))return;const s=document.createElement('script');s.src=src;s.defer=true;s.setAttribute(`data-${key}`,'1');document.head.appendChild(s)}
load('command-palette.js','wl-command');load('provenance-core.js','wl-provenance');load('workspace-ui.js','wl-workspace');load('terminal-ui.js','wl-terminal');load('final-ui.js','wl-final');
if((p==='index.html'||!p)){load('observation-experience.js','wl-observation');load('market-command-centre.js','wl-market-command');load('decision-journal.js','wl-decision-journal')}
})();