(()=>{'use strict';
if(window.__wavelengthTerminalShellV1)return;window.__wavelengthTerminalShellV1=true;
const page=(location.pathname.split('/').pop()||'index.html').toLowerCase();
const enabled=new Set(['index.html','','market-command.html','data-truth-v4.html','conviction-room.html','asset.html','coin.html']);
if(!enabled.has(page))return;
document.body.classList.add('wl-terminal-v1');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const codeMap={
 'Market Opportunity Map':'MAP','Wavelength Radar':'RDR','Replay Time Machine':'RPLY','Scenario Theatre':'SCEN','Portfolio X-Ray':'XRAY','Decision Story':'STORY','Thesis Autopsy':'AUTO','Why Not?':'WHY','Evidence Heatmap':'EVID','Explainable Opportunity Alerts':'ALRT','Wavelength Intelligence Stream':'INTL',
 'Semantic Evidence Mix':'MIX','Derivatives Cross-Check':'DER','True Exchange-Flow Intelligence':'FLOW','Dimension Semantics':'DIMS','Hyperliquid Provider Health':'HYP','Semantic Policy':'POL',
 'Price chart':'CHRT','Technical structure':'TECH','Derivatives / crowding':'DER','Fundamentals':'FUND','Why Wavelength cares':'THES','Market Memory / historical analogues':'MEM','Wavelength read':'READ',
 'Ask Wavelength':'ASK','Multi-timeframe structure':'MTF','Decision boundary':'BOUND','Adversarial tests':'CHLG','Opportunity cost':'OPC','Execution reality':'EXEC','Missing evidence':'GAPS'
};
function decorateTitles(){ $$('.card-title').forEach(el=>{const t=el.textContent.trim();const code=codeMap[t]||t.replace(/[^A-Za-z]/g,'').slice(0,4).toUpperCase();el.dataset.termCode=`[${code}]`;}); }
function strip(){if($('.wlt-strip'))return;const d=document.createElement('div');d.className='wlt-strip';d.innerHTML=`<div class="wlt-strip-brand">WL // TERMINAL</div><div class="wlt-strip-feed"><span id="wltIntegrity">INTG —</span><span id="wltTruth">DATA —</span><span id="wltFlow">FLOW —</span><span id="wltProof">PROOF —</span><span id="wltMode">MODE RESEARCH-ONLY</span></div><div class="wlt-strip-time" id="wltClock">--:--:-- UTC</div>`;document.body.prepend(d);const tick=()=>{const n=new Date();const c=$('#wltClock');if(c)c.textContent=n.toISOString().slice(11,19)+' UTC'};tick();setInterval(tick,1000);Promise.all([fetch('system-integrity.json?ts='+Date.now(),{cache:'no-store'}).then(r=>r.ok?r.json():null).catch(()=>null),fetch('data-truth-v4.json?ts='+Date.now(),{cache:'no-store'}).then(r=>r.ok?r.json():null).catch(()=>null),fetch('exchange-flow-intelligence.json?ts='+Date.now(),{cache:'no-store'}).then(r=>r.ok?r.json():null).catch(()=>null),fetch('proof-programme.json?ts='+Date.now(),{cache:'no-store'}).then(r=>r.ok?r.json():null).catch(()=>null)]).then(([i,t,f,p])=>{const ie=$('#wltIntegrity'),te=$('#wltTruth'),fe=$('#wltFlow'),pe=$('#wltProof');if(ie){ie.textContent=`INTG ${i?.integrity_score??'—'} ${i?.status??''}`;ie.classList.add((i?.integrity_score??0)>=95?'wlt-green':'wlt-yellow')}if(te){const v=t?.scores?.proxy_adjusted_completeness;te.textContent=`DATA ${v??'—'}%`;te.classList.add((v??0)>=80?'wlt-green':'wlt-yellow')}if(fe){const n=f?.coverage?.direct_assets;fe.textContent=`FLOW ${n??'—'} DIRECT`;fe.classList.add(n>0?'wlt-cyan':'wlt-yellow')}if(pe){const n=p?.proof_ledger?.cycles??p?.summary?.cycles??p?.cycles?.length??'—';pe.textContent=`PROOF ${n} CYC`;}});}
function rail(){if($('.wlt-rail'))return;const r=document.createElement('nav');r.className='wlt-rail';r.setAttribute('aria-label','Terminal functions');r.innerHTML=`<a href="index.html" title="Overview"><kbd>F1</kbd>OV</a><a href="market-command.html" title="Market Command"><kbd>F2</kbd>MK</a><a href="data-truth-v4.html" title="Data Truth"><kbd>F3</kbd>DT</a><a href="conviction-room.html" title="Conviction Room"><kbd>F4</kbd>CR</a><a href="proof-programme.html" title="Proof"><kbd>F5</kbd>PF</a><button type="button" id="wltSearch" title="Command search"><kbd>/</kbd>GO</button>`;document.body.appendChild(r);$('#wltSearch',r)?.addEventListener('click',()=>window.WavelengthCommandPalette?.open?.()||window.WavelengthCommand?.());}
function commandLine(){const pageEl=$('.page')||$('main');if(!pageEl||$('.wlt-commandline'))return;const bar=document.createElement('div');bar.className='wlt-commandline';bar.innerHTML=`<label>WL&gt;</label><input id="wltCmd" autocomplete="off" spellcheck="false" placeholder="Type command: BTC, DT, FLOW, PROOF, RISK, MARKET…"><span class="wlt-command-help">ENTER execute · / palette · F1–F5 functions</span>`;const top=$('.topbar',pageEl);if(top)top.insertAdjacentElement('afterend',bar);else pageEl.prepend(bar);const input=$('#wltCmd',bar);const routes={DT:'data-truth-v4.html',DATA:'data-truth-v4.html',FLOW:'data-truth-v4.html#flows',PROOF:'proof-programme.html',PF:'proof-programme.html',RISK:'portfolio-risk.html',MARKET:'market-command.html',MK:'market-command.html',CR:'conviction-room.html',CONVICTION:'conviction-room.html',HOME:'index.html',OV:'index.html',INT:'system-integrity.html'};input?.addEventListener('keydown',e=>{if(e.key!=='Enter')return;const q=input.value.trim().toUpperCase();if(!q)return;if(routes[q]){location.href=routes[q];return}if(/^[A-Z0-9]{2,10}$/.test(q)){location.href=`asset.html?symbol=${encodeURIComponent(q)}`;return}window.WavelengthCommandPalette?.open?.();});}
function keys(){document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;const map={F1:'index.html',F2:'market-command.html',F3:'data-truth-v4.html',F4:'conviction-room.html',F5:'proof-programme.html'};if(map[e.key]){e.preventDefault();location.href=map[e.key]}})}
function pageCode(){const sub=$('.brand-sub');if(!sub)return;const labels={'index.html':'OVERVIEW TERMINAL','':'OVERVIEW TERMINAL','market-command.html':'MARKET COMMAND // MK','data-truth-v4.html':'DATA TRUTH // DT','conviction-room.html':'CONVICTION ROOM // CR','asset.html':'ASSET WORKSTATION // SEC','coin.html':'COIN WORKSTATION // SEC'};sub.textContent=labels[page]||sub.textContent;}
function terminalizeConviction(){if(page!=='conviction-room.html')return;const top=$('.topbar');if(top&&!top.querySelector('.brand'))top.innerHTML='<a class="brand" href="./"><div class="brand-mark">〰</div><div><div class="brand-name">Wavelength Live</div><div class="brand-sub">CONVICTION ROOM // CR</div></div></a><nav class="nav"></nav>';}
function init(){terminalizeConviction();pageCode();strip();rail();commandLine();decorateTitles();keys();document.documentElement.dataset.density='terminal';}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();