(()=>{
'use strict';
if(window.WavelengthOS)return;
const cache=new Map();
const get=async path=>{if(cache.has(path))return cache.get(path);const p=fetch(path,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(`${path} ${r.status}`);return r.json()}).catch(()=>null);cache.set(path,p);return p};
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const num=v=>Number.isFinite(Number(v))?Number(v):null;
const pct=v=>num(v)==null?'—':`${num(v)>=0?'+':''}${num(v).toFixed(2)}%`;
const title=s=>String(s||'').replace(/_/g,' ').replace(/\b\w/g,m=>m.toUpperCase());
const assurance=async()=>await get('decision-assurance-v1.json')||{};
const assets=async()=>Array.isArray((await assurance()).assets)?(await assurance()).assets:[];
const asset=async symbol=>(await assets()).find(a=>String(a.symbol).toUpperCase()===String(symbol).toUpperCase())||null;
const score=a=>num(a?.evidence_confidence?.score)||0;
const grade=a=>a?.evidence_confidence?.grade||'—';
const quality=a=>a?.evidence_confidence?.counts||a?.coin_intelligence?.source_quality||{};
const ranked=async()=>[...(await assets())].sort((a,b)=>score(b)-score(a));
const params=()=>Object.fromEntries(new URLSearchParams(location.search));
const nav=active=>`<div class="wl-os-customer-nav">${[['wavelength-today.html','Today'],['discover.html','Discover'],['portfolio-intelligence.html','My Portfolio'],['index.html#markets','Assets'],['proof-ledger.html','Proof'],['ask-wavelength.html','Ask Wavelength']].map(([h,l])=>`<a class="${active===l?'active':''}" href="${h}">${l}</a>`).join('')}</div>`;
const boot=(active)=>{document.body.classList.add('wl-customer-os');const top=document.querySelector('.topbar');if(top&&!document.querySelector('.wl-os-customer-nav'))top.insertAdjacentHTML('afterend',nav(active));};
const dimensions=a=>{const all=[...(a?.decision_decomposition?.positive||[]),...(a?.decision_decomposition?.negative_or_fragile||[])];const map={};all.forEach(x=>map[x.dimension]=x);return map};
const deskMap={technical:'Technical',derivatives:'Derivatives',onchain_exchange_flows:'On-chain',macro_context:'Macro',liquidity:'Liquidity',fundamental:'Fundamentals',stablecoin_liquidity:'Stablecoins',event_catalyst_risk:'Catalyst Risk',market_context:'Market Context'};
const committee=a=>Object.entries(deskMap).map(([k,name])=>{const d=dimensions(a)[k];const q=num(d?.quality_score);let vote='NO DATA';if(q!=null)vote=q>=85?'SUPPORT':q>=65?'WATCH':'OBJECT';return {key:k,name,vote,score:q,provider:d?.provider||'—',freshness:d?.freshness||'—',semantic:d?.semantic_class||'—'}});
const objections=a=>(a?.decision_decomposition?.negative_or_fragile||a?.evidence_confidence?.weakest_evidence||[]).slice(0,5);
const positives=a=>(a?.decision_decomposition?.positive||a?.evidence_confidence?.strongest_evidence||[]).slice(0,5);
const proof=async()=>{const a=await assurance();const calibration=await get('signal-calibration.json')||{};const outcomes=await get('outcome-analytics.json')||{};return {assurance:a,calibration,outcomes,ablation:a.ablation||{}}};
const walk=(obj,fn,path='root')=>{if(obj==null)return;if(Array.isArray(obj)){fn(obj,path);obj.forEach((v,i)=>walk(v,fn,`${path}[${i}]`));return}if(typeof obj==='object')Object.entries(obj).forEach(([k,v])=>walk(v,fn,`${path}.${k}`))};
const findRecords=obj=>{const out=[];walk(obj,(arr,path)=>{if(arr.length&&arr.length<5000&&arr.some(x=>x&&typeof x==='object'&&('symbol'in x||'coin'in x||'asset'in x)))arr.forEach(x=>{if(x&&typeof x==='object')out.push({...x,__path:path})})});return out};
const journal=async()=>findRecords(await get('decision-journal.json')||{});
const outcomeRecords=async()=>findRecords(await get('outcome-analytics.json')||{});
const holdings=()=>{try{return JSON.parse(localStorage.getItem('wavelength_portfolio_v1')||'[]')}catch{return[]}};
const saveHoldings=v=>localStorage.setItem('wavelength_portfolio_v1',JSON.stringify(v));
const parseSymbols=q=>[...new Set((String(q).toUpperCase().match(/\b[A-Z]{2,8}\b/g)||[]).filter(x=>!['WHAT','WHY','SHOW','BEST','BUY','SELL','WATCH','PROOF','VERSUS','COMPARE','WITH','THE','AND','FOR','NOW'].includes(x)))];
const CONTEXT_KEY='wavelength_research_context_v1';
const cleanSymbol=v=>String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'');
const researchContext=()=>{const q=new URLSearchParams(location.search),direct=cleanSymbol(q.get('symbol')||q.get('candidate'));if(direct)return direct;const fromQuestion=parseSymbols(q.get('q')||'')[0];if(fromQuestion)return cleanSymbol(fromQuestion);try{return cleanSymbol(localStorage.getItem(CONTEXT_KEY)||'')}catch{return''}};
const rememberContext=s=>{s=cleanSymbol(s);if(!s)return;try{localStorage.setItem(CONTEXT_KEY,s)}catch{}};
function bridgeContext(){const q=new URLSearchParams(location.search),explicit=cleanSymbol(q.get('symbol')||q.get('candidate'))||cleanSymbol(parseSymbols(q.get('q')||'')[0]);if(explicit)rememberContext(explicit);const sym=explicit||researchContext();if(!sym)return;const targets={'decision-room.html':'symbol','replay.html':'symbol','thesis-watch.html':'symbol','evidence-map.html':'symbol','proof-ledger.html':'symbol','portfolio-intelligence.html':'candidate'};document.querySelectorAll('a[href]').forEach(a=>{let u;try{u=new URL(a.getAttribute('href'),location.href)}catch{return}const file=(u.pathname.split('/').pop()||'').toLowerCase(),param=targets[file];if(!param)return;if(!u.searchParams.get(param))u.searchParams.set(param,sym);a.setAttribute('href',(u.pathname.split('/').pop()||file)+u.search+u.hash)});const file=(location.pathname.split('/').pop()||'').toLowerCase();if(file==='portfolio-intelligence.html'){const fill=()=>{const el=document.getElementById('candidate');if(!el)return false;if(!el.value)el.value=sym;return true};if(!fill()){let n=0,t=setInterval(()=>{if(fill()||++n>80)clearInterval(t)},100)}}}
window.WavelengthOS={get,esc,num,pct,title,assurance,assets,asset,ranked,score,grade,quality,params,boot,dimensions,committee,objections,positives,proof,findRecords,journal,outcomeRecords,holdings,saveHoldings,parseSymbols,deskMap,researchContext,rememberContext,bridgeContext};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{bridgeContext();setTimeout(bridgeContext,250);setTimeout(bridgeContext,1200)});else{bridgeContext();setTimeout(bridgeContext,250)}
})();